Iuvo Unity: IuvoUnity.BaseClasses.DamageComponent Class Reference
IuvoUnity.BaseClasses.DamageComponent Class Reference
Public Member Functions
DamageComponent (float damageAmount, DamageType damageCategory)
void DealDamage (HealthComponent healthComp)
Public Attributes
DamageTypeComponent DamageType
float DamageValue
Constructor & Destructor Documentation
DamageComponent()
IuvoUnity.BaseClasses.DamageComponent.DamageComponent (float damageAmount, DamageType damageCategory)
            {
                if (damageAmount < 0.0f)
                {
                    IuvoDebug.DebugLogWarning("Damage amount cannot be negative. Setting to 1.");
                    DamageValue = 1.0f;
                    DamageType = new DamageTypeComponent { DamageCategory = damageCategory };
                    return;
                }
                DamageValue = damageAmount;
                DamageType = new DamageTypeComponent { DamageCategory = damageCategory };
            }
References DamageType, DamageValue, and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
Member Function Documentation
DealDamage()
void IuvoUnity.BaseClasses.DamageComponent.DealDamage (HealthComponent healthComp)
Implements IuvoUnity.BaseClasses.IDealDamage.
            {
                if (healthComp == null)
                {
                    IuvoDebug.DebugLogWarning("HealthComponent is null. Cannot deal damage.");
                    return;
                }
                if (DamageValue < 0.0f)
                {
                    IuvoDebug.DebugLogWarning("Damage amount cannot be negative.");
                    return;
                }
                healthComp.TakeDamage(this);
            }
References DamageValue, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), and IuvoUnity.BaseClasses.HealthComponent.TakeDamage().
Member Data Documentation
DamageType
DamageTypeComponent IuvoUnity.BaseClasses.DamageComponent.DamageType
Referenced by DamageComponent().
DamageValue
float IuvoUnity.BaseClasses.DamageComponent.DamageValue
Referenced by DamageComponent(), DealDamage(), and IuvoUnity.BaseClasses.HealthComponent.TakeDamage().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/RPG/DamageComponent.cs