Iuvo Unity: IuvoUnity.BaseClasses.HealthComponent Class Reference
IuvoUnity.BaseClasses.HealthComponent Class Reference
Public Member Functions
float HealthPercentage ()
bool IsDead ()
bool TryGetHealthConfig (out HealthConfiguration config)
virtual void UpdateMaxHealth ()
void Start ()
void OnDestroy ()
virtual void Heal (float amount)
void HealInRadius (float amount)
void HealInRadiusWithFalloff (float amount)
void HealRandomInRadius (float amount)
void HealRandomInRadiusWithFalloff (float amount)
virtual void TakeDamage (DamageComponent damageComponent)
virtual void OnConfigure ()
virtual void OnReconfigure ()
Public Attributes
int CurrentLevel = 1
FlexibleEvent< float > OnGainHealth = new FlexibleEvent<float>()
FlexibleEvent< float > OnLoseHealth = new FlexibleEvent<float>()
FlexibleEvent< float, float > OnHealthChanged = new FlexibleEvent<float, float>()
FlexibleEvent< DamageComponent > OnHealthDepleted = new FlexibleEvent<DamageComponent>()
Properties
float CurrentHealth = 25 [get, private set]
float MaxHealth = 25 [get, private set]
bool Configured [get, set]
bool Reconfigured [get, set]
Private Attributes
HealthConfiguration HealthConfig
Transform parent
bool isDead = false
Member Function Documentation
Heal()
virtual void IuvoUnity.BaseClasses.HealthComponent.Heal (float amount) virtual
Implements IuvoUnity.BaseClasses.IHeal.
            {
                if (amount < 0.0f)
                {
                    IuvoDebug.DebugLogWarning("Heal amount cannot be negative.");
                    return;
                }
                CurrentHealth += amount;
                if (CurrentHealth > MaxHealth)
                {
                    CurrentHealth = MaxHealth;
                }
                OnGainHealth.Invoke(amount);
                OnHealthChanged.Invoke(CurrentHealth, MaxHealth);
            }
References CurrentHealth, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), MaxHealth, OnGainHealth, and OnHealthChanged.
HealInRadius()
void IuvoUnity.BaseClasses.HealthComponent.HealInRadius (float amount)
            {
                // noop
            }
HealInRadiusWithFalloff()
void IuvoUnity.BaseClasses.HealthComponent.HealInRadiusWithFalloff (float amount)
            {
                //noop
            }
HealRandomInRadius()
void IuvoUnity.BaseClasses.HealthComponent.HealRandomInRadius (float amount)
            {
                //noop
            }
HealRandomInRadiusWithFalloff()
void IuvoUnity.BaseClasses.HealthComponent.HealRandomInRadiusWithFalloff (float amount)
            {
                //noop
            }
HealthPercentage()
float IuvoUnity.BaseClasses.HealthComponent.HealthPercentage ()
            {
                if (isDead)
                {
                    return 0f; // If dead, health percentage is 0
                }
                return (float)CurrentHealth / MaxHealth;
            }
References CurrentHealth, isDead, and MaxHealth.
IsDead()
bool IuvoUnity.BaseClasses.HealthComponent.IsDead ()
=> isDead;
References isDead.
OnConfigure()
virtual void IuvoUnity.BaseClasses.HealthComponent.OnConfigure () virtual
Implements IuvoUnity.Interfaces.IConfigurable.
            {
            }
OnDestroy()
void IuvoUnity.BaseClasses.HealthComponent.OnDestroy ()
            {
                if (HealthConfig != null)
                {
                    HealthConfig.OnDisable();
                    IuvoDebug.DebugLog("HealthConfiguration disabled.");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), and HealthConfig.
OnReconfigure()
virtual void IuvoUnity.BaseClasses.HealthComponent.OnReconfigure () virtual
Implements IuvoUnity.Interfaces.IReconfigurable.
            {
            }
Start()
void IuvoUnity.BaseClasses.HealthComponent.Start ()
            {
                if (parent == null)
                {
                    parent = transform.parent;
                }
                if (parent == null)
                {
                    IuvoDebug.DebugLogWarning("HealthComponent has no parent transform.");
                }
                if (HealthConfig != null)
                {
                    //CurrentLevel = HealthConfig.LoadLevel();
                    UpdateMaxHealth();
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), HealthConfig, parent, and UpdateMaxHealth().
TakeDamage()
virtual void IuvoUnity.BaseClasses.HealthComponent.TakeDamage (DamageComponent damageComponent) virtual
Implements IuvoUnity.BaseClasses.ITakeDamage.
            {
                if (damageComponent == null || damageComponent.DamageValue < 0.0f)
                {
                    IuvoDebug.DebugLogWarning("Invalid DamageComponent.");
                    return;
                }
                if (this is IShield shieldComp)
                {
                    shieldComp.AbsorbDamage(damageComponent);
                    if (damageComponent.DamageValue <= 0.0f)
                    {
                        return; // All damage absorbed by shield
                    }
                }
                else if (parent != null)
                {
                    IShield[] shields = parent.GetComponentsInChildren<IShield>();
                    foreach (var shield in shields)
                    {
                        shield.AbsorbDamage(damageComponent);
                        if (damageComponent.DamageValue <= 0.0f)
{
                            return; // All damage absorbed by shield
                        }
                    }
                }
                CurrentHealth -= damageComponent.DamageValue;
                OnLoseHealth.Invoke(damageComponent.DamageValue);
                if (CurrentHealth <= 0.0f)
                {
                    CurrentHealth = 0;
                    if (!isDead)
                    {
                        isDead = true;
                        OnHealthDepleted.Invoke(damageComponent);
                    }
                }
                OnHealthChanged.Invoke(CurrentHealth, MaxHealth);
            }
References CurrentHealth, IuvoUnity.BaseClasses.DamageComponent.DamageValue, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), isDead, MaxHealth, OnHealthChanged, OnHealthDepleted, OnLoseHealth, and parent.
Referenced by IuvoUnity.BaseClasses.DamageComponent.DealDamage().
TryGetHealthConfig()
bool IuvoUnity.BaseClasses.HealthComponent.TryGetHealthConfig (out HealthConfiguration config)
            {
                if (HealthConfig)
                {
                    config = HealthConfig;
                    return true;
                }
                config = null;
                return false;
            }
References HealthConfig.
UpdateMaxHealth()
virtual void IuvoUnity.BaseClasses.HealthComponent.UpdateMaxHealth () virtual
            {
                if (HealthConfig != null)
                {
                    int newMaxHealth = HealthConfig.GetMaxHealthAtLevel(CurrentLevel);
                    if (newMaxHealth < 0)
                    {
                        IuvoDebug.DebugLogError("Failed to update MaxHealth due to invalid level or configuration.");
                        return;
                    }
                    MaxHealth = newMaxHealth;
                    if (CurrentHealth > MaxHealth)
                    {
                        CurrentHealth = MaxHealth; // Ensure current health does not exceed max health
                    }
                }
            }
References CurrentHealth, CurrentLevel, IuvoUnity.Debug.IuvoDebug.DebugLogError(), HealthConfig, and MaxHealth.
Referenced by Start().
Member Data Documentation
CurrentLevel
int IuvoUnity.BaseClasses.HealthComponent.CurrentLevel = 1
Referenced by UpdateMaxHealth().
HealthConfig
HealthConfiguration IuvoUnity.BaseClasses.HealthComponent.HealthConfig private
Referenced by OnDestroy(), Start(), TryGetHealthConfig(), and UpdateMaxHealth().
isDead
bool IuvoUnity.BaseClasses.HealthComponent.isDead = false private
Referenced by HealthPercentage(), IsDead(), and TakeDamage().
OnGainHealth
FlexibleEvent<float> IuvoUnity.BaseClasses.HealthComponent.OnGainHealth = new FlexibleEvent<float>()
Referenced by Heal().
OnHealthChanged
FlexibleEvent<float, float> IuvoUnity.BaseClasses.HealthComponent.OnHealthChanged = new FlexibleEvent<float, float>()
Referenced by Heal(), and TakeDamage().
OnHealthDepleted
FlexibleEvent<DamageComponent> IuvoUnity.BaseClasses.HealthComponent.OnHealthDepleted = new FlexibleEvent<DamageComponent>()
Referenced by TakeDamage().
OnLoseHealth
FlexibleEvent<float> IuvoUnity.BaseClasses.HealthComponent.OnLoseHealth = new FlexibleEvent<float>()
Referenced by TakeDamage().
parent
Transform IuvoUnity.BaseClasses.HealthComponent.parent private
Referenced by Start(), and TakeDamage().
Property Documentation
Configured
bool IuvoUnity.BaseClasses.HealthComponent.Configured get set
Implements IuvoUnity.Interfaces.IConfigurable.
{ get; set; }
CurrentHealth
float IuvoUnity.BaseClasses.HealthComponent.CurrentHealth = 25 get private set
{ get; private set; } = 25;
Referenced by Heal(), HealthPercentage(), TakeDamage(), and UpdateMaxHealth().
MaxHealth
float IuvoUnity.BaseClasses.HealthComponent.MaxHealth = 25 get private set
{ get; private set; } = 25;
Referenced by Heal(), HealthPercentage(), TakeDamage(), and UpdateMaxHealth().
Reconfigured
bool IuvoUnity.BaseClasses.HealthComponent.Reconfigured get set
Implements IuvoUnity.Interfaces.IReconfigurable.
{ get; set; }
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/RPG/HealthComponent.cs