Iuvo Unity: IuvoUnity.StateMachines.HSM.State Class Reference
IuvoUnity.StateMachines.HSM.State Class Reference abstract
Public Member Functions
State (StateMachine machine, State parent=null)
State Leaf ()
IEnumerable< State > PathToRoot ()
Public Attributes
readonly StateMachine Machine
State Parent
State ActiveChild
Protected Member Functions
virtual State GetInitialState ()
virtual State GetTransition ()
virtual void OnEnter ()
virtual void OnExit ()
virtual void OnUpdate (float deltaTime)
Constructor & Destructor Documentation
State()
IuvoUnity.StateMachines.HSM.State.State (StateMachine machine, State parent = null)
                {
                    Machine = machine;
                    Parent = parent;
                }
References Machine, Parent, and State().
Referenced by IuvoUnity.Statemachines.HSM.Airborne.Airborne(), IuvoUnity.Statemachines.HSM.DoubleJump.DoubleJump(), IuvoUnity.Statemachines.HSM.Falling.Falling(), IuvoUnity.Statemachines.HSM.Flying.Flying(), IuvoUnity.Statemachines.HSM.Grounded.GetInitialState(), IuvoUnity.Statemachines.HSM.PlayerRoot.GetInitialState(), GetInitialState(), IuvoUnity.Statemachines.HSM.Airborne.GetTransition(), IuvoUnity.Statemachines.HSM.Grounded.GetTransition(), IuvoUnity.Statemachines.HSM.Idle.GetTransition(), IuvoUnity.Statemachines.HSM.Move.GetTransition(), IuvoUnity.Statemachines.HSM.PlayerRoot.GetTransition(), GetTransition(), IuvoUnity.Statemachines.HSM.Grounded.Grounded(), IuvoUnity.Statemachines.HSM.Idle.Idle(), IuvoUnity.Statemachines.HSM.Jumping.Jumping(), IuvoUnity.Statemachines.HSM.Landing.Landing(), Leaf(), IuvoUnity.Statemachines.HSM.Move.Move(), PathToRoot(), and State().
Member Function Documentation
GetInitialState()
virtual State IuvoUnity.StateMachines.HSM.State.GetInitialState () protected virtual
Reimplemented in IuvoUnity.Statemachines.HSM.Grounded, and IuvoUnity.Statemachines.HSM.PlayerRoot.
=> null; // Initial child to enter when this state starts (null = this is the leaf)
References State().
GetTransition()
virtual State IuvoUnity.StateMachines.HSM.State.GetTransition () protected virtual
Reimplemented in IuvoUnity.Statemachines.HSM.Airborne, IuvoUnity.Statemachines.HSM.Grounded, IuvoUnity.Statemachines.HSM.Idle, IuvoUnity.Statemachines.HSM.Move, and IuvoUnity.Statemachines.HSM.PlayerRoot.
=> null; // Target state to switch to (null = no transition)
References State().
Leaf()
State IuvoUnity.StateMachines.HSM.State.Leaf ()
                {
                    State s = this;
                    while (s.ActiveChild != null) s = s.ActiveChild;
                    return s;
                }
References ActiveChild, and State().
OnEnter()
virtual void IuvoUnity.StateMachines.HSM.State.OnEnter () protected virtual
Reimplemented in IuvoUnity.Statemachines.HSM.Airborne, and IuvoUnity.Statemachines.HSM.Idle.
{ }
OnExit()
virtual void IuvoUnity.StateMachines.HSM.State.OnExit () protected virtual
{ }
OnUpdate()
virtual void IuvoUnity.StateMachines.HSM.State.OnUpdate (float deltaTime) protected virtual
Reimplemented in IuvoUnity.Statemachines.HSM.Move.
{ }
PathToRoot()
IEnumerable< State > IuvoUnity.StateMachines.HSM.State.PathToRoot ()
                {
                    for (State s = this; s != null; s = s.Parent) yield return s;
                }
References State().
Member Data Documentation
ActiveChild
State IuvoUnity.StateMachines.HSM.State.ActiveChild
Referenced by Leaf().
Machine
readonly StateMachine IuvoUnity.StateMachines.HSM.State.Machine
Referenced by State().
Parent
State IuvoUnity.StateMachines.HSM.State.Parent
Referenced by IuvoUnity.StateMachines.HSM.StateMachine.ChangeState(), IuvoUnity.Statemachines.HSM.Airborne.GetTransition(), IuvoUnity.Statemachines.HSM.Grounded.GetTransition(), IuvoUnity.Statemachines.HSM.Idle.GetTransition(), IuvoUnity.Statemachines.HSM.Move.GetTransition(), IuvoUnity.StateMachines.HSM.TransitionSequencer.LCA(), and State().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/StateMachine/HierarchicalStateMachine/State.cs