Iuvo Unity: IuvoUnity.DataStructs.TreeNode< T > Class Template Reference
IuvoUnity.DataStructs.TreeNode< T > Class Template Reference
Public Member Functions
TreeNode (T data)
void AddChild (TreeNode< T > child)
bool RemoveChild (TreeNode< T > child)
Properties
Link< T > Link [get, private set]
TreeNode< T > Parent [get, private set]
List< TreeNode< T > > Children [get, private set]
T Data [get, set]
Member Function Documentation
AddChild()
void IuvoUnity.DataStructs.TreeNode< T >.AddChild (TreeNode< T > child)
            {
                if (child == null) return;
                child.Parent = this;
                Children.Add(child);
            }
References Children, and TreeNode().
RemoveChild()
bool IuvoUnity.DataStructs.TreeNode< T >.RemoveChild (TreeNode< T > child)
            {
                if (child == null) return false;
                bool removed = Children.Remove(child);
                if (removed)
                    child.Parent = null;
                return removed;
            }
References Children, and TreeNode().
TreeNode()
IuvoUnity.DataStructs.TreeNode< T >.TreeNode (T data)
            {
                Link = new Link<T>(data);
                Children = new List<TreeNode<T>>();
            }
References Children, and Link.
Referenced by AddChild(), and RemoveChild().
Property Documentation
Children
List<TreeNode<T> > IuvoUnity.DataStructs.TreeNode< T >.Children get private set
{ get; private set; }
Referenced by AddChild(), RemoveChild(), and TreeNode().
Data
T IuvoUnity.DataStructs.TreeNode< T >.Data get set
            {
                get => Link.GetData();
                set => Link.SetData(value);
            }
Link
Link<T> IuvoUnity.DataStructs.TreeNode< T >.Link get private set
{ get; private set; }
Referenced by TreeNode().
Parent
TreeNode<T> IuvoUnity.DataStructs.TreeNode< T >.Parent get private set
{ get; private set; }
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/TreeNode.cs