Iuvo Unity: IuvoUnity.DataStructs.PlayerHandlersContext Class Reference
IuvoUnity.DataStructs.PlayerHandlersContext Class Reference
Public Member Functions
PlayerHandlersContext ()
void Dispose ()
T GetHandler< T > (ContextKey_PLAYER_HANDLERS key)
void SetHandler (ContextKey_PLAYER_HANDLERS key, IPlayerHandler handler)
Private Member Functions
void ClearHandlers ()
Private Attributes
ConcurrentDictionary< ContextKey_PLAYER_HANDLERS, IPlayerHandler > handlers = new ConcurrentDictionary<ContextKey_PLAYER_HANDLERS, IPlayerHandler>()
Constructor & Destructor Documentation
PlayerHandlersContext()
IuvoUnity.DataStructs.PlayerHandlersContext.PlayerHandlersContext ()
            {
                foreach (ContextKey_PLAYER_HANDLERS key in System.Enum.GetValues(typeof(ContextKey_PLAYER_HANDLERS)))
                {
                    handlers[key] = null;
                }
            }
References handlers.
Member Function Documentation
ClearHandlers()
void IuvoUnity.DataStructs.PlayerHandlersContext.ClearHandlers () private
            {
                handlers.Clear();
            }
References handlers.
Referenced by Dispose().
Dispose()
void IuvoUnity.DataStructs.PlayerHandlersContext.Dispose ()
Implements IuvoUnity.Interfaces.IContext.
            {
                ClearHandlers();
            }
References ClearHandlers().
GetHandler< T >()
T IuvoUnity.DataStructs.PlayerHandlersContext.GetHandler< T > (ContextKey_PLAYER_HANDLERS key)
Type Constraints
T : class
T : IPlayerHandler
                                                                           : class, IPlayerHandler
            {
                return handlers.TryGetValue(key, out var handler) ? handler as T : null;
            }
References handlers.
SetHandler()
void IuvoUnity.DataStructs.PlayerHandlersContext.SetHandler (ContextKey_PLAYER_HANDLERS key, IPlayerHandler handler)
            {
                handlers[key] = handler;
            }
References handlers.
Member Data Documentation
handlers
ConcurrentDictionary<ContextKey_PLAYER_HANDLERS, IPlayerHandler> IuvoUnity.DataStructs.PlayerHandlersContext.handlers = new ConcurrentDictionary<ContextKey_PLAYER_HANDLERS, IPlayerHandler>() private
Referenced by ClearHandlers(), GetHandler< T >(), PlayerHandlersContext(), and SetHandler().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/PlayerHandlerContext.cs