Iuvo Unity: IuvoUnity.ProceduralGeneration.ProceduralMesh Class Reference
IuvoUnity.ProceduralGeneration.ProceduralMesh Class Reference abstract
Public Member Functions
void Generate ()
Public Attributes
List< Vector3 > vertices = new List<Vector3>()
List< int > triangles = new List<int>()
List< Vector2 > uvs = new List<Vector2>()
List< Vector3 > normals = new List<Vector3>()
Mesh mesh
string meshName = "ProceduralMesh"
Material meshMaterial
Protected Member Functions
virtual void Awake ()
void GenerateMesh ()
virtual void ClearMeshData ()
virtual void ApplyMesh ()
Member Function Documentation
ApplyMesh()
virtual void IuvoUnity.ProceduralGeneration.ProceduralMesh.ApplyMesh () protected virtual
Reimplemented in IuvoUnity.ProceduralGeneration.ProceduralStripMesh.
            {
                if (mesh == null)
                {
                    mesh = new Mesh { name = meshName };
                }
                mesh.Clear();
                mesh.SetVertices(vertices);
                mesh.SetTriangles(triangles, 0);
                if (uvs.Count == vertices.Count)
                    mesh.SetUVs(0, uvs);
                else
                    mesh.uv = new Vector2[vertices.Count];
                if (normals.Count == vertices.Count)
                    mesh.SetNormals(normals);
                else
                    mesh.RecalculateNormals();
                mesh.RecalculateBounds();
                GetComponent<MeshFilter>().mesh = mesh;
                if (meshMaterial != null)
                    GetComponent<MeshRenderer>().material = meshMaterial;
            }
References mesh, meshMaterial, meshName, normals, triangles, uvs, and vertices.
Referenced by Generate().
Awake()
virtual void IuvoUnity.ProceduralGeneration.ProceduralMesh.Awake () protected virtual
=> Generate();
ClearMeshData()
virtual void IuvoUnity.ProceduralGeneration.ProceduralMesh.ClearMeshData () protected virtual
Reimplemented in IuvoUnity.ProceduralGeneration.ProceduralStripMesh.
            {
                vertices.Clear();
                triangles.Clear();
                uvs.Clear();
                normals.Clear();
            }
References normals, triangles, uvs, and vertices.
Referenced by Generate().
Generate()
void IuvoUnity.ProceduralGeneration.ProceduralMesh.Generate ()
            {
                ClearMeshData();
                GenerateMesh();
                ApplyMesh();
            }
References ApplyMesh(), ClearMeshData(), and GenerateMesh().
Referenced by IuvoUnity.ProceduralGeneration.ProceduralStripMesh.SetPairs().
GenerateMesh()
void IuvoUnity.ProceduralGeneration.ProceduralMesh.GenerateMesh () abstract protected
Referenced by Generate().
Member Data Documentation
mesh
Mesh IuvoUnity.ProceduralGeneration.ProceduralMesh.mesh
Referenced by ApplyMesh(), IuvoUnity.ProceduralGeneration.ProceduralStripMesh.ApplyMesh(), IuvoUnity.ProceduralGeneration.ProceduralGridMesh.GenerateMesh(), and IuvoUnity.ProceduralGeneration.TerrainGenerator.GenerateMesh().
meshMaterial
Material IuvoUnity.ProceduralGeneration.ProceduralMesh.meshMaterial
Referenced by ApplyMesh().
meshName
string IuvoUnity.ProceduralGeneration.ProceduralMesh.meshName = "ProceduralMesh"
Referenced by ApplyMesh().
normals
List<Vector3> IuvoUnity.ProceduralGeneration.ProceduralMesh.normals = new List<Vector3>()
Referenced by ApplyMesh(), ClearMeshData(), IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateBetweenStrips(), and IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateMesh().
triangles
List<int> IuvoUnity.ProceduralGeneration.ProceduralMesh.triangles = new List<int>()
Referenced by ApplyMesh(), ClearMeshData(), IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateBetweenStrips(), IuvoUnity.ProceduralGeneration.ProceduralCylinder.GenerateMesh(), IuvoUnity.ProceduralGeneration.ProceduralGridMesh.GenerateMesh(), and IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateMesh().
uvs
List<Vector2> IuvoUnity.ProceduralGeneration.ProceduralMesh.uvs = new List<Vector2>()
Referenced by ApplyMesh(), ClearMeshData(), IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateBetweenStrips(), IuvoUnity.ProceduralGeneration.ProceduralCylinder.GenerateMesh(), IuvoUnity.ProceduralGeneration.ProceduralGridMesh.GenerateMesh(), and IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateMesh().
vertices
List<Vector3> IuvoUnity.ProceduralGeneration.ProceduralMesh.vertices = new List<Vector3>()
Referenced by ApplyMesh(), IuvoUnity.ProceduralGeneration.ProceduralStripMesh.ApplyMesh(), ClearMeshData(), IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateBetweenStrips(), IuvoUnity.ProceduralGeneration.ProceduralCylinder.GenerateMesh(), IuvoUnity.ProceduralGeneration.ProceduralGridMesh.GenerateMesh(), IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateMesh(), and IuvoUnity.ProceduralGeneration.TerrainGenerator.GenerateMesh().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ProceduralGenerationBases/ProceduralMesh/ProceduralMesh.cs