Iuvo Unity: IuvoUnity.IuvoTime.TimeKeeper Class Reference
IuvoUnity.IuvoTime.TimeKeeper Class Reference
Static Public Member Functions
static bool IsDecrement (Timer_Activity_Mode mode)
static bool IsIncrement (Timer_Activity_Mode mode)
static bool IsStopwatch (Timer_Activity_Mode mode)
static bool IsLoopingTimer (Timer_Activity_Mode mode)
static bool IsCustomTimer (Timer_Activity_Mode mode)
static bool IsSuperLongTerm (Timer_Activity_Mode mode)
static bool IsLongTerm (Timer_Activity_Mode mode)
static bool IsShortTerm (Timer_Activity_Mode mode)
static string FormatTime (float time)
static string FormatTimerDuration (Timer timer)
static string FormatElapsedTime (Timer timer)
static string FormatRemainingTime (Timer timer)
static Timer CreateTimer (TimerConfiguration configuration)
Static Public Attributes
static float SUPER_LONG_TERM_MAX = 18000000
static float SUPER_LONG_TERM_MIN = 36000.0f
static float LONG_TERM_MAX = 35999.9f
static float LONG_TERM_MIN = 300.0f
static float SHORT_TERM_MAX = 259.9f
static float SHORT_TERM_MIN = 0.5f
static TimerFactory factory
Member Function Documentation
CreateTimer()
Timer IuvoUnity.IuvoTime.TimeKeeper.CreateTimer (TimerConfiguration configuration) static
            {
                if (factory == null)
                {
                    factory = new TimerFactory();
                }
                return factory.Create(configuration);
            }
References factory.
FormatElapsedTime()
string IuvoUnity.IuvoTime.TimeKeeper.FormatElapsedTime (Timer timer) static
            {
                if (timer == null)
                {
                    return "00:00:00";
                }
                return FormatTime(timer.Elapsed());
            }
References IuvoUnity.DataStructs.Timer.Elapsed(), and FormatTime().
Referenced by TimerTestUI.Start(), and TimerTestUI.Update().
FormatRemainingTime()
string IuvoUnity.IuvoTime.TimeKeeper.FormatRemainingTime (Timer timer) static
            {
                if (timer == null)
                {
                    return "00:00:00";
                }
                return FormatTime(timer.Remaining());
            }
References FormatTime(), and IuvoUnity.DataStructs.Timer.Remaining().
Referenced by TimerTestUI.Update().
FormatTime()
string IuvoUnity.IuvoTime.TimeKeeper.FormatTime (float time) static
            {
                if (time < 0)
                {
                    return "00:00:00";
                }
                int hours = Mathf.FloorToInt(time / 3600);
                int minutes = Mathf.FloorToInt((time % 3600) / 60);
                int seconds = Mathf.FloorToInt(time % 60);
                int milliseconds = Mathf.FloorToInt((time * 1000) % 1000);
                return string.Format("{0:D2}:{1:D2}:{2:D2}:{3:D3}", hours, minutes, seconds, milliseconds);
            }
Referenced by FormatElapsedTime(), FormatRemainingTime(), and FormatTimerDuration().
FormatTimerDuration()
string IuvoUnity.IuvoTime.TimeKeeper.FormatTimerDuration (Timer timer) static
            {
                if (timer == null)
                {
                    return "00:00:00";
                }
                return FormatTime(timer.Duration());
            }
References IuvoUnity.DataStructs.Timer.Duration(), and FormatTime().
IsCustomTimer()
bool IuvoUnity.IuvoTime.TimeKeeper.IsCustomTimer (Timer_Activity_Mode mode) static
            {
                if (mode == Timer_Activity_Mode.CUSTOM_TIMER)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
Referenced by IuvoUnity.DataStructs.MultiTimer.GetDuration().
IsDecrement()
bool IuvoUnity.IuvoTime.TimeKeeper.IsDecrement (Timer_Activity_Mode mode) static
            {
                if (mode == Timer_Activity_Mode.SUPER_LONG_TERM_DECREMENT ||
                       mode == Timer_Activity_Mode.LONG_TERM_DECREMENT ||
                       mode == Timer_Activity_Mode.SHORT_DECREMENT ||
                       mode == Timer_Activity_Mode.DECREMENT)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
Referenced by IuvoUnity.DataStructs.MultiTimer.Elapsed(), IuvoUnity.DataStructs.MultiTimer.GetDuration(), IuvoUnity.DataStructs.MultiTimer.IsRunning(), IuvoUnity.DataStructs.LoopingTimer.Pause(), IuvoUnity.DataStructs.MultiTimer.Pause(), IuvoUnity.DataStructs.MultiTimer.Remaining(), IuvoUnity.DataStructs.LoopingTimer.Reset(), IuvoUnity.DataStructs.MultiTimer.Reset(), IuvoUnity.DataStructs.LoopingTimer.Resume(), IuvoUnity.DataStructs.MultiTimer.Resume(), IuvoUnity.DataStructs.MultiTimer.SetDuration(), IuvoUnity.DataStructs.LoopingTimer.Start(), IuvoUnity.DataStructs.MultiTimer.Start(), IuvoUnity.DataStructs.LoopingTimer.Tick(), IuvoUnity.DataStructs.MultiTimer.Tick(), and TimerTestUI.Update().
IsIncrement()
bool IuvoUnity.IuvoTime.TimeKeeper.IsIncrement (Timer_Activity_Mode mode) static
            {
                if (mode == Timer_Activity_Mode.SUPER_LONG_TERM_INCREMENT ||
                       mode == Timer_Activity_Mode.LONG_TERM_INCREMENT ||
                       mode == Timer_Activity_Mode.SHORT_TERM_INCREMENT ||
                       mode == Timer_Activity_Mode.INCREMENT)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
Referenced by IuvoUnity.DataStructs.MultiTimer.Elapsed(), IuvoUnity.DataStructs.MultiTimer.GetDuration(), IuvoUnity.DataStructs.MultiTimer.IsRunning(), IuvoUnity.DataStructs.LoopingTimer.Pause(), IuvoUnity.DataStructs.MultiTimer.Pause(), IuvoUnity.DataStructs.MultiTimer.Remaining(), IuvoUnity.DataStructs.LoopingTimer.Reset(), IuvoUnity.DataStructs.MultiTimer.Reset(), IuvoUnity.DataStructs.LoopingTimer.Resume(), IuvoUnity.DataStructs.MultiTimer.Resume(), IuvoUnity.DataStructs.MultiTimer.SetDuration(), IuvoUnity.DataStructs.LoopingTimer.Start(), IuvoUnity.DataStructs.MultiTimer.Start(), IuvoUnity.DataStructs.LoopingTimer.Tick(), IuvoUnity.DataStructs.MultiTimer.Tick(), and TimerTestUI.Update().
IsLongTerm()
bool IuvoUnity.IuvoTime.TimeKeeper.IsLongTerm (Timer_Activity_Mode mode) static
            {
                if (mode == Timer_Activity_Mode.SUPER_LONG_TERM_DECREMENT ||
                       mode == Timer_Activity_Mode.LONG_TERM_DECREMENT ||
                       mode == Timer_Activity_Mode.SUPER_LONG_TERM_INCREMENT ||
                       mode == Timer_Activity_Mode.LONG_TERM_INCREMENT ||
                       mode == Timer_Activity_Mode.SUPER_LONG_TERM_STOPWATCH ||
                       mode == Timer_Activity_Mode.LONG_TERM_STOPWATCH)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
IsLoopingTimer()
bool IuvoUnity.IuvoTime.TimeKeeper.IsLoopingTimer (Timer_Activity_Mode mode) static
            {
                if (mode == Timer_Activity_Mode.LOOPING_TIMER)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
IsShortTerm()
bool IuvoUnity.IuvoTime.TimeKeeper.IsShortTerm (Timer_Activity_Mode mode) static
            {
                if (mode == Timer_Activity_Mode.SHORT_DECREMENT ||
                       mode == Timer_Activity_Mode.DECREMENT ||
                       mode == Timer_Activity_Mode.SHORT_TERM_INCREMENT ||
                       mode == Timer_Activity_Mode.INCREMENT ||
                       mode == Timer_Activity_Mode.SHORT_TERM_STOPWATCH ||
                       mode == Timer_Activity_Mode.STOPWATCH)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
IsStopwatch()
bool IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch (Timer_Activity_Mode mode) static
            {
                if (mode == Timer_Activity_Mode.SUPER_LONG_TERM_STOPWATCH ||
                       mode == Timer_Activity_Mode.LONG_TERM_STOPWATCH ||
                       mode == Timer_Activity_Mode.SHORT_TERM_STOPWATCH ||
                       mode == Timer_Activity_Mode.STOPWATCH)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
Referenced by IuvoUnity.DataStructs.MultiTimer.Elapsed(), IuvoUnity.DataStructs.MultiTimer.GetDuration(), IuvoUnity.DataStructs.MultiTimer.IsRunning(), IuvoUnity.DataStructs.MultiTimer.Pause(), IuvoUnity.DataStructs.MultiTimer.Remaining(), IuvoUnity.DataStructs.MultiTimer.Reset(), IuvoUnity.DataStructs.MultiTimer.Resume(), IuvoUnity.DataStructs.MultiTimer.SetDuration(), IuvoUnity.DataStructs.MultiTimer.Start(), IuvoUnity.DataStructs.MultiTimer.Tick(), and TimerTestUI.Update().
IsSuperLongTerm()
bool IuvoUnity.IuvoTime.TimeKeeper.IsSuperLongTerm (Timer_Activity_Mode mode) static
            {
                if (mode == Timer_Activity_Mode.SUPER_LONG_TERM_DECREMENT ||
                       mode == Timer_Activity_Mode.SUPER_LONG_TERM_INCREMENT ||
                       mode == Timer_Activity_Mode.SUPER_LONG_TERM_STOPWATCH)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
Member Data Documentation
factory
TimerFactory IuvoUnity.IuvoTime.TimeKeeper.factory static
Referenced by CreateTimer().
LONG_TERM_MAX
float IuvoUnity.IuvoTime.TimeKeeper.LONG_TERM_MAX = 35999.9f static
LONG_TERM_MIN
float IuvoUnity.IuvoTime.TimeKeeper.LONG_TERM_MIN = 300.0f static
SHORT_TERM_MAX
float IuvoUnity.IuvoTime.TimeKeeper.SHORT_TERM_MAX = 259.9f static
SHORT_TERM_MIN
float IuvoUnity.IuvoTime.TimeKeeper.SHORT_TERM_MIN = 0.5f static
SUPER_LONG_TERM_MAX
float IuvoUnity.IuvoTime.TimeKeeper.SUPER_LONG_TERM_MAX = 18000000 static
SUPER_LONG_TERM_MIN
float IuvoUnity.IuvoTime.TimeKeeper.SUPER_LONG_TERM_MIN = 36000.0f static
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Time/IuvoTime.cs