Iuvo Unity: IuvoUnity.Singletons.CoroutineManager Class Reference
IuvoUnity.Singletons.CoroutineManager Class Reference
Static Public Member Functions
static void RunCoroutine (IEnumerator coroutine)
static WaitForSeconds GetWaitForSeconds (float seconds)
Static Public Attributes
static Dictionary< WaitForSeconds, float > waitForDictionary = new Dictionary<WaitForSeconds, float>()
Protected Member Functions
override void Awake ()
Protected Member Functions inherited from IuvoUnity.Singletons.PersistentSingleton< T >
virtual void InitializeSingleton ()
Private Member Functions
void Start ()
Additional Inherited Members
Public Attributes inherited from IuvoUnity.Singletons.PersistentSingleton< T >
bool UnparentOnAwake = true
Static Protected Attributes inherited from IuvoUnity.Singletons.PersistentSingleton< T >
static T instance
Properties inherited from IuvoUnity.Singletons.PersistentSingleton< T >
static bool HasInstance [get]
static T Current [get]
static T Instance [get]
Member Function Documentation
Awake()
override void IuvoUnity.Singletons.CoroutineManager.Awake () protected virtual
Reimplemented from IuvoUnity.Singletons.PersistentSingleton< T >.
            {
                base.Awake();
            }
GetWaitForSeconds()
WaitForSeconds IuvoUnity.Singletons.CoroutineManager.GetWaitForSeconds (float seconds) static
            {
                foreach (var kvp in waitForDictionary)
                {
                    if (Mathf.Approximately(kvp.Value, seconds))
                    {
                        return kvp.Key;
                    }
                }
                WaitForSeconds waitFor = new WaitForSeconds(seconds);
                waitForDictionary.Add(waitFor, seconds);
                return waitFor;
            }
References waitForDictionary.
Referenced by IuvoUnity.Interfaces.IPausable.ResumeAfterDelay().
RunCoroutine()
void IuvoUnity.Singletons.CoroutineManager.RunCoroutine (IEnumerator coroutine) static
            {
                Instance.StartCoroutine(coroutine);
            }
References IuvoUnity.Singletons.PersistentSingleton< T >.Instance.
Referenced by IuvoUnity.Interfaces.IPausable.PauseFor().
Start()
void IuvoUnity.Singletons.CoroutineManager.Start () private
            {
            }
Member Data Documentation
waitForDictionary
Dictionary<WaitForSeconds, float> IuvoUnity.Singletons.CoroutineManager.waitForDictionary = new Dictionary<WaitForSeconds, float>() static
Referenced by GetWaitForSeconds().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Singletons/CoroutineManager.cs