Iuvo Unity: IuvoUnity.IuvoTime.TimerFactory Class Reference
IuvoUnity.IuvoTime.TimerFactory Class Reference
Public Member Functions
Timer Create (TimerConfiguration configuration)
Member Function Documentation
Create()
Timer IuvoUnity.IuvoTime.TimerFactory.Create (TimerConfiguration configuration)
            {
                // Implementation for creating a timer based on the configuration
                GameObject timerObject = new GameObject("Timer");
                Timer timer = timerObject.AddComponent<Timer>();
                if (configuration != null)
                {
                    configuration.Configure(timer);
                    timer.OnConfigure();
                }
                timer.OnCreate();
                return timer;
            }
References IuvoUnity.Configurations.TimerConfiguration.Configure(), IuvoUnity.DataStructs.Timer.OnConfigure(), and IuvoUnity.DataStructs.Timer.OnCreate().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Time/IuvoTime.cs