Iuvo Unity: IuvoUnity.DataStructs.Chain< T > Class Template Reference
IuvoUnity.DataStructs.Chain< T > Class Template Reference
Public Member Functions
void PushFront (Link< T > toAdd)
void PushBack (Link< T > toAdd)
void RebuildLinks ()
void Remove (Link< T > toRemove)
void RemoveAll ()
Link< T > FindClosest (System.Func< T, float > distanceFunc)
Chain< T > Clone ()
void Reverse ()
void MakeCircular ()
void InsertAt (Link< T > toAdd, Link< T > prev, Link< T > next)
void ValidateLinks ()
Static Public Member Functions
static List< Link< T > > GetForwardPath (Link< T > start, int max=100)
Public Attributes
List< Link< T > > Links = new List<Link<T>>()
Member Function Documentation
Clone()
Chain< T > IuvoUnity.DataStructs.Chain< T >.Clone ()
            {
                var newChain = new Chain<T>();
                foreach (var link in Links)
                {
                    newChain.PushBack(link.Clone());
                }
                newChain.RebuildLinks();
                return newChain;
            }
References Links.
FindClosest()
Link< T > IuvoUnity.DataStructs.Chain< T >.FindClosest (System.Func< T, float > distanceFunc)
            {
                Link<T> closest = null;
                float minDistance = float.MaxValue;
                foreach (var link in Links)
                {
                    float dist = distanceFunc(link.GetData());
                    if (dist < minDistance)
                    {
                        minDistance = dist;
                        closest = link;
                    }
                }
                return closest;
            }
References Links.
GetForwardPath()
List< Link< T > > IuvoUnity.DataStructs.Chain< T >.GetForwardPath (Link< T > start, int max = 100) static
            {
                var list = new List<Link<T>>();
                var current = start;
                int count = 0;
                while (current != null && count++ < max)
                {
                    list.Add(current);
                    current = current.TryGetNext();
                }
                return list;
            }
InsertAt()
void IuvoUnity.DataStructs.Chain< T >.InsertAt (Link< T > toAdd, Link< T > prev, Link< T > next)
            {
                if (toAdd == null) return;
                if (Links.Contains(toAdd)) return;
                if (prev != null && !Links.Contains(prev))
                {
                    IuvoDebug.DebugLogWarning("InsertAt: prev not in list");
                    return;
                }
                if (next != null && !Links.Contains(next))
                {
                    IuvoDebug.DebugLogWarning("InsertAt: next not in list");
                    return;
                }
                if (prev != null)
                    prev.SetNext(toAdd);
                if (next != null)
                    next.SetPrevious(toAdd);
                toAdd.SetPrevious(prev);
                toAdd.SetNext(next);
                int index = Links.IndexOf(prev);
                if (index >= 0)
                    Links.Insert(index + 1, toAdd);
                else
                    Links.Add(toAdd);
                RebuildLinks();
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), Links, RebuildLinks(), IuvoUnity.DataStructs.Link< T >.SetNext(), and IuvoUnity.DataStructs.Link< T >.SetPrevious().
MakeCircular()
void IuvoUnity.DataStructs.Chain< T >.MakeCircular ()
            {
                if (Links.Count < 2) return;
                var first = Links[0];
                var last = Links[Links.Count - 1];
                last.SetNext(first);
                first.SetPrevious(last);
            }
References Links.
PushBack()
void IuvoUnity.DataStructs.Chain< T >.PushBack (Link< T > toAdd)
            {
                if (Links.Contains(toAdd))
                    return;
                if (Links.Count == 0)
                {
                    Links.Add(toAdd);
                    return;
                }
                var last = Links[Links.Count - 1];
                last.SetNext(toAdd);
                toAdd.SetPrevious(last);
                toAdd.SetNext(null);
                Links.Add(toAdd);
            }
References Links, IuvoUnity.DataStructs.Link< T >.SetNext(), and IuvoUnity.DataStructs.Link< T >.SetPrevious().
PushFront()
void IuvoUnity.DataStructs.Chain< T >.PushFront (Link< T > toAdd)
            {
                if (Links.Contains(toAdd))
                    return;
                if (Links.Count == 0)
                {
                    Links.Add(toAdd);
                    return;
                }
                var first = Links[0];
                toAdd.SetNext(first);
                first.SetPrevious(toAdd);
                toAdd.SetPrevious(null);
                Links.Insert(0, toAdd);
            }
References Links, IuvoUnity.DataStructs.Link< T >.SetNext(), and IuvoUnity.DataStructs.Link< T >.SetPrevious().
RebuildLinks()
void IuvoUnity.DataStructs.Chain< T >.RebuildLinks ()
            {
                for (int i = 0; i < Links.Count; i++)
                {
                    var current = Links[i];
                    Link<T> next = i < Links.Count - 1 ? Links[i + 1] : null;
                    Link<T> prev = i > 0 ? Links[i - 1] : null;
                    current.SetNext(next);
                    current.SetPrevious(prev);
                }
            }
References Links.
Referenced by InsertAt(), and Reverse().
Remove()
void IuvoUnity.DataStructs.Chain< T >.Remove (Link< T > toRemove)
            {
                if (!Links.Contains(toRemove)) return;
                var prev = toRemove.TryGetPrevious();
                var next = toRemove.TryGetNext();
                if (prev != null) prev.SetNext(next);
                if (next != null) next.SetPrevious(prev);
                toRemove.SetNext(null);
                toRemove.SetPrevious(null);
                Links.Remove(toRemove);
            }
References Links, IuvoUnity.DataStructs.Link< T >.SetNext(), IuvoUnity.DataStructs.Link< T >.SetPrevious(), IuvoUnity.DataStructs.Link< T >.TryGetNext(), and IuvoUnity.DataStructs.Link< T >.TryGetPrevious().
RemoveAll()
void IuvoUnity.DataStructs.Chain< T >.RemoveAll ()
            {
                foreach (var link in Links)
                {
                    link.SetNext(null);
                    link.SetPrevious(null);
                }
                Links.Clear();
            }
References Links.
Reverse()
void IuvoUnity.DataStructs.Chain< T >.Reverse ()
            {
                Links.Reverse();
                RebuildLinks();
            }
References Links, and RebuildLinks().
ValidateLinks()
void IuvoUnity.DataStructs.Chain< T >.ValidateLinks ()
            {
                for (int i = 0; i < Links.Count; i++)
                {
                    var link = Links[i];
                    var next = link.TryGetNext();
                    if (next != null && next.TryGetPrevious() != link)
                    {
                        IuvoDebug.DebugLogWarning($"Next link mismatch at index {i}");
                    }
                    var prev = link.TryGetPrevious();
                    if (prev != null && prev.TryGetNext() != link)
                    {
                        IuvoDebug.DebugLogWarning($"Previous link mismatch at index {i}");
                    }
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), and Links.
Member Data Documentation
Links
List<Link<T> > IuvoUnity.DataStructs.Chain< T >.Links = new List<Link<T>>()
Referenced by Clone(), FindClosest(), InsertAt(), MakeCircular(), PushBack(), PushFront(), RebuildLinks(), Remove(), RemoveAll(), Reverse(), and ValidateLinks().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/Chain.cs