Iuvo Unity: IuvoUnity.BaseClasses.LevelComponent Class Reference
IuvoUnity.BaseClasses.LevelComponent Class Reference
Public Member Functions
bool IsMaxLevel ()
Checks if the current level is at or above the maximum level defined in the LevelConfiguration.
void AddExperience (int amount)
Experience only goes to CurrentExperience variable. TotalExperience only increases on level-up.
void LoseExperience (int amount)
void AddLevels (int toAdd)
Directly adds levels, bypassing experience checks. Use with caution.
void LoseLevels (int toLose)
Directly removes levels. Will not reduce below level 1. All experience for lost levels is retained, but can be lost again if experience is lost.
void AddLevelUpPoint (int amount)
void SpendLevelUpPoint ()
void ManualLevelUp ()
int GetExperienceToNextLevel ()
void SerializeSelf ()
virtual void OnDestroy ()
virtual void Start ()
void InitializeFromData (LevelComponentData data)
bool TryGetLevelConfig (out LevelConfiguration config)
virtual void OnConfigure ()
virtual void OnReconfigure ()
Public Attributes
FlexibleEvent< int > OnLevelUp = new FlexibleEvent<int>()
FlexibleEvent< int > OnLevelDown = new FlexibleEvent<int>()
FlexibleDynamicEvent OnExperienceChanged = new FlexibleDynamicEvent(new UnityEvent<int, int, int, int>())
params = currentExperience, experienceGained, experienceLost, experienceToNextLvl
Properties
int CurrentLevel [get, private set]
int LevelProgressExperience [get, private set]
int LifetimeExperience [get, private set]
int ExperienceUntilNextLevel [get, private set]
int NextLevelExperienceMinimum [get, private set]
int CurrentLevelUpPoints [get, private set]
int MaxLevelUpPoints [get, set]
bool AutoLeveling [get, set]
bool Configured [get, set]
bool Reconfigured [get, set]
Private Member Functions
int GetEffectiveExperience ()
Returns the total experience to consider for leveling calculations. Accounts for permanentExperience mode.
void CheckLevelUp (LevelConfiguration config)
Private Attributes
bool isMaxLevel = false
bool autoLeveling = true
bool permanentExperience = false
LevelConfiguration levelConfig
Member Function Documentation
AddExperience()
void IuvoUnity.BaseClasses.LevelComponent.AddExperience (int amount)
Experience only goes to CurrentExperience variable. TotalExperience only increases on level-up.
Parameters
amount
            {
                if (amount < 0)
                {
                    IuvoDebug.DebugLogWarning("Experience amount cannot be negative.");
                    return;
                }
                if (!TryGetLevelConfig(out LevelConfiguration config))
                {
                    IuvoDebug.DebugLogError("Failed to get LevelConfiguration. Cannot add experience.");
                    return;
                }
                if (permanentExperience)
                {
                    LifetimeExperience += amount;
                }
                else
                {
                    LevelProgressExperience += amount;
                }
                if (autoLeveling)
                {
                    CheckLevelUp(config);
                }
                int effectiveExp = GetEffectiveExperience();
                ExperienceUntilNextLevel = config.GetExperienceToNextLevel(CurrentLevel, effectiveExp);
                OnExperienceChanged.Invoke(LevelProgressExperience, amount, 0, ExperienceUntilNextLevel);
            }
References autoLeveling, CheckLevelUp(), CurrentLevel, IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), ExperienceUntilNextLevel, GetEffectiveExperience(), LevelProgressExperience, LifetimeExperience, OnExperienceChanged, permanentExperience, and TryGetLevelConfig().
AddLevels()
void IuvoUnity.BaseClasses.LevelComponent.AddLevels (int toAdd)
Directly adds levels, bypassing experience checks. Use with caution.
Parameters
toAdd
            {
                if (toAdd < 0)
                {
                    IuvoDebug.DebugLogWarning("Level amount to add cannot be negative.");
                    return;
                }
                if (!TryGetLevelConfig(out LevelConfiguration config))
                {
                    IuvoDebug.DebugLogError("Failed to get LevelConfiguration. Cannot add levels.");
                    return;
                }
                int targetLevel = Mathf.Min(CurrentLevel + toAdd, config.MaxLevel);
                if (targetLevel == CurrentLevel)
                {
                    IuvoDebug.DebugLogWarning("Already at maximum level. Cannot add more levels.");
                    return;
                }
                for (int i = CurrentLevel; i < targetLevel; i++)
                {
                    CurrentLevel++;
                    AddLevelUpPoint(1);
                    OnLevelUp.Invoke(CurrentLevel);
                }
                // Update experience values based on new level
                int newLevelExp = config.GetExpAtLevel(CurrentLevel);
                LifetimeExperience = newLevelExp;
                LevelProgressExperience = 0;
                isMaxLevel = (CurrentLevel >= config.MaxLevel);
                ExperienceUntilNextLevel = isMaxLevel ? 0 : config.GetExperienceToNextLevel(CurrentLevel, GetEffectiveExperience());
                NextLevelExperienceMinimum = isMaxLevel ? newLevelExp : config.GetExpAtLevel(CurrentLevel + 1);
                OnExperienceChanged.Invoke(LevelProgressExperience, 0, 0, ExperienceUntilNextLevel);
            }
References AddLevelUpPoint(), CurrentLevel, IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), ExperienceUntilNextLevel, GetEffectiveExperience(), isMaxLevel, LevelProgressExperience, LifetimeExperience, NextLevelExperienceMinimum, OnExperienceChanged, OnLevelUp, and TryGetLevelConfig().
AddLevelUpPoint()
void IuvoUnity.BaseClasses.LevelComponent.AddLevelUpPoint (int amount)
            {
                if (amount < 0)
                {
                    IuvoDebug.DebugLogWarning("Level-up point amount cannot be negative.");
                    return;
                }
                if (CurrentLevelUpPoints + amount > MaxLevelUpPoints)
                {
                    IuvoDebug.DebugLogWarning("Cannot exceed maximum level-up points.");
                }
                CurrentLevelUpPoints = Mathf.Min(CurrentLevelUpPoints + amount, MaxLevelUpPoints);
            }
References CurrentLevelUpPoints, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), and MaxLevelUpPoints.
Referenced by AddLevels(), and CheckLevelUp().
CheckLevelUp()
void IuvoUnity.BaseClasses.LevelComponent.CheckLevelUp (LevelConfiguration config) private
            {
                if (config == null) return;
                bool leveledUp = false;
                int effectiveExp = GetEffectiveExperience();
                while (CurrentLevel < config.MaxLevel)
                {
                    int nextLevelExp = config.GetExpAtLevel(CurrentLevel + 1);
                    if (effectiveExp >= nextLevelExp)
                    {
                        leveledUp = true;
                        CurrentLevel++;
                        int leftover = effectiveExp - nextLevelExp;
                        if (!permanentExperience)
{
                            LifetimeExperience = nextLevelExp; // Update lifetime only on level-up
                            LevelProgressExperience = leftover;
                        }
                        else
{
                            LevelProgressExperience = 0; // reset current progress if permanent
                        }
                        AddLevelUpPoint(1);
                        OnLevelUp.Invoke(CurrentLevel);
                        // Update effectiveExp for next iteration
                        effectiveExp = GetEffectiveExperience();
                    }
                    else
                    {
                        break; // Not enough EXP for next level
                    }
                }
                // Update max level flag
                isMaxLevel = (CurrentLevel >= config.MaxLevel);
                // Calculate remaining EXP to next level
                if (!isMaxLevel)
                {
                    int nextLevelExp = config.GetExpAtLevel(CurrentLevel + 1);
                    ExperienceUntilNextLevel = nextLevelExp - effectiveExp;
                    NextLevelExperienceMinimum = nextLevelExp;
                }
                else
                {
                    ExperienceUntilNextLevel = 0;
                    NextLevelExperienceMinimum = config.GetExpAtLevel(config.MaxLevel); // Optional: cap at max level
                    LevelProgressExperience = 0; // optional: reset excess EXP
                }
                if (leveledUp)
                {
                    OnExperienceChanged.Invoke(LevelProgressExperience, 0, 0, ExperienceUntilNextLevel);
                }
            }
References AddLevelUpPoint(), CurrentLevel, ExperienceUntilNextLevel, GetEffectiveExperience(), IuvoUnity.Configurations.LevelConfiguration.GetExpAtLevel(), isMaxLevel, LevelProgressExperience, LifetimeExperience, IuvoUnity.Configurations.LevelConfiguration.MaxLevel, NextLevelExperienceMinimum, OnExperienceChanged, OnLevelUp, and permanentExperience.
Referenced by AddExperience(), and ManualLevelUp().
GetEffectiveExperience()
int IuvoUnity.BaseClasses.LevelComponent.GetEffectiveExperience () private
Returns the total experience to consider for leveling calculations. Accounts for permanentExperience mode.
            {
                return permanentExperience ? LifetimeExperience : LevelProgressExperience + LifetimeExperience;
            }
References LevelProgressExperience, LifetimeExperience, and permanentExperience.
Referenced by AddExperience(), AddLevels(), CheckLevelUp(), GetExperienceToNextLevel(), and LoseLevels().
GetExperienceToNextLevel()
int IuvoUnity.BaseClasses.LevelComponent.GetExperienceToNextLevel ()
            {
                if (levelConfig != null)
                {
                    return levelConfig.GetExperienceToNextLevel(CurrentLevel, GetEffectiveExperience());
                }
                else
                {
                    IuvoDebug.DebugLogError("LevelConfiguration is not set. Cannot get experience to next level.");
                    return 0;
                }
            }
References CurrentLevel, IuvoUnity.Debug.IuvoDebug.DebugLogError(), GetEffectiveExperience(), and levelConfig.
InitializeFromData()
void IuvoUnity.BaseClasses.LevelComponent.InitializeFromData (LevelComponentData data)
            {
                CurrentLevel = data.CurrentLevel;
                LevelProgressExperience = data.LevelProgressExperience;
                LifetimeExperience = data.LifetimeExperience;
                ExperienceUntilNextLevel = data.ExperienceUntilNextLevel;
                NextLevelExperienceMinimum = data.NextLevelExperienceMinimum;
                CurrentLevelUpPoints = data.CurrentLevelUpPoints;
                MaxLevelUpPoints = data.MaxLevelUpPoints;
            }
References CurrentLevel, IuvoUnity.BaseClasses.LevelComponentData.CurrentLevel, CurrentLevelUpPoints, IuvoUnity.BaseClasses.LevelComponentData.CurrentLevelUpPoints, ExperienceUntilNextLevel, IuvoUnity.BaseClasses.LevelComponentData.ExperienceUntilNextLevel, LevelProgressExperience, IuvoUnity.BaseClasses.LevelComponentData.LevelProgressExperience, LifetimeExperience, IuvoUnity.BaseClasses.LevelComponentData.LifetimeExperience, MaxLevelUpPoints, IuvoUnity.BaseClasses.LevelComponentData.MaxLevelUpPoints, NextLevelExperienceMinimum, and IuvoUnity.BaseClasses.LevelComponentData.NextLevelExperienceMinimum.
Referenced by Start().
IsMaxLevel()
bool IuvoUnity.BaseClasses.LevelComponent.IsMaxLevel ()
Checks if the current level is at or above the maximum level defined in the LevelConfiguration.
Returns
            {
                if (TryGetLevelConfig(out LevelConfiguration config))
                {
                    isMaxLevel = (CurrentLevel >= config.MaxLevel);
                    return isMaxLevel;
                }
                isMaxLevel = false;
                return isMaxLevel;
            }
References CurrentLevel, isMaxLevel, and TryGetLevelConfig().
LoseExperience()
void IuvoUnity.BaseClasses.LevelComponent.LoseExperience (int amount)
            {
                if (permanentExperience)
                {
                    IuvoDebug.DebugLogWarning("Cannot lose experience when permanentExperience is enabled.");
                    return;
                }
                if (amount < 0)
                {
                    IuvoDebug.DebugLogWarning("Experience amount cannot be negative.");
                    return;
                }
                LevelProgressExperience = Mathf.Max(0, LevelProgressExperience - amount);
                if (TryGetLevelConfig(out LevelConfiguration config))
                {
                    ExperienceUntilNextLevel = config.GetExperienceToNextLevel(CurrentLevel, LifetimeExperience);
                }
                OnExperienceChanged.Invoke(LevelProgressExperience, 0, amount, ExperienceUntilNextLevel);
            }
References CurrentLevel, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), ExperienceUntilNextLevel, LevelProgressExperience, LifetimeExperience, OnExperienceChanged, permanentExperience, and TryGetLevelConfig().
LoseLevels()
void IuvoUnity.BaseClasses.LevelComponent.LoseLevels (int toLose)
Directly removes levels. Will not reduce below level 1. All experience for lost levels is retained, but can be lost again if experience is lost.
Parameters
toLose
            {
                if (toLose < 0)
                {
                    IuvoDebug.DebugLogWarning("Level amount to lose cannot be negative.");
                    return;
                }
                if (!TryGetLevelConfig(out LevelConfiguration config))
                {
                    IuvoDebug.DebugLogError("Failed to get LevelConfiguration. Cannot lose levels.");
                    return;
                }
                int targetLevel = Mathf.Max(CurrentLevel - toLose, 1);
                if (targetLevel == CurrentLevel)
                {
                    IuvoDebug.DebugLogWarning("Already at minimum level. Cannot lose more levels.");
                    return;
                }
                for (int i = CurrentLevel; i > targetLevel; i--)
                {
                    CurrentLevel--;
                    if (CurrentLevelUpPoints > 0)
                    {
                        CurrentLevelUpPoints--;
                    }
                    OnLevelDown.Invoke(CurrentLevel);
                }
                // Update experience values based on new level
                int newLevelExp = config.GetExpAtLevel(CurrentLevel);
                LifetimeExperience = newLevelExp;
                LevelProgressExperience = 0;
                isMaxLevel = (CurrentLevel >= config.MaxLevel);
                ExperienceUntilNextLevel = isMaxLevel ? 0 : config.GetExperienceToNextLevel(CurrentLevel, GetEffectiveExperience());
                NextLevelExperienceMinimum = isMaxLevel ? newLevelExp : config.GetExpAtLevel(CurrentLevel + 1);
                OnExperienceChanged.Invoke(LevelProgressExperience, 0, 0, ExperienceUntilNextLevel);
            }
References CurrentLevel, CurrentLevelUpPoints, IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), ExperienceUntilNextLevel, GetEffectiveExperience(), isMaxLevel, LevelProgressExperience, LifetimeExperience, NextLevelExperienceMinimum, OnExperienceChanged, OnLevelDown, and TryGetLevelConfig().
ManualLevelUp()
void IuvoUnity.BaseClasses.LevelComponent.ManualLevelUp ()
            {
                if (TryGetLevelConfig(out LevelConfiguration config))
                {
                    CheckLevelUp(config);
                }
            }
References CheckLevelUp(), and TryGetLevelConfig().
OnConfigure()
virtual void IuvoUnity.BaseClasses.LevelComponent.OnConfigure () virtual
Implements IuvoUnity.Interfaces.IConfigurable.
            {
            }
OnDestroy()
virtual void IuvoUnity.BaseClasses.LevelComponent.OnDestroy () virtual
            {
                try
                {
                    SerializeSelf();
                }
                catch (System.Exception ex)
                {
                    IuvoDebug.DebugLogError($"Failed to serialize LevelComponent on destroy: {ex.Message}");
                }
                finally
                {
                    OnLevelUp.RemoveAllFlexibleEventListeners();
                    OnExperienceChanged.RemoveAllFlexibleEventListeners();
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), OnExperienceChanged, OnLevelUp, and SerializeSelf().
OnReconfigure()
virtual void IuvoUnity.BaseClasses.LevelComponent.OnReconfigure () virtual
Implements IuvoUnity.Interfaces.IReconfigurable.
            {
            }
SerializeSelf()
void IuvoUnity.BaseClasses.LevelComponent.SerializeSelf ()
            {
                if (levelConfig == null)
                {
                    IuvoDebug.DebugLogError("LevelConfiguration is not set. Cannot serialize LevelComponent.");
                    return;
                }
                LevelComponentData data = new LevelComponentData
                {
                    CurrentLevel = CurrentLevel,
                    LevelProgressExperience = LevelProgressExperience,
                    LifetimeExperience = LifetimeExperience,
                    ExperienceUntilNextLevel = ExperienceUntilNextLevel,
                    NextLevelExperienceMinimum = NextLevelExperienceMinimum,
                    CurrentLevelUpPoints = CurrentLevelUpPoints,
                    MaxLevelUpPoints = MaxLevelUpPoints,
                    isMaxLevel = isMaxLevel
                };
                levelConfig.Serialize(data);
            }
References CurrentLevel, CurrentLevelUpPoints, IuvoUnity.Debug.IuvoDebug.DebugLogError(), ExperienceUntilNextLevel, isMaxLevel, levelConfig, LevelProgressExperience, LifetimeExperience, MaxLevelUpPoints, and NextLevelExperienceMinimum.
Referenced by OnDestroy().
SpendLevelUpPoint()
void IuvoUnity.BaseClasses.LevelComponent.SpendLevelUpPoint ()
            {
                if (CurrentLevelUpPoints <= 0)
                {
                    IuvoDebug.DebugLogWarning("No level-up points available to spend.");
                    return;
                }
                CurrentLevelUpPoints--;
            }
References CurrentLevelUpPoints, and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
Start()
virtual void IuvoUnity.BaseClasses.LevelComponent.Start () virtual
            {
                if (!TryGetLevelConfig(out LevelConfiguration config))
                {
                    IuvoDebug.DebugLogError("LevelConfiguration missing at Start(). Using defaults.");
                    CurrentLevel = 1;
                    LevelProgressExperience = 0;
                    LifetimeExperience = 0;
                    ExperienceUntilNextLevel = 1;
                    MaxLevelUpPoints = 5;
                    return;
                }
                var data = config.DeserializeLevelComponent();
                if (data.HasValue && data.Value.IsValid())
                {
                    InitializeFromData(data.Value);
                }
            }
References CurrentLevel, IuvoUnity.Debug.IuvoDebug.DebugLogError(), ExperienceUntilNextLevel, InitializeFromData(), LevelProgressExperience, LifetimeExperience, MaxLevelUpPoints, and TryGetLevelConfig().
TryGetLevelConfig()
bool IuvoUnity.BaseClasses.LevelComponent.TryGetLevelConfig (out LevelConfiguration config)
            {
                if (levelConfig)
                {
                    config = levelConfig;
                    return true;
                }
                IuvoDebug.DebugLogError("ERROR: LevelConfiguration is not set. Returning default runtime instance.");
                config = null;
                return false;
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), and levelConfig.
Referenced by AddExperience(), AddLevels(), IsMaxLevel(), LoseExperience(), LoseLevels(), ManualLevelUp(), and Start().
Member Data Documentation
autoLeveling
bool IuvoUnity.BaseClasses.LevelComponent.autoLeveling = true private
Referenced by AddExperience().
isMaxLevel
bool IuvoUnity.BaseClasses.LevelComponent.isMaxLevel = false private
Referenced by AddLevels(), CheckLevelUp(), IsMaxLevel(), LoseLevels(), and SerializeSelf().
levelConfig
LevelConfiguration IuvoUnity.BaseClasses.LevelComponent.levelConfig private
Referenced by GetExperienceToNextLevel(), SerializeSelf(), and TryGetLevelConfig().
OnExperienceChanged
FlexibleDynamicEvent IuvoUnity.BaseClasses.LevelComponent.OnExperienceChanged = new FlexibleDynamicEvent(new UnityEvent<int, int, int, int>())
params = currentExperience, experienceGained, experienceLost, experienceToNextLvl
Referenced by AddExperience(), AddLevels(), CheckLevelUp(), LoseExperience(), LoseLevels(), and OnDestroy().
OnLevelDown
FlexibleEvent<int> IuvoUnity.BaseClasses.LevelComponent.OnLevelDown = new FlexibleEvent<int>()
Referenced by LoseLevels().
OnLevelUp
FlexibleEvent<int> IuvoUnity.BaseClasses.LevelComponent.OnLevelUp = new FlexibleEvent<int>()
Referenced by AddLevels(), CheckLevelUp(), and OnDestroy().
permanentExperience
bool IuvoUnity.BaseClasses.LevelComponent.permanentExperience = false private
Referenced by AddExperience(), CheckLevelUp(), GetEffectiveExperience(), and LoseExperience().
Property Documentation
AutoLeveling
bool IuvoUnity.BaseClasses.LevelComponent.AutoLeveling get set
            {
                get => autoLeveling;
                set => autoLeveling = value;
            }
Configured
bool IuvoUnity.BaseClasses.LevelComponent.Configured get set
Implements IuvoUnity.Interfaces.IConfigurable.
{ get; set; }
CurrentLevel
int IuvoUnity.BaseClasses.LevelComponent.CurrentLevel get private set
{ get; private set; }      // The current level of the entity
Referenced by AddExperience(), AddLevels(), CheckLevelUp(), GetExperienceToNextLevel(), InitializeFromData(), IsMaxLevel(), LoseExperience(), LoseLevels(), SerializeSelf(), and Start().
CurrentLevelUpPoints
int IuvoUnity.BaseClasses.LevelComponent.CurrentLevelUpPoints get private set
{ get; private set; }       // points available to spend on upgrades
Referenced by AddLevelUpPoint(), InitializeFromData(), LoseLevels(), SerializeSelf(), and SpendLevelUpPoint().
ExperienceUntilNextLevel
int IuvoUnity.BaseClasses.LevelComponent.ExperienceUntilNextLevel get private set
{ get; private set; }       // EXP needed to reach next level
Referenced by AddExperience(), AddLevels(), CheckLevelUp(), InitializeFromData(), LoseExperience(), LoseLevels(), SerializeSelf(), and Start().
LevelProgressExperience
int IuvoUnity.BaseClasses.LevelComponent.LevelProgressExperience get private set
{ get; private set; }       // help EXP towards next level
Referenced by AddExperience(), AddLevels(), CheckLevelUp(), GetEffectiveExperience(), InitializeFromData(), LoseExperience(), LoseLevels(), SerializeSelf(), and Start().
LifetimeExperience
int IuvoUnity.BaseClasses.LevelComponent.LifetimeExperience get private set
{ get; private set; }       // all EXP ever gained. permanent on level up, cannot decrease
Referenced by AddExperience(), AddLevels(), CheckLevelUp(), GetEffectiveExperience(), InitializeFromData(), LoseExperience(), LoseLevels(), SerializeSelf(), and Start().
MaxLevelUpPoints
int IuvoUnity.BaseClasses.LevelComponent.MaxLevelUpPoints get set private
{ get; set; }            // maximum points that can be accumulated
Referenced by AddLevelUpPoint(), InitializeFromData(), SerializeSelf(), and Start().
NextLevelExperienceMinimum
int IuvoUnity.BaseClasses.LevelComponent.NextLevelExperienceMinimum get private set
{ get; private set; }         // minimum EXP required for next level
Referenced by AddLevels(), CheckLevelUp(), InitializeFromData(), LoseLevels(), and SerializeSelf().
Reconfigured
bool IuvoUnity.BaseClasses.LevelComponent.Reconfigured get set
Implements IuvoUnity.Interfaces.IReconfigurable.
{ get; set; }
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/RPG/Progression/LevelComponent.cs