Iuvo Unity: IuvoUnity.Statemachines.HSM.Grounded Class Reference
IuvoUnity.Statemachines.HSM.Grounded Class Reference
Public Member Functions
Grounded (StateMachine m, State parent, PlayerContext context)
Public Member Functions inherited from IuvoUnity.StateMachines.HSM.State
State (StateMachine machine, State parent=null)
State Leaf ()
IEnumerable< State > PathToRoot ()
Public Attributes
PlayerContext ctx
readonly Idle Idle
readonly Move Move
Public Attributes inherited from IuvoUnity.StateMachines.HSM.State
readonly StateMachine Machine
State Parent
State ActiveChild
Protected Member Functions
override State GetInitialState ()
override State GetTransition ()
Protected Member Functions inherited from IuvoUnity.StateMachines.HSM.State
virtual void OnEnter ()
virtual void OnExit ()
virtual void OnUpdate (float deltaTime)
Constructor & Destructor Documentation
Grounded()
IuvoUnity.Statemachines.HSM.Grounded.Grounded (StateMachine m, State parent, PlayerContext context)
                                                                                     : base(m, parent)
                {
                    Idle = new Idle(m, this, context);
                    Move = new Move(m, this, context);
                    ctx = context;
                }
References ctx, Idle, Move, and IuvoUnity.StateMachines.HSM.State.State().
Member Function Documentation
GetInitialState()
override State IuvoUnity.Statemachines.HSM.Grounded.GetInitialState () protected virtual
Reimplemented from IuvoUnity.StateMachines.HSM.State.
=> Idle;
References Idle, and IuvoUnity.StateMachines.HSM.State.State().
GetTransition()
override State IuvoUnity.Statemachines.HSM.Grounded.GetTransition () protected virtual
Reimplemented from IuvoUnity.StateMachines.HSM.State.
                {
                    return ctx.playerCondition.GetIsGrounded() ? null : ((PlayerRoot)Parent).Airborne;
                }
References ctx, IuvoUnity.StateMachines.HSM.State.Parent, and IuvoUnity.StateMachines.HSM.State.State().
Member Data Documentation
ctx
PlayerContext IuvoUnity.Statemachines.HSM.Grounded.ctx
Referenced by GetTransition(), and Grounded().
Idle
readonly Idle IuvoUnity.Statemachines.HSM.Grounded.Idle
Referenced by GetInitialState(), and Grounded().
Move
readonly Move IuvoUnity.Statemachines.HSM.Grounded.Move
Referenced by Grounded().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/StateMachine/HierarchicalStateMachine/States.cs