Iuvo Unity: IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager Class Reference
IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager Class Reference
Public Member Functions
void Update ()
void GenerateGridDungeon ()
Public Attributes
bool isRandom = true
bool isFinishedMakingRooms = false
bool isFinishedRemovingWalls = false
bool isFinishedCheckingPaths = false
bool isFinishedAdjustingRooms = false
bool isFinished = false
int randMinWorldWidth = 25
int randMaxWorldWidth = 100
int randMinWorldLength = 20
int randMaxWorldLength = 100
int randMinWorldHeight = 1
int randMaxWorldHeight = 3
int randMaxNumOfRooms = 25
int randMinRoomWidth = 5
int randMaxRoomWidth = 15
int randMinRoomHeight = 5
int randMaxRoomHeight = 15
int randMinRoomLength = 5
int randMaxRoomLength = 15
int randMinNumberOfRooms = 3
int randMaxNumberOfRooms = 10
int WorldWidth = 100
int WorldHeight = 5
int WorldLength = 100
int NumOfRooms = 0
int RoomWidth = 15
int RoomHeight = 15
int RoomLength = 15
float distanceFactor = 0.5f
GameObject roomFloorPrefab
GameObject corridorPrefab
List< Room > rooms = new List<Room>()
List< Corridor > corridors = new List<Corridor>()
Properties
static DungeonManager Instance [get, private set]
Private Member Functions
void Awake ()
void GenerateGridRoom (Vector3 worldSize, int width, int height, int length)
void GenerateGridOfRooms ()
Private Attributes
Vector3 currentWorldSize = Vector3.zero
Member Function Documentation
Awake()
void IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.Awake () private
                {
                    if (Instance == null)
                    {
                        Instance = this;
                    }
                    else
                    {
                        Destroy(gameObject);
                    }
                    NumOfRooms = WorldWidth * WorldLength;
                }
References Instance, NumOfRooms, WorldLength, and WorldWidth.
GenerateGridDungeon()
void IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.GenerateGridDungeon ()
                {
                    GenerateGridOfRooms();
                }
References GenerateGridOfRooms().
Referenced by Update().
GenerateGridOfRooms()
void IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.GenerateGridOfRooms () private
                {
                    currentWorldSize = transform.position;
                    for (int h = 0; h < WorldHeight; h++)
                    {
                        for (int i = 0; i < WorldWidth; i++)
{
                            for (int j = 0; j < WorldLength; j++)
{
                                GenerateGridRoom(currentWorldSize, RoomWidth, RoomHeight, RoomLength);
                                currentWorldSize = currentWorldSize.Add(z: 1 * distanceFactor);
                            }
                            currentWorldSize = currentWorldSize.WithZ(transform.position.z);
                            currentWorldSize = currentWorldSize.Add(x: 1 * distanceFactor);
                        }
                        currentWorldSize = currentWorldSize.WithX(transform.position.x);
                        currentWorldSize = currentWorldSize.Add(y: 1 * distanceFactor);
                    }
                    foreach (Room room in rooms)
                    {
                        if (room.roomFloor != null)
                            room.roomFloor.transform.position.Add(y: RoomHeight / 2);
                    }
                }
References currentWorldSize, distanceFactor, GenerateGridRoom(), IuvoUnity.ProceduralGeneration.Room.roomFloor, RoomHeight, RoomLength, rooms, RoomWidth, WorldHeight, WorldLength, and WorldWidth.
Referenced by GenerateGridDungeon().
GenerateGridRoom()
void IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.GenerateGridRoom (Vector3 worldSize, int width, int height, int length) private
                {
                    Room room = new Room(worldSize, width, height, length, DungeonManager.Instance.roomFloorPrefab);
                    if (room != null)
                    {
                        rooms.Add(room);
                    }
                }
References Instance, roomFloorPrefab, and rooms.
Referenced by GenerateGridOfRooms().
Update()
void IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.Update ()
                {
                    if (!isFinished)
                    {
                        if (isRandom)
{
                            if (rooms.Count >= randMaxNumOfRooms)
{
                                isFinished = true;
                                return;
                            }
                            //GenerateRandomDungeon();
                        }
                        else
{
                            if (rooms.Count >= NumOfRooms)
{
                                isFinished = true;
                                return;
                            }
                            GenerateGridDungeon();
                        }
                    }
                    else
                    {
                        //
                    }
                }
References GenerateGridDungeon(), isFinished, isRandom, NumOfRooms, randMaxNumOfRooms, and rooms.
Member Data Documentation
corridorPrefab
GameObject IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.corridorPrefab
corridors
List<Corridor> IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.corridors = new List<Corridor>()
currentWorldSize
Vector3 IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.currentWorldSize = Vector3.zero private
Referenced by GenerateGridOfRooms().
distanceFactor
float IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.distanceFactor = 0.5f
Referenced by GenerateGridOfRooms().
isFinished
bool IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.isFinished = false
Referenced by Update().
isFinishedAdjustingRooms
bool IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.isFinishedAdjustingRooms = false
isFinishedCheckingPaths
bool IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.isFinishedCheckingPaths = false
isFinishedMakingRooms
bool IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.isFinishedMakingRooms = false
isFinishedRemovingWalls
bool IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.isFinishedRemovingWalls = false
isRandom
bool IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.isRandom = true
Referenced by Update().
NumOfRooms
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.NumOfRooms = 0
Referenced by Awake(), and Update().
randMaxNumberOfRooms
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMaxNumberOfRooms = 10
randMaxNumOfRooms
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMaxNumOfRooms = 25
Referenced by Update().
randMaxRoomHeight
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMaxRoomHeight = 15
randMaxRoomLength
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMaxRoomLength = 15
randMaxRoomWidth
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMaxRoomWidth = 15
randMaxWorldHeight
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMaxWorldHeight = 3
randMaxWorldLength
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMaxWorldLength = 100
randMaxWorldWidth
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMaxWorldWidth = 100
randMinNumberOfRooms
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMinNumberOfRooms = 3
randMinRoomHeight
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMinRoomHeight = 5
randMinRoomLength
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMinRoomLength = 5
randMinRoomWidth
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMinRoomWidth = 5
randMinWorldHeight
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMinWorldHeight = 1
randMinWorldLength
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMinWorldLength = 20
randMinWorldWidth
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.randMinWorldWidth = 25
roomFloorPrefab
GameObject IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.roomFloorPrefab
Referenced by GenerateGridRoom().
RoomHeight
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.RoomHeight = 15
Referenced by GenerateGridOfRooms().
RoomLength
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.RoomLength = 15
Referenced by GenerateGridOfRooms().
rooms
List<Room> IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.rooms = new List<Room>()
Referenced by GenerateGridOfRooms(), GenerateGridRoom(), and Update().
RoomWidth
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.RoomWidth = 15
Referenced by GenerateGridOfRooms().
WorldHeight
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.WorldHeight = 5
Referenced by GenerateGridOfRooms().
WorldLength
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.WorldLength = 100
Referenced by Awake(), and GenerateGridOfRooms().
WorldWidth
int IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.WorldWidth = 100
Referenced by Awake(), and GenerateGridOfRooms().
Property Documentation
Instance
DungeonManager IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.Instance static get private set
{ get; private set; } // Singleton instance
Referenced by Awake(), and GenerateGridRoom().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ProceduralGenerationBases/Dungeons/DungeonManager.cs