Iuvo Unity: IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType > Class Template Reference
IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType > Class Template Reference
Public Member Functions
WeaponCategory (T_SubType subType)
override string ToString ()
Static Public Member Functions
static WeaponMainType GetMainTypeForSubType (Type enumType)
static bool IsValidSubType< TSubType > (WeaponMainType mainType, TSubType subType)
static Enum GetDefaultSubType (WeaponMainType mainType)
Properties
WeaponMainType _mainType [get]
T_SubType _subType [get]
Static Private Attributes
static readonly Dictionary< Type, WeaponMainType > subTypeToMainMap
Member Function Documentation
GetDefaultSubType()
Enum IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType >.GetDefaultSubType (WeaponMainType mainType) static
                    {
                        return mainType switch
{
                            WeaponMainType.SWORD => SwordType.SHORT_SWORD,
                            WeaponMainType.AXE => AxeType.HATCHET,
                            WeaponMainType.HAMMER => HammerType.CLUB,
                            WeaponMainType.POLEARM => PoleArmType.SPEAR,
                            WeaponMainType.RANGED => RangedType.ARROW,
                            WeaponMainType.THROWABLE => ThrowableType.ROCK,
                            WeaponMainType.HYBRID => HybridType.OTHER, // Optional
                            _ => throw new ArgumentOutOfRangeException(nameof(mainType), $"No default for {mainType}")
                        };
                    }
References IuvoUnity.BaseClasses.Items.Weapons.AXE, IuvoUnity.BaseClasses.Items.Weapons.HAMMER, IuvoUnity.BaseClasses.Items.Weapons.HYBRID, IuvoUnity.BaseClasses.Items.Weapons.POLEARM, IuvoUnity.BaseClasses.Items.Weapons.RANGED, IuvoUnity.BaseClasses.Items.Weapons.SWORD, and IuvoUnity.BaseClasses.Items.Weapons.THROWABLE.
Referenced by WeaponCategory().
GetMainTypeForSubType()
WeaponMainType IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType >.GetMainTypeForSubType (Type enumType) static
                    {
                        if (subTypeToMainMap.TryGetValue(enumType, out var mainType))
{
                            return mainType;
                        }
                        throw new ArgumentException($"Unknown weapon subtype enum: {enumType.Name}");
                    }
References subTypeToMainMap.
Referenced by IsValidSubType< TSubType >(), and WeaponCategory().
IsValidSubType< TSubType >()
bool IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType >.IsValidSubType< TSubType > (WeaponMainType mainType, TSubType subType) static
Type Constraints
TSubType : Enum
                                                                                                                          : Enum
                    {
                        return GetMainTypeForSubType(typeof(TSubType)) == mainType;
                    }
References GetMainTypeForSubType().
ToString()
override string IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType >.ToString ()
                    {
                        return $"{_mainType} : {_subType}";
                    }
WeaponCategory()
IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType >.WeaponCategory (T_SubType subType)
                    {
                        _mainType = GetMainTypeForSubType(typeof(T_SubType));
                        _subType = IsValidSubType(_mainType, subType)
                            ? subType
                            : (T_SubType)GetDefaultSubType(_mainType);
                    }
References _mainType, _subType, GetDefaultSubType(), and GetMainTypeForSubType().
Member Data Documentation
subTypeToMainMap
readonly Dictionary<Type, WeaponMainType> IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType >.subTypeToMainMap static private
Initial value:
                                                    = new Dictionary<Type, WeaponMainType>()
{
    { typeof(SwordType), WeaponMainType.SWORD },
    { typeof(AxeType), WeaponMainType.AXE },
    { typeof(HammerType), WeaponMainType.HAMMER },
    { typeof(PoleArmType), WeaponMainType.POLEARM },
    { typeof(RangedType), WeaponMainType.RANGED },
    { typeof(ThrowableType), WeaponMainType.THROWABLE }
}
                    {
                        { typeof(SwordType), WeaponMainType.SWORD },
                        { typeof(AxeType), WeaponMainType.AXE },
                        { typeof(HammerType), WeaponMainType.HAMMER },
                        { typeof(PoleArmType), WeaponMainType.POLEARM },
                        { typeof(RangedType), WeaponMainType.RANGED },
                        { typeof(ThrowableType), WeaponMainType.THROWABLE }
                    };
Referenced by GetMainTypeForSubType().
Property Documentation
_mainType
WeaponMainType IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType >._mainType get
{ get; }
Referenced by WeaponCategory().
_subType
T_SubType IuvoUnity.BaseClasses.Items.Weapons.WeaponCategory< T_SubType >._subType get
{ get; }
Referenced by WeaponCategory().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/RPG/Items/Weapons/MeleeWeapons/Weapon.cs