Iuvo Unity: IuvoUnity.Inputs.BaseInputActionLegacy Class Reference
IuvoUnity.Inputs.BaseInputActionLegacy Class Reference abstract
Public Member Functions
void HandleInput ()
Public Attributes
UnityEvent OnPerformedUnity
Action OnPerformed
Protected Member Functions
void Perform ()
virtual void Update ()
Member Function Documentation
HandleInput()
void IuvoUnity.Inputs.BaseInputActionLegacy.HandleInput () abstract
Referenced by Update().
Perform()
void IuvoUnity.Inputs.BaseInputActionLegacy.Perform () protected
            {
                IuvoDebug.DebugLog($"{name}: Performed!");
                OnPerformedUnity?.Invoke();
                OnPerformed?.Invoke();
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), OnPerformed, and OnPerformedUnity.
Referenced by IuvoUnity.Inputs.CompositeInputActionBase.HandleInput(), IuvoUnity.Inputs.HoldInputActionBase.HandleInput(), and IuvoUnity.Inputs.TapInputActionBase.HandleInput().
Update()
virtual void IuvoUnity.Inputs.BaseInputActionLegacy.Update () protected virtual
            {
                HandleInput();
            }
References HandleInput().
Member Data Documentation
OnPerformed
Action IuvoUnity.Inputs.BaseInputActionLegacy.OnPerformed
Referenced by Perform().
OnPerformedUnity
UnityEvent IuvoUnity.Inputs.BaseInputActionLegacy.OnPerformedUnity
Referenced by Perform().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Input/InputBaseLegacy.cs