Iuvo Unity: IuvoUnity.DataStructs.Context Class Reference
IuvoUnity.DataStructs.Context Class Reference
Public Member Functions
Context ()
Context (ref ConcurrentDictionary< Enum, object > contextDictionary)
Context (ref ConcurrentDictionary< Enum, object > contextDictionary, ref ConcurrentDictionary< Enum, object > eventDictionary)
void Set< T > (Enum key, T value)
T Get< T > (Enum key)
bool TryGet< T > (Enum key, out T value)
bool Has (Enum key)
bool Remove (Enum key)
void ClearData ()
Context CloneContext ()
void MergeContexts (Context other, bool overwrite=true)
void RegisterEvent (Enum key, FlexibleEvent evt)
void RegisterEvent< T > (Enum key, FlexibleEvent< T > evt)
bool TryGetEvent (Enum key, out FlexibleEvent evt)
bool TryGetEvent< T > (Enum key, out FlexibleEvent< T > evt)
void InvokeEvent (Enum key)
void InvokeEvent< T > (Enum key, T value)
bool HasEvent (Enum key)
bool RemoveEvent (Enum key)
void ClearEvents ()
void Dispose ()
Private Attributes
ConcurrentDictionary< Enum, object > _data = new ConcurrentDictionary<Enum, object>()
ConcurrentDictionary< Enum, object > _eventMap = new ConcurrentDictionary<Enum, object>()
Constructor & Destructor Documentation
Context() [1/3]
IuvoUnity.DataStructs.Context.Context ()
            {
            }
Referenced by CloneContext(), and MergeContexts().
Context() [2/3]
IuvoUnity.DataStructs.Context.Context (ref ConcurrentDictionary< Enum, object > contextDictionary)
            {
                _data = new ConcurrentDictionary<Enum, object>(contextDictionary);
            }
References _data.
Context() [3/3]
IuvoUnity.DataStructs.Context.Context (ref ConcurrentDictionary< Enum, object > contextDictionary, ref ConcurrentDictionary< Enum, object > eventDictionary)
            {
                _data = new ConcurrentDictionary<Enum, object>(contextDictionary);
                _eventMap = new ConcurrentDictionary<Enum, object>(eventDictionary);
            }
References _data, and _eventMap.
Member Function Documentation
ClearData()
void IuvoUnity.DataStructs.Context.ClearData ()
=> _data.Clear();
References _data.
Referenced by Dispose().
ClearEvents()
void IuvoUnity.DataStructs.Context.ClearEvents ()
            {
                foreach (var kvp in _eventMap)
                {
                    if (kvp.Value is FlexibleEvent fe)
                    {
                        fe.RemoveAllFlexibleEventListeners();
                    }
                    else if (kvp.Value is System.IDisposable disposable)
                    {
                        disposable.Dispose();
                    }
                }
                _eventMap.Clear();
            }
References _eventMap.
Referenced by Dispose().
CloneContext()
Context IuvoUnity.DataStructs.Context.CloneContext ()
            {
                var newDict = new ConcurrentDictionary<Enum, object>(_data);
                var newEventDict = new ConcurrentDictionary<Enum, object>(_eventMap);
                return new Context(ref newDict, ref newEventDict);
            }
References _data, _eventMap, and Context().
Dispose()
void IuvoUnity.DataStructs.Context.Dispose ()
Implements IuvoUnity.Interfaces.IContext.
            {
                ClearData();
                ClearEvents();
            }
References ClearData(), and ClearEvents().
Get< T >()
T IuvoUnity.DataStructs.Context.Get< T > (Enum key)
            {
                if (!ContextKeyGroups.IsValidKey(key))
                    throw new InvalidOperationException($"Invalid key type: {key.GetType().Name}");
                if (_data.TryGetValue(key, out var value) && value is T t)
                    return t;
                throw new KeyNotFoundException($"Key {key} not found or wrong type");
            }
References _data, and IuvoUnity.DataStructs.ContextKeyGroups.IsValidKey().
Has()
bool IuvoUnity.DataStructs.Context.Has (Enum key)
=> _data.ContainsKey(key);
References _data.
HasEvent()
bool IuvoUnity.DataStructs.Context.HasEvent (Enum key)
=> _eventMap.ContainsKey(key);
References _eventMap.
InvokeEvent()
void IuvoUnity.DataStructs.Context.InvokeEvent (Enum key)
            {
                if (TryGetEvent(key, out FlexibleEvent evt))
                {
                    evt.Invoke();
                }
            }
References TryGetEvent().
InvokeEvent< T >()
void IuvoUnity.DataStructs.Context.InvokeEvent< T > (Enum key, T value)
            {
                if (TryGetEvent<T>(key, out FlexibleEvent<T> evt))
                {
                    evt.Invoke(value);
                }
            }
References TryGetEvent().
MergeContexts()
void IuvoUnity.DataStructs.Context.MergeContexts (Context other, bool overwrite = true)
            {
                foreach (var kvp in other._data)
                {
                    if (overwrite || !_data.ContainsKey(kvp.Key))
                    {
                        _data[kvp.Key] = kvp.Value;
                    }
                }
                foreach (var kvp in other._eventMap)
                {
                    if (overwrite || !_eventMap.ContainsKey(kvp.Key))
                    {
                        _eventMap[kvp.Key] = kvp.Value;
                    }
                }
            }
References _data, _eventMap, and Context().
RegisterEvent()
void IuvoUnity.DataStructs.Context.RegisterEvent (Enum key, FlexibleEvent evt)
            {
                if (!ContextKeyGroups.IsValidKey(key)) return;
                _eventMap[key] = evt;
            }
References _eventMap, and IuvoUnity.DataStructs.ContextKeyGroups.IsValidKey().
RegisterEvent< T >()
void IuvoUnity.DataStructs.Context.RegisterEvent< T > (Enum key, FlexibleEvent< T > evt)
            {
                if (!ContextKeyGroups.IsValidKey(key)) return;
                _eventMap[key] = evt;
            }
References _eventMap, and IuvoUnity.DataStructs.ContextKeyGroups.IsValidKey().
Remove()
bool IuvoUnity.DataStructs.Context.Remove (Enum key)
=> _data.TryRemove(key, out _);
References _data.
RemoveEvent()
bool IuvoUnity.DataStructs.Context.RemoveEvent (Enum key)
=> _eventMap.TryRemove(key, out _);
References _eventMap.
Set< T >()
void IuvoUnity.DataStructs.Context.Set< T > (Enum key, T value)
            {
                if (!ContextKeyGroups.AllowedKeys.Contains(key.GetType()))
                {
                    IuvoDebug.DebugLogWarning($"Key {key} not in approved ContextKey groups.");
                    return;
                }
                _data[key] = value;
            }
References _data, IuvoUnity.DataStructs.ContextKeyGroups.AllowedKeys, and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
TryGet< T >()
bool IuvoUnity.DataStructs.Context.TryGet< T > (Enum key, out T value)
            {
                if (!ContextKeyGroups.IsValidKey(key))
                {
                    value = default;
                    return false;
                }
                if (_data.TryGetValue(key, out var obj) && obj is T t)
                {
                    value = t;
                    return true;
                }
                value = default;
                return false;
            }
References _data, and IuvoUnity.DataStructs.ContextKeyGroups.IsValidKey().
TryGetEvent()
bool IuvoUnity.DataStructs.Context.TryGetEvent (Enum key, out FlexibleEvent evt)
            {
                if (_eventMap.TryGetValue(key, out var val) && val is FlexibleEvent e)
                {
                    evt = e;
                    return true;
                }
                evt = null;
                return false;
            }
References _eventMap.
Referenced by InvokeEvent(), and InvokeEvent< T >().
TryGetEvent< T >()
bool IuvoUnity.DataStructs.Context.TryGetEvent< T > (Enum key, out FlexibleEvent< T > evt)
            {
                if (_eventMap.TryGetValue(key, out var val) && val is FlexibleEvent<T> e)
                {
                    evt = e;
                    return true;
                }
                evt = null;
                return false;
            }
References _eventMap.
Member Data Documentation
_data
ConcurrentDictionary<Enum, object> IuvoUnity.DataStructs.Context._data = new ConcurrentDictionary<Enum, object>() private
Referenced by ClearData(), CloneContext(), Context(), Context(), Get< T >(), Has(), MergeContexts(), Remove(), Set< T >(), and TryGet< T >().
_eventMap
ConcurrentDictionary<Enum, object> IuvoUnity.DataStructs.Context._eventMap = new ConcurrentDictionary<Enum, object>() private
Referenced by ClearEvents(), CloneContext(), Context(), HasEvent(), MergeContexts(), RegisterEvent(), RegisterEvent< T >(), RemoveEvent(), TryGetEvent(), and TryGetEvent< T >().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/Context.cs