Iuvo Unity: IuvoUnity.Inputs.InputActionBase Class Reference
IuvoUnity.Inputs.InputActionBase Class Reference abstract
Public Member Functions
void Enable ()
virtual void OnEnable ()
void Disable ()
virtual void OnDisable ()
void TriggerPerform ()
Public Attributes
UnityEvent OnPerformedUnity
System.Action OnPerformed
System.Action OnStarted
System.Action OnCanceled
UnityEvent< InputAction.CallbackContext > onPerformedWithContext
UnityEvent< InputAction.CallbackContext > onStartedWithContext
UnityEvent< InputAction.CallbackContext > onCanceledWithContext
Protected Member Functions
virtual void Awake ()
virtual void Update ()
virtual void FixedUpdate ()
virtual void OnInputPerformed (InputAction.CallbackContext context)
virtual void OnInputStarted (InputAction.CallbackContext context)
virtual void OnInputCanceled (InputAction.CallbackContext context)
virtual void Perform ()
virtual void OnDestroy ()
Protected Attributes
InputActionReference inputActionReference
Properties
string ActionName [get]
InputAction inputAction [get]
bool IsEnabled = false [get, private set]
Private Attributes
bool isSubscribed = false
Member Function Documentation
Awake()
virtual void IuvoUnity.Inputs.InputActionBase.Awake () protected virtual
            {
                if (inputActionReference == null || inputActionReference.action == null)
                {
                    IuvoDebug.DebugLogWarning(name + ": InputActionReference or its action is not assigned!");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), and inputActionReference.
Disable()
void IuvoUnity.Inputs.InputActionBase.Disable ()
            {
                if (IsEnabled)
                {
                    OnDisable();
                }
            }
References IsEnabled, and OnDisable().
Referenced by OnDestroy().
Enable()
void IuvoUnity.Inputs.InputActionBase.Enable ()
            {
                if (!IsEnabled)
                {
                    OnEnable();
                }
            }
References IsEnabled, and OnEnable().
FixedUpdate()
virtual void IuvoUnity.Inputs.InputActionBase.FixedUpdate () protected virtual
            {
                // Optionally overridden
            }
OnDestroy()
virtual void IuvoUnity.Inputs.InputActionBase.OnDestroy () protected virtual
            {
                Disable();
            }
References Disable().
OnDisable()
virtual void IuvoUnity.Inputs.InputActionBase.OnDisable () virtual
Reimplemented in IuvoUnity.Inputs.DirectionalInputAction, and IuvoUnity.Inputs.InputCooldownAction.
            {
                var action = inputAction;
                if (action != null && isSubscribed)
                {
                    isSubscribed = false;
                    action.started -= OnInputStarted;
                    action.performed -= OnInputPerformed;
                    action.canceled -= OnInputCanceled;
                    action.Disable();
                    IsEnabled = false;
                }
            }
References inputAction, IsEnabled, isSubscribed, OnInputCanceled(), OnInputPerformed(), and OnInputStarted().
Referenced by Disable().
OnEnable()
virtual void IuvoUnity.Inputs.InputActionBase.OnEnable () virtual
Implements IuvoUnity.Interfaces.IEnableable.
Reimplemented in IuvoUnity.Inputs.DirectionalInputAction.
            {
                var action = inputAction;
                if (action != null && !isSubscribed)
                {
                    isSubscribed = true;
                    action.started += OnInputStarted;
                    action.performed += OnInputPerformed;
                    action.canceled += OnInputCanceled;
                    action.Enable();
                    IsEnabled = true;
                }
            }
References inputAction, IsEnabled, isSubscribed, OnInputCanceled(), OnInputPerformed(), and OnInputStarted().
Referenced by Enable().
OnInputCanceled()
virtual void IuvoUnity.Inputs.InputActionBase.OnInputCanceled (InputAction.CallbackContext context) protected virtual
            {
                onCanceledWithContext?.Invoke(context);
                OnCanceled?.Invoke();
            }
References OnCanceled, and onCanceledWithContext.
Referenced by OnDisable(), and OnEnable().
OnInputPerformed()
virtual void IuvoUnity.Inputs.InputActionBase.OnInputPerformed (InputAction.CallbackContext context) protected virtual
Reimplemented in IuvoUnity.Inputs.AxisInputAction, IuvoUnity.Inputs.DirectionalInputAction, IuvoUnity.Inputs.DoubleTapInputAction, IuvoUnity.Inputs.InputCooldownAction, and IuvoUnity.Inputs.TapInputAction.
            {
                onPerformedWithContext?.Invoke(context);
                Perform();
            }
References onPerformedWithContext, and Perform().
Referenced by OnDisable(), and OnEnable().
OnInputStarted()
virtual void IuvoUnity.Inputs.InputActionBase.OnInputStarted (InputAction.CallbackContext context) protected virtual
            {
                onStartedWithContext?.Invoke(context);
                OnStarted?.Invoke();
            }
References OnStarted, and onStartedWithContext.
Referenced by OnDisable(), and OnEnable().
Perform()
virtual void IuvoUnity.Inputs.InputActionBase.Perform () protected virtual
            {
                IuvoDebug.DebugLog($"{ActionName} action performed.");
                OnPerformedUnity?.Invoke();
                OnPerformed?.Invoke();
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), OnPerformed, and OnPerformedUnity.
Referenced by IuvoUnity.Inputs.AxisInputAction.OnInputPerformed(), IuvoUnity.Inputs.DirectionalInputAction.OnInputPerformed(), IuvoUnity.Inputs.DoubleTapInputAction.OnInputPerformed(), OnInputPerformed(), IuvoUnity.Inputs.InputCooldownAction.OnInputPerformed(), and IuvoUnity.Inputs.TapInputAction.OnInputPerformed().
TriggerPerform()
void IuvoUnity.Inputs.InputActionBase.TriggerPerform ()
=> Perform();
Update()
virtual void IuvoUnity.Inputs.InputActionBase.Update () protected virtual
Reimplemented in IuvoUnity.Inputs.AxisInputAction, and IuvoUnity.Inputs.DoubleTapInputAction.
            {
                // Optionally overridden
            }
Member Data Documentation
inputActionReference
InputActionReference IuvoUnity.Inputs.InputActionBase.inputActionReference protected
Referenced by Awake().
isSubscribed
bool IuvoUnity.Inputs.InputActionBase.isSubscribed = false private
Referenced by OnDisable(), and OnEnable().
OnCanceled
System.Action IuvoUnity.Inputs.InputActionBase.OnCanceled
Referenced by OnInputCanceled().
onCanceledWithContext
UnityEvent<InputAction.CallbackContext> IuvoUnity.Inputs.InputActionBase.onCanceledWithContext
Referenced by OnInputCanceled().
OnPerformed
System.Action IuvoUnity.Inputs.InputActionBase.OnPerformed
Referenced by Perform().
OnPerformedUnity
UnityEvent IuvoUnity.Inputs.InputActionBase.OnPerformedUnity
Referenced by Perform().
onPerformedWithContext
UnityEvent<InputAction.CallbackContext> IuvoUnity.Inputs.InputActionBase.onPerformedWithContext
Referenced by OnInputPerformed().
OnStarted
System.Action IuvoUnity.Inputs.InputActionBase.OnStarted
Referenced by OnInputStarted().
onStartedWithContext
UnityEvent<InputAction.CallbackContext> IuvoUnity.Inputs.InputActionBase.onStartedWithContext
Referenced by OnInputStarted().
Property Documentation
ActionName
string IuvoUnity.Inputs.InputActionBase.ActionName get
inputAction
InputAction IuvoUnity.Inputs.InputActionBase.inputAction get
Referenced by OnDisable(), OnEnable(), and IuvoUnity.Inputs.AxisInputAction.Update().
IsEnabled
bool IuvoUnity.Inputs.InputActionBase.IsEnabled = false get private set
{ get; private set; } = false;
Referenced by Disable(), Enable(), OnDisable(), and OnEnable().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Input/InputBase.cs