Iuvo Unity: IuvoUnity.DataStructs.ActorContext Class Reference
IuvoUnity.DataStructs.ActorContext Class Reference
Public Member Functions
ActorContext ()
void Dispose ()
IEnumerable< GameObject > GetTargets ()
int GetTargetCount ()
GameObject GetFirstTarget ()
void SetTargets (IEnumerable< GameObject > objs)
void AddTarget (GameObject obj)
void RemoveTarget (GameObject obj)
void ClearTargets ()
bool HasTargets ()
bool ContainsTarget (GameObject obj)
IEnumerable< GameObject > GetPlayers ()
int GetPlayerCount ()
GameObject GetFirstPlayer ()
void SetPlayers (IEnumerable< GameObject > objs)
void AddPlayer (GameObject obj)
void RemovePlayer (GameObject obj)
void ClearPlayers ()
bool HasPlayers ()
bool ContainsPlayer (GameObject obj)
IEnumerable< GameObject > GetAllies ()
int GetAllyCount ()
GameObject GetFirstAlly ()
void SetAllies (IEnumerable< GameObject > objs)
void AddAlly (GameObject obj)
void RemoveAlly (GameObject obj)
void ClearAllies ()
bool HasAllies ()
bool ContainsAlly (GameObject obj)
IEnumerable< GameObject > GetEnemies ()
int GetEnemyCount ()
GameObject GetFirstEnemy ()
void SetEnemies (IEnumerable< GameObject > objs)
void AddEnemy (GameObject obj)
void RemoveEnemy (GameObject obj)
void ClearEnemies ()
bool HasEnemies ()
bool ContainsEnemy (GameObject obj)
IEnumerable< GameObject > GetCameras ()
int GetCameraCount ()
GameObject GetFirstCamera ()
void SetCameras (IEnumerable< GameObject > objs)
void AddCamera (GameObject obj)
void RemoveCamera (GameObject obj)
void ClearCameras ()
bool HasCameras ()
bool ContainsCamera (GameObject obj)
IEnumerable< GameObject > GetInteractables ()
int GetInteractableCount ()
GameObject GetFirstInteractable ()
void SetInteractables (IEnumerable< GameObject > objs)
void AddInteractable (GameObject obj)
void RemoveInteractable (GameObject obj)
void ClearInteractables ()
bool HasInteractables ()
bool ContainsInteractable (GameObject obj)
IEnumerable< GameObject > GetRandomObjects ()
int GetRandomObjectCount ()
GameObject GetFirstRandomObject ()
void SetRandomObjects (IEnumerable< GameObject > objs)
void AddRandomObject (GameObject obj)
void RemoveRandomObject (GameObject obj)
void ClearRandomObjects ()
bool HasRandomObjects ()
bool ContainsRandomObject (GameObject obj)
Private Member Functions
IEnumerable< GameObject > Get (ContextKey_ACTOR key)
GameObject GetFirst (ContextKey_ACTOR key)
void Set (ContextKey_ACTOR key, IEnumerable< GameObject > objs)
void Add (ContextKey_ACTOR key, GameObject obj)
void Remove (ContextKey_ACTOR key, GameObject obj)
bool Has (ContextKey_ACTOR key)
bool Contains (ContextKey_ACTOR key, GameObject obj)
void Clear (ContextKey_ACTOR key)
void ClearAll ()
Private Attributes
Dictionary< ContextKey_ACTOR, HashSet< GameObject > > actors = new()
Constructor & Destructor Documentation
ActorContext()
IuvoUnity.DataStructs.ActorContext.ActorContext ()
            {
                foreach (ContextKey_ACTOR key in System.Enum.GetValues(typeof(ContextKey_ACTOR)))
                {
                    actors[key] = new HashSet<GameObject>();
                }
            }
References actors.
Member Function Documentation
Add()
void IuvoUnity.DataStructs.ActorContext.Add (ContextKey_ACTOR key, GameObject obj) private
            {
                if (obj != null)
                    actors[key].Add(obj);
            }
References actors.
Referenced by AddAlly(), AddCamera(), AddEnemy(), AddInteractable(), AddPlayer(), AddRandomObject(), and AddTarget().
AddAlly()
void IuvoUnity.DataStructs.ActorContext.AddAlly (GameObject obj)
=> Add(ContextKey_ACTOR.Allies, obj);
References Add(), and AddAlly().
Referenced by AddAlly().
AddCamera()
void IuvoUnity.DataStructs.ActorContext.AddCamera (GameObject obj)
=> Add(ContextKey_ACTOR.Cameras, obj);
References Add(), and AddCamera().
Referenced by AddCamera().
AddEnemy()
void IuvoUnity.DataStructs.ActorContext.AddEnemy (GameObject obj)
=> Add(ContextKey_ACTOR.Enemies, obj);
References Add(), and AddEnemy().
Referenced by AddEnemy().
AddInteractable()
void IuvoUnity.DataStructs.ActorContext.AddInteractable (GameObject obj)
=> Add(ContextKey_ACTOR.Interactables, obj);
References Add(), and AddInteractable().
Referenced by AddInteractable().
AddPlayer()
void IuvoUnity.DataStructs.ActorContext.AddPlayer (GameObject obj)
=> Add(ContextKey_ACTOR.Players, obj);
References Add(), and AddPlayer().
Referenced by AddPlayer().
AddRandomObject()
void IuvoUnity.DataStructs.ActorContext.AddRandomObject (GameObject obj)
=> Add(ContextKey_ACTOR.RandomObjects, obj);
References Add(), and AddRandomObject().
Referenced by AddRandomObject().
AddTarget()
void IuvoUnity.DataStructs.ActorContext.AddTarget (GameObject obj)
=> Add(ContextKey_ACTOR.Targets, obj);
References Add(), and AddTarget().
Referenced by AddTarget().
Clear()
void IuvoUnity.DataStructs.ActorContext.Clear (ContextKey_ACTOR key) private
            {
                actors[key].Clear();
            }
References actors.
Referenced by ClearAll(), ClearAllies(), ClearCameras(), ClearEnemies(), ClearInteractables(), ClearPlayers(), ClearRandomObjects(), and ClearTargets().
ClearAll()
void IuvoUnity.DataStructs.ActorContext.ClearAll () private
            {
                foreach (var key in actors.Keys)
                    Clear(key);
            }
References actors, and Clear().
Referenced by Dispose().
ClearAllies()
void IuvoUnity.DataStructs.ActorContext.ClearAllies ()
=> Clear(ContextKey_ACTOR.Allies);
References Clear(), and ClearAllies().
Referenced by ClearAllies().
ClearCameras()
void IuvoUnity.DataStructs.ActorContext.ClearCameras ()
=> Clear(ContextKey_ACTOR.Cameras);
References Clear(), and ClearCameras().
Referenced by ClearCameras().
ClearEnemies()
void IuvoUnity.DataStructs.ActorContext.ClearEnemies ()
=> Clear(ContextKey_ACTOR.Enemies);
References Clear(), and ClearEnemies().
Referenced by ClearEnemies().
ClearInteractables()
void IuvoUnity.DataStructs.ActorContext.ClearInteractables ()
=> Clear(ContextKey_ACTOR.Interactables);
References Clear(), and ClearInteractables().
Referenced by ClearInteractables().
ClearPlayers()
void IuvoUnity.DataStructs.ActorContext.ClearPlayers ()
=> Clear(ContextKey_ACTOR.Players);
References Clear(), and ClearPlayers().
Referenced by ClearPlayers().
ClearRandomObjects()
void IuvoUnity.DataStructs.ActorContext.ClearRandomObjects ()
=> Clear(ContextKey_ACTOR.RandomObjects);
References Clear(), and ClearRandomObjects().
Referenced by ClearRandomObjects().
ClearTargets()
void IuvoUnity.DataStructs.ActorContext.ClearTargets ()
=> Clear(ContextKey_ACTOR.Targets);
References Clear(), and ClearTargets().
Referenced by ClearTargets().
Contains()
bool IuvoUnity.DataStructs.ActorContext.Contains (ContextKey_ACTOR key, GameObject obj) private
            {
                return obj != null && actors[key].Contains(obj);
            }
References actors.
Referenced by ContainsAlly(), ContainsCamera(), ContainsEnemy(), ContainsInteractable(), ContainsPlayer(), ContainsRandomObject(), and ContainsTarget().
ContainsAlly()
bool IuvoUnity.DataStructs.ActorContext.ContainsAlly (GameObject obj)
=> Contains(ContextKey_ACTOR.Allies, obj);
References Contains(), and ContainsAlly().
Referenced by ContainsAlly().
ContainsCamera()
bool IuvoUnity.DataStructs.ActorContext.ContainsCamera (GameObject obj)
=> Contains(ContextKey_ACTOR.Cameras, obj);
References Contains(), and ContainsCamera().
Referenced by ContainsCamera().
ContainsEnemy()
bool IuvoUnity.DataStructs.ActorContext.ContainsEnemy (GameObject obj)
=> Contains(ContextKey_ACTOR.Enemies, obj);
References Contains(), and ContainsEnemy().
Referenced by ContainsEnemy().
ContainsInteractable()
bool IuvoUnity.DataStructs.ActorContext.ContainsInteractable (GameObject obj)
=> Contains(ContextKey_ACTOR.Interactables, obj);
References Contains(), and ContainsInteractable().
Referenced by ContainsInteractable().
ContainsPlayer()
bool IuvoUnity.DataStructs.ActorContext.ContainsPlayer (GameObject obj)
=> Contains(ContextKey_ACTOR.Players, obj);
References Contains(), and ContainsPlayer().
Referenced by ContainsPlayer().
ContainsRandomObject()
bool IuvoUnity.DataStructs.ActorContext.ContainsRandomObject (GameObject obj)
=> Contains(ContextKey_ACTOR.RandomObjects, obj);
References Contains(), and ContainsRandomObject().
Referenced by ContainsRandomObject().
ContainsTarget()
bool IuvoUnity.DataStructs.ActorContext.ContainsTarget (GameObject obj)
=> Contains(ContextKey_ACTOR.Targets, obj);
References Contains(), and ContainsTarget().
Referenced by ContainsTarget().
Dispose()
void IuvoUnity.DataStructs.ActorContext.Dispose ()
Implements IuvoUnity.Interfaces.IContext.
            {
                ClearAll();
            }
References ClearAll().
Get()
IEnumerable< GameObject > IuvoUnity.DataStructs.ActorContext.Get (ContextKey_ACTOR key) private
=> actors[key];
References actors.
Referenced by GetAllies(), GetCameras(), GetEnemies(), GetInteractables(), GetPlayers(), and GetRandomObjects().
GetAllies()
IEnumerable< GameObject > IuvoUnity.DataStructs.ActorContext.GetAllies ()
=> Get(ContextKey_ACTOR.Allies);
References Get(), and GetAllies().
Referenced by GetAllies(), and GetAllyCount().
GetAllyCount()
int IuvoUnity.DataStructs.ActorContext.GetAllyCount ()
=> GetAllies() is ICollection<GameObject> coll ? coll.Count : 0;
References GetAllies(), and GetAllyCount().
Referenced by GetAllyCount().
GetCameraCount()
int IuvoUnity.DataStructs.ActorContext.GetCameraCount ()
=> GetCameras() is ICollection<GameObject> coll ? coll.Count : 0;
References GetCameraCount(), and GetCameras().
Referenced by GetCameraCount().
GetCameras()
IEnumerable< GameObject > IuvoUnity.DataStructs.ActorContext.GetCameras ()
=> Get(ContextKey_ACTOR.Cameras);
References Get(), and GetCameras().
Referenced by GetCameraCount(), and GetCameras().
GetEnemies()
IEnumerable< GameObject > IuvoUnity.DataStructs.ActorContext.GetEnemies ()
=> Get(ContextKey_ACTOR.Enemies);
References Get(), and GetEnemies().
Referenced by GetEnemies(), and GetEnemyCount().
GetEnemyCount()
int IuvoUnity.DataStructs.ActorContext.GetEnemyCount ()
=> GetEnemies() is ICollection<GameObject> coll ? coll.Count : 0;
References GetEnemies(), and GetEnemyCount().
Referenced by GetEnemyCount().
GetFirst()
GameObject IuvoUnity.DataStructs.ActorContext.GetFirst (ContextKey_ACTOR key) private
            {
                foreach (var obj in actors[key])
                    return obj;
                return null;
            }
References actors.
Referenced by GetFirstAlly(), GetFirstCamera(), GetFirstEnemy(), GetFirstInteractable(), GetFirstPlayer(), GetFirstRandomObject(), and GetFirstTarget().
GetFirstAlly()
GameObject IuvoUnity.DataStructs.ActorContext.GetFirstAlly ()
=> GetFirst(ContextKey_ACTOR.Allies);
References GetFirst(), and GetFirstAlly().
Referenced by GetFirstAlly().
GetFirstCamera()
GameObject IuvoUnity.DataStructs.ActorContext.GetFirstCamera ()
=> GetFirst(ContextKey_ACTOR.Cameras);
References GetFirst(), and GetFirstCamera().
Referenced by GetFirstCamera().
GetFirstEnemy()
GameObject IuvoUnity.DataStructs.ActorContext.GetFirstEnemy ()
=> GetFirst(ContextKey_ACTOR.Enemies);
References GetFirst(), and GetFirstEnemy().
Referenced by GetFirstEnemy().
GetFirstInteractable()
GameObject IuvoUnity.DataStructs.ActorContext.GetFirstInteractable ()
=> GetFirst(ContextKey_ACTOR.Interactables);
References GetFirst(), and GetFirstInteractable().
Referenced by GetFirstInteractable().
GetFirstPlayer()
GameObject IuvoUnity.DataStructs.ActorContext.GetFirstPlayer ()
=> GetFirst(ContextKey_ACTOR.Players);
References GetFirst(), and GetFirstPlayer().
Referenced by GetFirstPlayer().
GetFirstRandomObject()
GameObject IuvoUnity.DataStructs.ActorContext.GetFirstRandomObject ()
=> GetFirst(ContextKey_ACTOR.RandomObjects);
References GetFirst(), and GetFirstRandomObject().
Referenced by GetFirstRandomObject().
GetFirstTarget()
GameObject IuvoUnity.DataStructs.ActorContext.GetFirstTarget ()
=> GetFirst(ContextKey_ACTOR.Targets);
References GetFirst(), and GetFirstTarget().
Referenced by GetFirstTarget().
GetInteractableCount()
int IuvoUnity.DataStructs.ActorContext.GetInteractableCount ()
=> GetInteractables() is ICollection<GameObject> coll ? coll.Count : 0;
References GetInteractableCount(), and GetInteractables().
Referenced by GetInteractableCount().
GetInteractables()
IEnumerable< GameObject > IuvoUnity.DataStructs.ActorContext.GetInteractables ()
=> Get(ContextKey_ACTOR.Interactables);
References Get(), and GetInteractables().
Referenced by GetInteractableCount(), and GetInteractables().
GetPlayerCount()
int IuvoUnity.DataStructs.ActorContext.GetPlayerCount ()
=> GetPlayers() is ICollection<GameObject> coll ? coll.Count : 0;
References GetPlayerCount(), and GetPlayers().
Referenced by GetPlayerCount().
GetPlayers()
IEnumerable< GameObject > IuvoUnity.DataStructs.ActorContext.GetPlayers ()
=> Get(ContextKey_ACTOR.Players);
References Get(), and GetPlayers().
Referenced by GetPlayerCount(), and GetPlayers().
GetRandomObjectCount()
int IuvoUnity.DataStructs.ActorContext.GetRandomObjectCount ()
=> GetRandomObjects() is ICollection<GameObject> coll ? coll.Count : 0;
References GetRandomObjectCount(), and GetRandomObjects().
Referenced by GetRandomObjectCount().
GetRandomObjects()
IEnumerable< GameObject > IuvoUnity.DataStructs.ActorContext.GetRandomObjects ()
=> Get(ContextKey_ACTOR.RandomObjects);
References Get(), and GetRandomObjects().
Referenced by GetRandomObjectCount(), and GetRandomObjects().
GetTargetCount()
int IuvoUnity.DataStructs.ActorContext.GetTargetCount ()
=> GetTargets() is ICollection<GameObject> coll ? coll.Count : 0;
GetTargets()
IEnumerable< GameObject > IuvoUnity.DataStructs.ActorContext.GetTargets ()
=> Get(ContextKey_ACTOR.Targets);
Has()
bool IuvoUnity.DataStructs.ActorContext.Has (ContextKey_ACTOR key) private
=> actors[key].Count > 0;
References actors.
Referenced by HasAllies(), HasCameras(), HasEnemies(), HasInteractables(), HasPlayers(), HasRandomObjects(), and HasTargets().
HasAllies()
bool IuvoUnity.DataStructs.ActorContext.HasAllies ()
=> Has(ContextKey_ACTOR.Allies);
References Has(), and HasAllies().
Referenced by HasAllies().
HasCameras()
bool IuvoUnity.DataStructs.ActorContext.HasCameras ()
=> Has(ContextKey_ACTOR.Cameras);
References Has(), and HasCameras().
Referenced by HasCameras().
HasEnemies()
bool IuvoUnity.DataStructs.ActorContext.HasEnemies ()
=> Has(ContextKey_ACTOR.Enemies);
References Has(), and HasEnemies().
Referenced by HasEnemies().
HasInteractables()
bool IuvoUnity.DataStructs.ActorContext.HasInteractables ()
=> Has(ContextKey_ACTOR.Interactables);
References Has(), and HasInteractables().
Referenced by HasInteractables().
HasPlayers()
bool IuvoUnity.DataStructs.ActorContext.HasPlayers ()
=> Has(ContextKey_ACTOR.Players);
References Has(), and HasPlayers().
Referenced by HasPlayers().
HasRandomObjects()
bool IuvoUnity.DataStructs.ActorContext.HasRandomObjects ()
=> Has(ContextKey_ACTOR.RandomObjects);
References Has(), and HasRandomObjects().
Referenced by HasRandomObjects().
HasTargets()
bool IuvoUnity.DataStructs.ActorContext.HasTargets ()
=> Has(ContextKey_ACTOR.Targets);
References Has(), and HasTargets().
Referenced by HasTargets().
Remove()
void IuvoUnity.DataStructs.ActorContext.Remove (ContextKey_ACTOR key, GameObject obj) private
            {
                if (obj != null)
                    actors[key].Remove(obj);
            }
References actors.
Referenced by RemoveAlly(), RemoveCamera(), RemoveEnemy(), RemoveInteractable(), RemovePlayer(), RemoveRandomObject(), and RemoveTarget().
RemoveAlly()
void IuvoUnity.DataStructs.ActorContext.RemoveAlly (GameObject obj)
=> Remove(ContextKey_ACTOR.Allies, obj);
References Remove(), and RemoveAlly().
Referenced by RemoveAlly().
RemoveCamera()
void IuvoUnity.DataStructs.ActorContext.RemoveCamera (GameObject obj)
=> Remove(ContextKey_ACTOR.Cameras, obj);
References Remove(), and RemoveCamera().
Referenced by RemoveCamera().
RemoveEnemy()
void IuvoUnity.DataStructs.ActorContext.RemoveEnemy (GameObject obj)
=> Remove(ContextKey_ACTOR.Enemies, obj);
References Remove(), and RemoveEnemy().
Referenced by RemoveEnemy().
RemoveInteractable()
void IuvoUnity.DataStructs.ActorContext.RemoveInteractable (GameObject obj)
=> Remove(ContextKey_ACTOR.Interactables, obj);
References Remove(), and RemoveInteractable().
Referenced by RemoveInteractable().
RemovePlayer()
void IuvoUnity.DataStructs.ActorContext.RemovePlayer (GameObject obj)
=> Remove(ContextKey_ACTOR.Players, obj);
References Remove(), and RemovePlayer().
Referenced by RemovePlayer().
RemoveRandomObject()
void IuvoUnity.DataStructs.ActorContext.RemoveRandomObject (GameObject obj)
=> Remove(ContextKey_ACTOR.RandomObjects, obj);
References Remove(), and RemoveRandomObject().
Referenced by RemoveRandomObject().
RemoveTarget()
void IuvoUnity.DataStructs.ActorContext.RemoveTarget (GameObject obj)
=> Remove(ContextKey_ACTOR.Targets, obj);
References Remove(), and RemoveTarget().
Referenced by RemoveTarget().
Set()
void IuvoUnity.DataStructs.ActorContext.Set (ContextKey_ACTOR key, IEnumerable< GameObject > objs) private
            {
                actors[key].Clear();
                foreach (var obj in objs)
                {
                    if (obj != null)
                        actors[key].Add(obj);
                }
            }
References actors.
Referenced by SetAllies(), SetCameras(), SetEnemies(), SetInteractables(), SetPlayers(), SetRandomObjects(), and SetTargets().
SetAllies()
void IuvoUnity.DataStructs.ActorContext.SetAllies (IEnumerable< GameObject > objs)
=> Set(ContextKey_ACTOR.Allies, objs);
References Set(), and SetAllies().
Referenced by SetAllies().
SetCameras()
void IuvoUnity.DataStructs.ActorContext.SetCameras (IEnumerable< GameObject > objs)
=> Set(ContextKey_ACTOR.Cameras, objs);
References Set(), and SetCameras().
Referenced by SetCameras().
SetEnemies()
void IuvoUnity.DataStructs.ActorContext.SetEnemies (IEnumerable< GameObject > objs)
=> Set(ContextKey_ACTOR.Enemies, objs);
References Set(), and SetEnemies().
Referenced by SetEnemies().
SetInteractables()
void IuvoUnity.DataStructs.ActorContext.SetInteractables (IEnumerable< GameObject > objs)
=> Set(ContextKey_ACTOR.Interactables, objs);
References Set(), and SetInteractables().
Referenced by SetInteractables().
SetPlayers()
void IuvoUnity.DataStructs.ActorContext.SetPlayers (IEnumerable< GameObject > objs)
=> Set(ContextKey_ACTOR.Players, objs);
References Set(), and SetPlayers().
Referenced by SetPlayers().
SetRandomObjects()
void IuvoUnity.DataStructs.ActorContext.SetRandomObjects (IEnumerable< GameObject > objs)
=> Set(ContextKey_ACTOR.RandomObjects, objs);
References Set(), and SetRandomObjects().
Referenced by SetRandomObjects().
SetTargets()
void IuvoUnity.DataStructs.ActorContext.SetTargets (IEnumerable< GameObject > objs)
=> Set(ContextKey_ACTOR.Targets, objs);
References Set(), and SetTargets().
Referenced by SetTargets().
Member Data Documentation
actors
Dictionary<ContextKey_ACTOR, HashSet<GameObject> > IuvoUnity.DataStructs.ActorContext.actors = new() private
Referenced by ActorContext(), Add(), Clear(), ClearAll(), Contains(), Get(), GetFirst(), Has(), Remove(), and Set().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/ActorContext.cs