Iuvo Unity: IuvoUnity.Inputs.InputActionHandler< T > Class Template Reference
IuvoUnity.Inputs.InputActionHandler< T > Class Template Reference
Public Member Functions
InputActionHandler (T inputActionInstance)
void Enable ()
void Disable ()
string GetActionName ()
void Perform ()
TVal? ReadValue< TVal > ()
Vector2? GetAxisValue ()
void Dispose ()
Properties
T InputActionInstance [get, private set]
Events
Action OnPerformed
Action OnStarted
Action OnCanceled
Private Member Functions
void HandlePerformed ()
void HandleStarted ()
void HandleCanceled ()
Member Function Documentation
Disable()
void IuvoUnity.Inputs.InputActionHandler< T >.Disable ()
            {
                InputActionInstance.Disable();
            }
References InputActionInstance.
Dispose()
void IuvoUnity.Inputs.InputActionHandler< T >.Dispose ()
            {
                if (InputActionInstance != null)
                {
                    InputActionInstance.OnPerformed -= HandlePerformed;
                    InputActionInstance.OnStarted -= HandleStarted;
                    InputActionInstance.OnCanceled -= HandleCanceled;
                    InputActionInstance.Disable();
                }
            }
References HandleCanceled(), HandlePerformed(), HandleStarted(), and InputActionInstance.
Enable()
void IuvoUnity.Inputs.InputActionHandler< T >.Enable ()
            {
                InputActionInstance.Enable();
            }
References InputActionInstance.
GetActionName()
string IuvoUnity.Inputs.InputActionHandler< T >.GetActionName ()
            {
                return InputActionInstance.ActionName;
            }
References InputActionInstance.
GetAxisValue()
Vector2? IuvoUnity.Inputs.InputActionHandler< T >.GetAxisValue ()
            {
                if (InputActionInstance is AxisInputAction axisAction)
                    return axisAction.CurrentValue;
                return null;
            }
References InputActionInstance.
HandleCanceled()
void IuvoUnity.Inputs.InputActionHandler< T >.HandleCanceled () private
            {
                OnCanceled?.Invoke();
            }
References OnCanceled.
Referenced by Dispose(), and InputActionHandler().
HandlePerformed()
void IuvoUnity.Inputs.InputActionHandler< T >.HandlePerformed () private
            {
                OnPerformed?.Invoke();
            }
References OnPerformed.
Referenced by Dispose(), and InputActionHandler().
HandleStarted()
void IuvoUnity.Inputs.InputActionHandler< T >.HandleStarted () private
            {
                OnStarted?.Invoke();
            }
References OnStarted.
Referenced by Dispose(), and InputActionHandler().
InputActionHandler()
IuvoUnity.Inputs.InputActionHandler< T >.InputActionHandler (T inputActionInstance)
            {
                InputActionInstance = inputActionInstance ?? throw new ArgumentNullException(nameof(inputActionInstance));
                // Subscribe to InputActionBase events
                InputActionInstance.OnPerformed += HandlePerformed;
                InputActionInstance.OnStarted += HandleStarted;
                InputActionInstance.OnCanceled += HandleCanceled;
            }
References HandleCanceled(), HandlePerformed(), HandleStarted(), and InputActionInstance.
Perform()
void IuvoUnity.Inputs.InputActionHandler< T >.Perform ()
            {
                InputActionInstance.TriggerPerform();
            }
References InputActionInstance.
ReadValue< TVal >()
TVal? IuvoUnity.Inputs.InputActionHandler< T >.ReadValue< TVal > ()
Type Constraints
TVal : struct
                                                      : struct
            {
                return InputActionInstance?.inputAction?.ReadValue<TVal>();
            }
References InputActionInstance.
Property Documentation
InputActionInstance
T IuvoUnity.Inputs.InputActionHandler< T >.InputActionInstance get private set
{ get; private set; }
Referenced by Disable(), Dispose(), Enable(), GetActionName(), GetAxisValue(), InputActionHandler(), Perform(), and ReadValue< TVal >().
Event Documentation
OnCanceled
Action IuvoUnity.Inputs.InputActionHandler< T >.OnCanceled
Referenced by HandleCanceled().
OnPerformed
Action IuvoUnity.Inputs.InputActionHandler< T >.OnPerformed
Referenced by HandlePerformed().
OnStarted
Action IuvoUnity.Inputs.InputActionHandler< T >.OnStarted
Referenced by HandleStarted().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Input/InputBase.cs