Iuvo Unity: IuvoUnity.IuvoPhysics.SphereCastData Class Reference
IuvoUnity.IuvoPhysics.SphereCastData Class Reference
Public Attributes
Vector3 checkOrigin = Vector3.zero
float distanceToCheck = 1.25f
float radiusToCheck = 1.0f
Vector3 directionToCheck = Vector3.down
bool isTouching = false
Ray ray = new Ray()
RaycastHit hit = new RaycastHit()
LayerMask layerMask = new LayerMask()
Private Member Functions
SphereCastData ()
Constructor & Destructor Documentation
SphereCastData()
IuvoUnity.IuvoPhysics.SphereCastData.SphereCastData () private
            {
                checkOrigin = Vector3.zero;
                distanceToCheck = 1.25f;
                radiusToCheck = 1.0f;
                directionToCheck = Vector3.down;
                isTouching = false;
                ray = new Ray(checkOrigin, directionToCheck);
                hit = new RaycastHit();
                layerMask = LayerMask.GetMask("Default");
            }
References checkOrigin, directionToCheck, distanceToCheck, hit, isTouching, layerMask, radiusToCheck, and ray.
Member Data Documentation
checkOrigin
Vector3 IuvoUnity.IuvoPhysics.SphereCastData.checkOrigin = Vector3.zero
Referenced by SphereCastData().
directionToCheck
Vector3 IuvoUnity.IuvoPhysics.SphereCastData.directionToCheck = Vector3.down
Referenced by SphereCastData().
distanceToCheck
float IuvoUnity.IuvoPhysics.SphereCastData.distanceToCheck = 1.25f
Referenced by SphereCastData().
hit
RaycastHit IuvoUnity.IuvoPhysics.SphereCastData.hit = new RaycastHit()
Referenced by SphereCastData().
isTouching
bool IuvoUnity.IuvoPhysics.SphereCastData.isTouching = false
Referenced by SphereCastData().
layerMask
LayerMask IuvoUnity.IuvoPhysics.SphereCastData.layerMask = new LayerMask()
Referenced by SphereCastData().
radiusToCheck
float IuvoUnity.IuvoPhysics.SphereCastData.radiusToCheck = 1.0f
Referenced by SphereCastData().
ray
Ray IuvoUnity.IuvoPhysics.SphereCastData.ray = new Ray()
Referenced by SphereCastData().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Physics/SphereCaster.cs