Iuvo Unity: IuvoUnity.Events.FlexibleEvent< T1, T2 > Class Template Reference
IuvoUnity.Events.FlexibleEvent< T1, T2 > Class Template Reference
Public Member Functions
void Invoke (T1 arg1, T2 arg2)
void AddListener (Action< T1, T2 > listener)
void RemoveListener (Action< T1, T2 > listener)
void AddUnityListener (UnityAction< T1, T2 > listener)
void RemoveUnityListener (UnityAction< T1, T2 > listener)
void RemoveAllFlexibleEventListeners ()
Properties
UnityEvent< T1, T2 > UnityEvent [get]
Events
Action< T1, T2 > internalEvent
Private Attributes
UnityEvent< T1, T2 > unityEvent = new UnityEvent<T1, T2>()
Member Function Documentation
AddListener()
void IuvoUnity.Events.FlexibleEvent< T1, T2 >.AddListener (Action< T1, T2 > listener)
            {
                internalEvent += listener;
                //internalActions.Add(listener);
            }
References internalEvent.
AddUnityListener()
void IuvoUnity.Events.FlexibleEvent< T1, T2 >.AddUnityListener (UnityAction< T1, T2 > listener)
            {
                unityEvent.AddListener(listener);
            }
References unityEvent.
Invoke()
void IuvoUnity.Events.FlexibleEvent< T1, T2 >.Invoke (T1 arg1, T2 arg2)
            {
                unityEvent?.Invoke(arg1, arg2);
                internalEvent?.Invoke(arg1, arg2);
            }
References internalEvent, and unityEvent.
RemoveAllFlexibleEventListeners()
void IuvoUnity.Events.FlexibleEvent< T1, T2 >.RemoveAllFlexibleEventListeners ()
            {
                //foreach (var evt in internalActions)
                //    RemoveListener(evt);
                internalEvent = null; // Clear the C# event to prevent memory leaks
                unityEvent.RemoveAllListeners();
            }
References internalEvent, and unityEvent.
RemoveListener()
void IuvoUnity.Events.FlexibleEvent< T1, T2 >.RemoveListener (Action< T1, T2 > listener)
            {
                internalEvent -= listener;
                //internalActions.Remove(listener);
            }
References internalEvent.
RemoveUnityListener()
void IuvoUnity.Events.FlexibleEvent< T1, T2 >.RemoveUnityListener (UnityAction< T1, T2 > listener)
            {
                unityEvent.RemoveListener(listener);
            }
References unityEvent.
Member Data Documentation
unityEvent
UnityEvent<T1, T2> IuvoUnity.Events.FlexibleEvent< T1, T2 >.unityEvent = new UnityEvent<T1, T2>() private
Referenced by AddUnityListener(), Invoke(), RemoveAllFlexibleEventListeners(), and RemoveUnityListener().
Property Documentation
UnityEvent
UnityEvent<T1, T2> IuvoUnity.Events.FlexibleEvent< T1, T2 >.UnityEvent get
Event Documentation
internalEvent
Action<T1, T2> IuvoUnity.Events.FlexibleEvent< T1, T2 >.internalEvent private
Referenced by AddListener(), Invoke(), RemoveAllFlexibleEventListeners(), and RemoveListener().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Events/FlexibleEvent.cs