Iuvo Unity: IuvoUnity.Configurations.TimerConfiguration Class Reference
IuvoUnity.Configurations.TimerConfiguration Class Reference
Public Member Functions
override void Configure (Timer configurable)
override void Reconfigure (Timer reconfigurable)
override void PrintInfo ()
Public Member Functions inherited from IuvoUnity.Configurations.BaseConfig< T >
virtual void Configure (T configurable)
virtual void Reconfigure (T reconfigurable)
virtual string GetConfigSerializePath (string actingConfigClass, string objectToSerializeName, string parentConfigClass="BaseConfig")
Public Attributes
TimerData timerData
Public Attributes inherited from IuvoUnity.Configurations.BaseConfig< T >
string configName
Private Member Functions
void OnEnable ()
Member Function Documentation
Configure()
override void IuvoUnity.Configurations.TimerConfiguration.Configure (Timer configurable)
            {
                if (configurable == null)
                {
                    IuvoDebug.DebugLogError("Configurable Timer is null.");
                    return;
                }
                base.Configure(configurable);
                configurable.ConfigureTimer(timerData);
                configurable.OnConfigure();
            }
References IuvoUnity.DataStructs.Timer.ConfigureTimer(), IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.DataStructs.Timer.OnConfigure(), and timerData.
Referenced by IuvoUnity.IuvoTime.TimerFactory.Create().
OnEnable()
void IuvoUnity.Configurations.TimerConfiguration.OnEnable () private
            {
                if (string.IsNullOrEmpty(configName))
                {
                    configName = "TimerConfiguration";
                }
            }
References IuvoUnity.Configurations.BaseConfig< T >.configName.
PrintInfo()
override void IuvoUnity.Configurations.TimerConfiguration.PrintInfo () virtual
Reimplemented from IuvoUnity.Configurations.BaseConfig< T >.
            {
                base.PrintInfo();
                IuvoDebug.DebugLog(string.Concat(" - Activity Mode: ", timerData.activityMode.ToString()));
                IuvoDebug.DebugLog(string.Concat(" - Tick Method: ", timerData.tickMethod.ToString()));
                IuvoDebug.DebugLog(string.Concat(" - Duration: ", timerData.duration.ToString()));
                IuvoDebug.DebugLog(string.Concat(" - Elapsed Time: ", timerData.elapsedTime.ToString()));
                IuvoDebug.DebugLog(string.Concat(" - Remaining Time: ", timerData.remainingTime.ToString()));
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), and timerData.
Reconfigure()
override void IuvoUnity.Configurations.TimerConfiguration.Reconfigure (Timer reconfigurable)
            {
                if (reconfigurable == null)
                {
                    IuvoDebug.DebugLogError("Configurable Timer is null.");
                    return;
                }
                base.Reconfigure(reconfigurable);
                reconfigurable.ConfigureTimer(timerData);
                reconfigurable.OnReconfigure();
            }
References IuvoUnity.DataStructs.Timer.ConfigureTimer(), IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.DataStructs.Timer.OnReconfigure(), and timerData.
Member Data Documentation
timerData
TimerData IuvoUnity.Configurations.TimerConfiguration.timerData
Referenced by Configure(), PrintInfo(), and Reconfigure().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Configurations/TimerConfiguration.cs