Iuvo Unity: IuvoUnity.IuvoPhysics.RayCastData Class Reference
IuvoUnity.IuvoPhysics.RayCastData Class Reference
Public Attributes
Vector3 checkOrigin = Vector3.zero
float distanceToCheck = 1.25f
Vector3 directionToCheck = Vector3.down
bool isTouching = false
Ray ray = new Ray()
RaycastHit hit = new RaycastHit()
LayerMask layerMask = new LayerMask()
Private Member Functions
RayCastData ()
Constructor & Destructor Documentation
RayCastData()
IuvoUnity.IuvoPhysics.RayCastData.RayCastData () private
            {
                checkOrigin = Vector3.zero;
                distanceToCheck = 1.25f;
                directionToCheck = Vector3.down;
                isTouching = false;
                ray = new Ray(checkOrigin, directionToCheck);
                hit = new RaycastHit();
                layerMask = LayerMask.GetMask("Default");
            }
References checkOrigin, directionToCheck, distanceToCheck, hit, isTouching, layerMask, and ray.
Member Data Documentation
checkOrigin
Vector3 IuvoUnity.IuvoPhysics.RayCastData.checkOrigin = Vector3.zero
Referenced by RayCastData().
directionToCheck
Vector3 IuvoUnity.IuvoPhysics.RayCastData.directionToCheck = Vector3.down
Referenced by RayCastData().
distanceToCheck
float IuvoUnity.IuvoPhysics.RayCastData.distanceToCheck = 1.25f
Referenced by RayCastData().
hit
RaycastHit IuvoUnity.IuvoPhysics.RayCastData.hit = new RaycastHit()
Referenced by RayCastData().
isTouching
bool IuvoUnity.IuvoPhysics.RayCastData.isTouching = false
Referenced by RayCastData().
layerMask
LayerMask IuvoUnity.IuvoPhysics.RayCastData.layerMask = new LayerMask()
Referenced by RayCastData().
ray
Ray IuvoUnity.IuvoPhysics.RayCastData.ray = new Ray()
Referenced by RayCastData().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Physics/RayCaster.cs