Iuvo Unity: IuvoUnity.StateMachines.CSM.ConditionalStateMachine Class Reference
IuvoUnity.StateMachines.CSM.ConditionalStateMachine Class Reference
Public Member Functions
bool ForcePrevState ()
void SetForcePrevState (bool value)
bool ForceDefaultState ()
void SetForceDefaultState (bool value)
bool IsInState (ConditionalState state)
bool WasInState (ConditionalState state)
bool IsInState (string stateName)
void Awake ()
void Start ()
virtual void Update ()
virtual void FixedUpdate ()
virtual void LateUpdate ()
virtual bool TryChangeState (ConditionalState newState)
virtual bool ChangeState (ConditionalState newState, bool canEnterNew)
Attempts to change to a new state, handling all conditions and events. Interrupt->Exit->Enter sequence is followed if all conditions are met.
Public Attributes
ConditionalState currentState
ConditionalState defaultState
ConditionalState previousState
List< ConditionalState > States = new List<ConditionalState>()
Queue< ConditionalState > History = new Queue<ConditionalState>()
Private Member Functions
void AddToHistory (ConditionalState state)
void HandleContinue (ConditionalStateMachineUpdateMode mode)
void HandleFallbackLogic ()
Private Attributes
int historySize = 10
bool forceEnterPreviousState = true
bool forceEnterDefaultState = false
Member Function Documentation
AddToHistory()
void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.AddToHistory (ConditionalState state) private
                {
                    if (state != null)
                    {
                        History.Enqueue(state);
                        if (History.Count > historySize) History.Dequeue();
                    }
                }
References History, and historySize.
Referenced by ChangeState(), and HandleFallbackLogic().
Awake()
void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.Awake ()
                {
                    if (defaultState == null && States.Count > 0)
                    {
                        defaultState = States[0];
                        IuvoDebug.DebugLogWarning("Default state not set. Assigning first state in States list as default.");
                    }
                    else if (States.Count == 0)
                    {
                        IuvoDebug.DebugLogError("No states defined in the state machine. Please add states to the States list.");
                    }
                }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), defaultState, and States.
ChangeState()
virtual bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.ChangeState (ConditionalState newState, bool canEnterNew) virtual
Attempts to change to a new state, handling all conditions and events. Interrupt->Exit->Enter sequence is followed if all conditions are met.
Parameters
newState
                {
                    if (newState == null || newState == currentState)
                    {
                        IuvoDebug.DebugLogWarning("State Transition Denied: New state is null or same as current state.");
                        return false;
                    }
                    if (currentState == null)
                    {
                        if (canEnterNew)
{
                            currentState = newState;
                            currentState.OnEnter.Invoke(this);
                            AddToHistory(currentState);
                            return true;
                        }
                        else
{
                            IuvoDebug.DebugLogWarning($"Cannot enter state {newState.stateName} due to unmet enter conditions.");
                            return false;
                        }
                    }
                    if (!currentState.CanInterrupt(this))
                    {
                        IuvoDebug.DebugLogWarning($"Cannot interrupt {currentState.stateName} with {newState.stateName} due to unmet interrupt conditions.");
                        return false;
                    }
                    if (!canEnterNew)
                    {
                        IuvoDebug.DebugLogWarning($"Cannot enter {newState.stateName} due to unmet enter conditions.");
                        return false;
                    }
                    if (!currentState.CanExit(this))
                    {
                        IuvoDebug.DebugLogWarning($"Cannot exit from {currentState.stateName} to {newState.stateName} due to unmet exit conditions.");
                        return false;
                    }
                    currentState.OnInterrupt.Invoke(this);
                    IuvoDebug.DebugLog($"{currentState.stateName} is being interrupted by {newState.stateName}.");
                    currentState.OnExit.Invoke(this);
                    IuvoDebug.DebugLog($"{currentState.stateName} exited successfully.");
                    IuvoDebug.DebugLog($"Transitioning from {currentState.stateName} to {newState.stateName}.");
                    previousState = currentState;
                    currentState = newState;
                    AddToHistory(currentState);
                    if (canEnterNew)
                    {
                        currentState.OnEnter.Invoke(this);
                    }
                    else
                    {
                        HandleFallbackLogic();
                        return false; // Fallback logic handled, return false to indicate transition failure
                    }
                    return true;
                }
References AddToHistory(), currentState, IuvoUnity.Debug.IuvoDebug.DebugLog(), IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), HandleFallbackLogic(), and previousState.
Referenced by Start(), and TryChangeState().
FixedUpdate()
virtual void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.FixedUpdate () virtual
Reimplemented in IuvoUnity.StateMachines.CSM.ConditionalHumanoidStateMachine.
=> HandleContinue(ConditionalStateMachineUpdateMode.FixedUpdate);
ForceDefaultState()
bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.ForceDefaultState ()
=> forceEnterDefaultState;
References forceEnterDefaultState.
ForcePrevState()
bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.ForcePrevState ()
=> forceEnterPreviousState;
References forceEnterPreviousState.
HandleContinue()
void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.HandleContinue (ConditionalStateMachineUpdateMode mode) private
                {
                    if (currentState != null && currentState.updateMode == mode)
                    {
                        if (currentState.CanContinue(this))
                            currentState.OnContinue?.Invoke(this);
                        else
                            IuvoDebug.DebugLogWarning(
                                $"Cannot continue state {currentState.stateName} due to unmet conditions.");
                    }
                }
References currentState, and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
HandleFallbackLogic()
void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.HandleFallbackLogic () private
                {
                    IuvoDebug.DebugLogWarning($"Cannot re-enter previous state {previousState.stateName} due to unmet enter conditions.");
                    if (forceEnterPreviousState && previousState != null)
                    {
                        IuvoDebug.DebugLogWarning($"Forcing entry into previous state {previousState.stateName}.");
                        currentState = previousState;
                        AddToHistory(currentState);
                        currentState.OnEnter.Invoke(this);
                    }
                    else if (forceEnterDefaultState && defaultState != null)
                    {
                        IuvoDebug.DebugLogWarning($"Forcing entry into default state {defaultState.stateName}.");
                        currentState = defaultState;
                        AddToHistory(currentState);
                        currentState.OnEnter.Invoke(this);
                    }
                    else
                    {
                        IuvoDebug.DebugLogWarning("No valid state to revert to, remaining in current state.");
                    }
                }
References AddToHistory(), currentState, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), defaultState, forceEnterDefaultState, forceEnterPreviousState, and previousState.
Referenced by ChangeState().
IsInState() [1/2]
bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.IsInState (ConditionalState state)
=> currentState == state;
References currentState.
IsInState() [2/2]
bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.IsInState (string stateName)
=> currentState != null && currentState.stateName == stateName;
References currentState.
LateUpdate()
virtual void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.LateUpdate () virtual
=> HandleContinue(ConditionalStateMachineUpdateMode.LateUpdate);
SetForceDefaultState()
void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.SetForceDefaultState (bool value)
                {
                    if (forceEnterPreviousState)
                    {
                        IuvoDebug.DebugLogError("Cannot force default state when previous state is forced. Please disable forceEnterPrevState first.");
                        return;
                    }
                    forceEnterDefaultState = value;
                }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), forceEnterDefaultState, and forceEnterPreviousState.
SetForcePrevState()
void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.SetForcePrevState (bool value)
                {
                    if (forceEnterDefaultState)
                    {
                        IuvoDebug.DebugLogError("Cannot force previous state when default state is forced. Please disable forceEnterDefaultState first.");
                        return;
                    }
                    forceEnterPreviousState = value;
                }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), forceEnterDefaultState, and forceEnterPreviousState.
Start()
void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.Start ()
                {
                    currentState = null;
                    previousState = null;
                    ChangeState(defaultState, true);
                }
References ChangeState(), currentState, defaultState, and previousState.
TryChangeState()
virtual bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.TryChangeState (ConditionalState newState) virtual
                {
                    if (newState != null)
                    {
                        bool canEnterNew = newState.CanEnter(this);
                        return ChangeState(newState, canEnterNew);
                    }
                    else
                    {
                        IuvoDebug.DebugLogWarning("State Transition Denied Due To Unmet Conditions.");
                        return false;
                    }
                }
References IuvoUnity.StateMachines.CSM.ConditionalState.CanEnter(), ChangeState(), and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
Update()
virtual void IuvoUnity.StateMachines.CSM.ConditionalStateMachine.Update () virtual
Reimplemented in IuvoUnity.StateMachines.CSM.ConditionalHumanoidStateMachine.
=> HandleContinue(ConditionalStateMachineUpdateMode.Update);
WasInState()
bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.WasInState (ConditionalState state)
=> previousState == state;
References previousState.
Member Data Documentation
currentState
ConditionalState IuvoUnity.StateMachines.CSM.ConditionalStateMachine.currentState
Referenced by ChangeState(), HandleContinue(), HandleFallbackLogic(), IsInState(), IsInState(), and Start().
defaultState
ConditionalState IuvoUnity.StateMachines.CSM.ConditionalStateMachine.defaultState
Referenced by Awake(), HandleFallbackLogic(), and Start().
forceEnterDefaultState
bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.forceEnterDefaultState = false private
Referenced by ForceDefaultState(), HandleFallbackLogic(), SetForceDefaultState(), and SetForcePrevState().
forceEnterPreviousState
bool IuvoUnity.StateMachines.CSM.ConditionalStateMachine.forceEnterPreviousState = true private
Referenced by ForcePrevState(), HandleFallbackLogic(), SetForceDefaultState(), and SetForcePrevState().
History
Queue<ConditionalState> IuvoUnity.StateMachines.CSM.ConditionalStateMachine.History = new Queue<ConditionalState>()
Referenced by AddToHistory().
historySize
int IuvoUnity.StateMachines.CSM.ConditionalStateMachine.historySize = 10 private
Referenced by AddToHistory().
previousState
ConditionalState IuvoUnity.StateMachines.CSM.ConditionalStateMachine.previousState
Referenced by ChangeState(), HandleFallbackLogic(), Start(), and WasInState().
States
List<ConditionalState> IuvoUnity.StateMachines.CSM.ConditionalStateMachine.States = new List<ConditionalState>()
Referenced by Awake().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/StateMachine/ConditionalStateMachine/Machines/ConditionalStateMachine.cs