Iuvo Unity: IuvoUnity.Editor.InterfaceReferenceDrawer Class Reference
IuvoUnity.Editor.InterfaceReferenceDrawer Class Reference
Public Member Functions
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
Static Private Member Functions
static InterfaceArgs GetArguments (FieldInfo fieldInfo)
static void ValidateAndAssignObject (SerializedProperty property, Object targetObject, string componentNameOrType, string interfaceName=null)
Static Private Attributes
const string UnderlyingValueFieldName = "underlyingValue"
Member Function Documentation
GetArguments()
InterfaceArgs IuvoUnity.Editor.InterfaceReferenceDrawer.GetArguments (FieldInfo fieldInfo) static private
            {
                Type objectType = null, interfaceType = null;
                Type fieldType = fieldInfo.FieldType;
                bool TryGetTypesFromInterfaceReference(Type type, out Type objType, out Type interfType)
                {
                    objType = interfType = null;
                    if (type?.IsGenericType != true) return false;
                    var genericType = type.GetGenericTypeDefinition();
                    if (genericType == typeof(InterfaceReference<>)) type = type.BaseType;
                    if (type?.GetGenericTypeDefinition() == typeof(InterfaceReference<,>))
                    {
                        var types = type.GetGenericArguments();
                        interfType = types[0];
                        objType = types[1];
                        return true;
                    }
                    return false;
                }
                void GetTypesFromList(Type type, out Type objType, out Type interfType)
                {
                    objType = interfType = null;
                    var listInterface = type.GetInterfaces()
                        .FirstOrDefault(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IList<>));
                    if (listInterface != null)
                    {
                        var elementType = listInterface.GetGenericArguments()[0];
                        TryGetTypesFromInterfaceReference(elementType, out objType, out interfType);
                    }
                }
                if (!TryGetTypesFromInterfaceReference(fieldType, out objectType, out interfaceType))
                {
                    GetTypesFromList(fieldType, out objectType, out interfaceType);
                }
                return new InterfaceArgs(objectType, interfaceType);
            }
Referenced by OnGUI().
OnGUI()
override void IuvoUnity.Editor.InterfaceReferenceDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
            {
                var underlyingProperty = property.FindPropertyRelative(UnderlyingValueFieldName);
                var args = GetArguments(fieldInfo);
                EditorGUI.BeginProperty(position, label, property);
                var assignedObject = EditorGUI.ObjectField(position, label, underlyingProperty.objectReferenceValue, typeof(Object), true);
                if (assignedObject != null)
                {
                    if (assignedObject is GameObject gameObject)
                    {
                        ValidateAndAssignObject(underlyingProperty, gameObject.GetComponent(args.InterfaceType), gameObject.name, args.InterfaceType.Name);
                    }
                    else
                    {
                        ValidateAndAssignObject(underlyingProperty, assignedObject, args.InterfaceType.Name);
                    }
                }
                else
                {
                    underlyingProperty.objectReferenceValue = null;
                }
                EditorGUI.EndProperty();
            }
References GetArguments(), UnderlyingValueFieldName, and ValidateAndAssignObject().
ValidateAndAssignObject()
void IuvoUnity.Editor.InterfaceReferenceDrawer.ValidateAndAssignObject (SerializedProperty property, Object targetObject, string componentNameOrType, string interfaceName = null) static private
            {
                if (targetObject != null)
                {
                    property.objectReferenceValue = targetObject;
                }
                else
                {
                    UnityEngine.Debug.LogWarning(
                        $@"The {(interfaceName != null
                            ? $"GameObject '{componentNameOrType}'"
                            : $"assigned object")} does not have a component that implements '{componentNameOrType}.'"
                        );
                    property.objectReferenceValue = null;
Referenced by OnGUI().
Member Data Documentation
UnderlyingValueFieldName
const string IuvoUnity.Editor.InterfaceReferenceDrawer.UnderlyingValueFieldName = "underlyingValue" static private
Referenced by OnGUI().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Editor/InterfaceReferenceDrawer.cs