Iuvo Unity: IuvoUnity.Editor.InterfaceReferenceUtils Class Reference
IuvoUnity.Editor.InterfaceReferenceUtils Class Reference
Static Public Member Functions
static void OnGUI (Rect position, SerializedProperty property, GUIContent label, InterfaceArgs args)
Static Private Member Functions
static void DrawInterFaceNameLabel (Rect position, string displayString, int controlID)
static void InitializeStyleIfNeeded ()
Static Private Attributes
static GUIStyle labelStyle
Member Function Documentation
DrawInterFaceNameLabel()
void IuvoUnity.Editor.InterfaceReferenceUtils.DrawInterFaceNameLabel (Rect position, string displayString, int controlID) static private
            {
                if (Event.current.type == EventType.Repaint)
                {
                    const int additionalLeftWidth = 3;
                    const int verticalIndent = 1;
                    var content = EditorGUIUtility.TrTextContent(displayString);
                    var size = labelStyle.CalcSize(content);
                    var labelPos = position;
                    labelPos.width = size.x + additionalLeftWidth;
                    labelPos.x += position.width - labelPos.width - 18;
                    labelPos.height -= verticalIndent * 2;
                    labelPos.y += verticalIndent;
                    labelStyle.Draw(labelPos, EditorGUIUtility.TrTextContent(displayString), controlID, DragAndDrop.activeControlID == controlID, false);
                }
            }
References labelStyle.
Referenced by OnGUI().
InitializeStyleIfNeeded()
void IuvoUnity.Editor.InterfaceReferenceUtils.InitializeStyleIfNeeded () static private
            {
                if (labelStyle != null) return;
                var style = new GUIStyle(EditorStyles.label)
                {
                    font = EditorStyles.objectField.font,
                    fontSize = EditorStyles.objectField.fontSize,
                    fontStyle = EditorStyles.objectField.fontStyle,
                    alignment = TextAnchor.MiddleRight,
                    padding = new RectOffset(0, 2, 0, 0)
                };
                labelStyle = style;
            }
References labelStyle.
Referenced by OnGUI().
OnGUI()
void IuvoUnity.Editor.InterfaceReferenceUtils.OnGUI (Rect position, SerializedProperty property, GUIContent label, InterfaceArgs args) static
            {
                InitializeStyleIfNeeded();
                var controlID = GUIUtility.GetControlID(FocusType.Passive) - 1;
                var isHovering = position.Contains(Event.current.mousePosition);
                var displayString = property.objectReferenceValue == null || isHovering ? $"({args.InterfaceType.Name})" : "*";
                DrawInterFaceNameLabel(position, displayString, controlID);
            }
References DrawInterFaceNameLabel(), and InitializeStyleIfNeeded().
Member Data Documentation
labelStyle
GUIStyle IuvoUnity.Editor.InterfaceReferenceUtils.labelStyle static private
Referenced by DrawInterFaceNameLabel(), and InitializeStyleIfNeeded().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Editor/InterfaceReferenceUtils.cs