Iuvo Unity: IuvoUnity.BaseClasses.ECS.IuvoSystem Class Reference
IuvoUnity.BaseClasses.ECS.IuvoSystem Class Reference abstract
Public Member Functions
virtual void Initialize (IuvoEntityRegistry entityRegistry)
void Update (float deltaTime)
virtual void LateUpdate (float deltaTime)
void RefreshEntityList (IuvoEntityRegistry entityRegistry)
virtual void Shutdown ()
Protected Member Functions
bool EntityMatchesRequirements (IuvoEntity entity)
Protected Attributes
IuvoEntityRegistry registry
List< IuvoEntity > applicableEntities = new List<IuvoEntity>()
Properties
Type[] RequiredComponents [get]
Member Function Documentation
EntityMatchesRequirements()
bool IuvoUnity.BaseClasses.ECS.IuvoSystem.EntityMatchesRequirements (IuvoEntity entity) protected
                {
                    foreach (var type in RequiredComponents)
                    {
                        if (!entity._ComponentManager.TryGetComponent<IuvoComponentBase>(out var thing))
                            return false;
                    }
                    return true;
                }
References RequiredComponents.
Initialize()
virtual void IuvoUnity.BaseClasses.ECS.IuvoSystem.Initialize (IuvoEntityRegistry entityRegistry) virtual
                {
                    registry = entityRegistry;
                    // Auto-register for applicable entities
                    RefreshEntityList(entityRegistry);
                }
References RefreshEntityList(), and registry.
LateUpdate()
virtual void IuvoUnity.BaseClasses.ECS.IuvoSystem.LateUpdate (float deltaTime) virtual
{ }
RefreshEntityList()
void IuvoUnity.BaseClasses.ECS.IuvoSystem.RefreshEntityList (IuvoEntityRegistry entityRegistry)
                {
                }
Referenced by Initialize().
Shutdown()
virtual void IuvoUnity.BaseClasses.ECS.IuvoSystem.Shutdown () virtual
                {
                    applicableEntities.Clear();
                }
References applicableEntities.
Update()
void IuvoUnity.BaseClasses.ECS.IuvoSystem.Update (float deltaTime) abstract
Member Data Documentation
applicableEntities
List<IuvoEntity> IuvoUnity.BaseClasses.ECS.IuvoSystem.applicableEntities = new List<IuvoEntity>() protected
Referenced by Shutdown().
registry
IuvoEntityRegistry IuvoUnity.BaseClasses.ECS.IuvoSystem.registry protected
Referenced by Initialize().
Property Documentation
RequiredComponents
Type [] IuvoUnity.BaseClasses.ECS.IuvoSystem.RequiredComponents get abstract protected
{ get; }
Referenced by EntityMatchesRequirements().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ECS/Systems/IuvoSystemBase.cs