Iuvo Unity: IuvoUnity.DataStructs.EventContext Class Reference
IuvoUnity.DataStructs.EventContext Class Reference
Public Member Functions
EventContext ()
bool TryGetEvent (ContextKey_EVENT key, out FlexibleEvent flexibleEvent)
void Clear (ContextKey_EVENT key)
void ClearAll ()
void AddListener (ContextKey_EVENT key, System.Action listener)
void RemoveListener (ContextKey_EVENT key, System.Action listener)
void AddUnityListener (ContextKey_EVENT key, UnityAction listener)
void RemoveUnityListener (ContextKey_EVENT key, UnityAction listener)
FlexibleEvent GetEvent (ContextKey_EVENT key)
bool HasEvent (ContextKey_EVENT key)
void Dispose ()
Public Attributes
readonly Dictionary< ContextKey_EVENT, FlexibleEvent > events = new Dictionary<ContextKey_EVENT, FlexibleEvent>()
Constructor & Destructor Documentation
EventContext()
IuvoUnity.DataStructs.EventContext.EventContext ()
            {
                foreach (ContextKey_EVENT key in System.Enum.GetValues(typeof(ContextKey_EVENT)))
                {
                    events[key] = new FlexibleEvent();
                }
            }
References events.
Member Function Documentation
AddListener()
void IuvoUnity.DataStructs.EventContext.AddListener (ContextKey_EVENT key, System.Action listener)
            {
                if (TryGetEvent(key, out var flexibleEvent))
                {
                    flexibleEvent.AddListener(listener);
                }
            }
References TryGetEvent().
AddUnityListener()
void IuvoUnity.DataStructs.EventContext.AddUnityListener (ContextKey_EVENT key, UnityAction listener)
            {
                if (TryGetEvent(key, out var flexibleEvent))
                {
                    flexibleEvent.AddUnityListener(listener);
                }
            }
References TryGetEvent().
Clear()
void IuvoUnity.DataStructs.EventContext.Clear (ContextKey_EVENT key)
            {
                if (TryGetEvent(key, out var flexibleEvent))
                {
                    flexibleEvent.RemoveAllFlexibleEventListeners();
                }
            }
References TryGetEvent().
Referenced by ClearAll().
ClearAll()
void IuvoUnity.DataStructs.EventContext.ClearAll ()
            {
                foreach (var key in events.Keys)
                {
                    Clear(key);
                }
            }
References Clear(), and events.
Referenced by Dispose().
Dispose()
void IuvoUnity.DataStructs.EventContext.Dispose ()
Implements IuvoUnity.Interfaces.IContext.
            {
                ClearAll();
            }
References ClearAll().
GetEvent()
FlexibleEvent IuvoUnity.DataStructs.EventContext.GetEvent (ContextKey_EVENT key)
            {
                if (TryGetEvent(key, out var flexibleEvent))
                {
                    return flexibleEvent;
                }
                return null;
            }
References TryGetEvent().
HasEvent()
bool IuvoUnity.DataStructs.EventContext.HasEvent (ContextKey_EVENT key)
            {
                return events.ContainsKey(key);
            }
References events.
RemoveListener()
void IuvoUnity.DataStructs.EventContext.RemoveListener (ContextKey_EVENT key, System.Action listener)
            {
                if (TryGetEvent(key, out var flexibleEvent))
                {
                    flexibleEvent.RemoveListener(listener);
                }
            }
References TryGetEvent().
RemoveUnityListener()
void IuvoUnity.DataStructs.EventContext.RemoveUnityListener (ContextKey_EVENT key, UnityAction listener)
            {
                if (TryGetEvent(key, out var flexibleEvent))
                {
                    flexibleEvent.RemoveUnityListener(listener);
                }
            }
References TryGetEvent().
TryGetEvent()
bool IuvoUnity.DataStructs.EventContext.TryGetEvent (ContextKey_EVENT key, out FlexibleEvent flexibleEvent)
            {
                if (events.TryGetValue(key, out flexibleEvent))
                {
                    return true;
                }
                UnityEngine.Debug.LogError($"Event {key} not found in PlayerEventContext.");
                return false;
            }
References events.
Referenced by AddListener(), AddUnityListener(), Clear(), GetEvent(), RemoveListener(), and RemoveUnityListener().
Member Data Documentation
events
readonly Dictionary<ContextKey_EVENT, FlexibleEvent> IuvoUnity.DataStructs.EventContext.events = new Dictionary<ContextKey_EVENT, FlexibleEvent>()
Referenced by ClearAll(), EventContext(), HasEvent(), and TryGetEvent().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/PlayerEventContext.cs