Iuvo Unity: IuvoUnity.Editor.ExpandableAttributeDrawer Class Reference
IuvoUnity.Editor.ExpandableAttributeDrawer Class Reference
Public Member Functions
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
Private Member Functions
void DrawExpandedInspector (Object target, ref Rect position)
float GetExpandedHeight (SerializedProperty property)
string GetFoldoutKey (SerializedProperty property)
Static Private Attributes
static readonly Dictionary< string, bool > _foldouts = new Dictionary<string, bool>()
static readonly HashSet< int > _drawStack = new HashSet<int>()
Member Function Documentation
DrawExpandedInspector()
void IuvoUnity.Editor.ExpandableAttributeDrawer.DrawExpandedInspector (Object target, ref Rect position) private
            {
                SerializedObject serializedObject = new SerializedObject(target);
                SerializedProperty iterator = serializedObject.GetIterator();
                bool enterChildren = true;
                while (iterator.NextVisible(enterChildren))
                {
                    if (iterator.name == "m_Script") continue;
                    float height = EditorGUI.GetPropertyHeight(iterator, true);
                    Rect propRect = new Rect(position.x, position.y, position.width, height);
                    EditorGUI.PropertyField(propRect, iterator, true);
                    position.y += height + EditorGUIUtility.standardVerticalSpacing;
                    enterChildren = false;
                }
                serializedObject.ApplyModifiedProperties();
            }
Referenced by OnGUI().
GetExpandedHeight()
float IuvoUnity.Editor.ExpandableAttributeDrawer.GetExpandedHeight (SerializedProperty property) private
            {
                float height = EditorGUIUtility.singleLineHeight + 6; // object field + spacing
                SerializedObject serializedObject = new SerializedObject(property.objectReferenceValue);
                SerializedProperty iterator = serializedObject.GetIterator();
                bool enterChildren = true;
                while (iterator.NextVisible(enterChildren))
                {
                    if (iterator.name == "m_Script") continue;
                    height += EditorGUI.GetPropertyHeight(iterator, true) + EditorGUIUtility.standardVerticalSpacing;
                    enterChildren = false;
                }
                height += 6; // padding inside box
                return height;
            }
Referenced by GetPropertyHeight(), and OnGUI().
GetFoldoutKey()
string IuvoUnity.Editor.ExpandableAttributeDrawer.GetFoldoutKey (SerializedProperty property) private
            {
                return $"{property.serializedObject.targetObject.GetInstanceID()}_{property.propertyPath}";
            }
Referenced by GetPropertyHeight(), and OnGUI().
GetPropertyHeight()
override float IuvoUnity.Editor.ExpandableAttributeDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
            {
                float height = EditorGUIUtility.singleLineHeight;
                if (property.objectReferenceValue == null)
                    return height;
                string key = GetFoldoutKey(property);
                if (!_foldouts.TryGetValue(key, out bool expanded) || !expanded)
                    return height;
                height = GetExpandedHeight(property);
                return height;
            }
References _foldouts, GetExpandedHeight(), and GetFoldoutKey().
OnGUI()
override void IuvoUnity.Editor.ExpandableAttributeDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
            {
                if (property.propertyType != SerializedPropertyType.ObjectReference)
                {
                    EditorGUI.PropertyField(position, property, label, true);
                    return;
                }
                // Draw object field
                position.height = EditorGUIUtility.singleLineHeight;
                property.objectReferenceValue = EditorGUI.ObjectField(
                    position, label, property.objectReferenceValue, fieldInfo.FieldType, false
                );
                if (property.objectReferenceValue == null)
                    return;
                string key = GetFoldoutKey(property);
                if (!_foldouts.ContainsKey(key)) _foldouts[key] = false;
                // Foldout arrow
                Rect foldoutRect = position;
                foldoutRect.xMin += EditorGUIUtility.labelWidth;
                _foldouts[key] = EditorGUI.Foldout(foldoutRect, _foldouts[key], GUIContent.none, true);
                if (_foldouts[key])
                {
                    int objId = property.objectReferenceValue.GetInstanceID();
                    if (_drawStack.Contains(objId))
                    {
                        // Prevent infinite recursion
                        position.y += EditorGUIUtility.singleLineHeight + EditorGUIUtility.standardVerticalSpacing;
                        EditorGUI.LabelField(position, "<Recursive Reference Detected>");
                        return;
                    }
                    _drawStack.Add(objId);
                    // Draw boxed background
                    EditorGUI.indentLevel++;
                    Rect boxRect = new Rect(position.x, position.y + EditorGUIUtility.singleLineHeight + 2,
                        position.width, GetExpandedHeight(property) - EditorGUIUtility.singleLineHeight - 4);
                    GUI.Box(boxRect, GUIContent.none, EditorStyles.helpBox);
                    // Offset content inside box
                    Rect innerPosition = new Rect(position.x + 4, position.y + EditorGUIUtility.singleLineHeight + 6,
                        position.width - 8, EditorGUIUtility.singleLineHeight);
                    DrawExpandedInspector(property.objectReferenceValue, ref innerPosition);
                    EditorGUI.indentLevel--;
                    _drawStack.Remove(objId);
                }
            }
References _drawStack, _foldouts, DrawExpandedInspector(), GetExpandedHeight(), and GetFoldoutKey().
Member Data Documentation
_drawStack
readonly HashSet<int> IuvoUnity.Editor.ExpandableAttributeDrawer._drawStack = new HashSet<int>() static private
Referenced by OnGUI().
_foldouts
readonly Dictionary<string, bool> IuvoUnity.Editor.ExpandableAttributeDrawer._foldouts = new Dictionary<string, bool>() static private
Referenced by GetPropertyHeight(), and OnGUI().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Editor/ExpandableAttributeDrawer.cs