Iuvo Unity: IuvoUnity.Extensions.GameObjectExtensions Class Reference
IuvoUnity.Extensions.GameObjectExtensions Class Reference
Static Public Member Functions
static void SetLayerRecursively (this GameObject obj, int layer)
Recursively sets the layer of a GameObject and all of its children.
static T GetOrAdd< T > (this GameObject gameObject)
Gets the component of type T if its exists otherwise adds it to the GameObject.
static T OrNull< T > (this T obj)
Returns the object if it is not null, otherwise returns null.
static GameObject FindChildByName (this GameObject gameObject, string childName)
Finds a child GameObject by its name.
static GameObject FindChildByTag (this GameObject gameObject, string tag)
Finds a child GameObject by its tag.
static bool HasComponent< T > (this GameObject gameObject)
Checks if a GameObject has a component of type T.
static void LogComponents< T > (this GameObject gameObject)
Logs all components of type T attached to the GameObject.
static void LogComponentsInChildren< T > (this GameObject gameObject)
Logs all components of type T attached to the GameObject and its children.
static bool HasRigidbody (this GameObject gameObject)
Checks if the GameObject has a Rigidbody component.
static void EnableComponent< T > (this GameObject gameObject)
Enables the specified component on the GameObject.
static void DisableComponent< T > (this GameObject gameObject)
Disables the specified component on the GameObject.
static void SetMaterialColor (this GameObject gameObject, Color color)
Sets the material color of the GameObject's Renderer.
static bool IsCollidingWith (this GameObject gameObject, GameObject other)
Checks if the GameObject is colliding with another GameObject.
static void ScaleStaticChildrenWithMesh (this GameObject parent, Vector3 scale, bool includeParent=false)
Scales all static children with MeshFilter components by the given scale.
static void ScaleNonStaticChildrenWithMesh (this GameObject parent, Vector3 scale, bool includeParent=false)
Scales all non-static children with MeshFilter components by the given scale.
static Collider[] GetAllColliders (this GameObject gameObject)
Gets all colliders attached to a GameObject and its children as an array.
Member Function Documentation
DisableComponent< T >()
void IuvoUnity.Extensions.GameObjectExtensions.DisableComponent< T > (this GameObject gameObject) static
Disables the specified component on the GameObject.
Template Parameters
T The type of component to disable.
Parameters
gameObject The GameObject to disable the component on.
Type Constraints
T : Behaviour
                                                                                       : Behaviour
            {
                T component = gameObject.GetComponent<T>();
                if (component != null)
                {
                    component.enabled = false;
                }
            }
EnableComponent< T >()
void IuvoUnity.Extensions.GameObjectExtensions.EnableComponent< T > (this GameObject gameObject) static
Enables the specified component on the GameObject.
Template Parameters
T The type of component to enable.
Parameters
gameObject The GameObject to enable the component on.
Type Constraints
T : Behaviour
                                                                                      : Behaviour
            {
                T component = gameObject.GetComponent<T>();
                if (component != null)
                {
                    component.enabled = true;
                }
            }
FindChildByName()
GameObject IuvoUnity.Extensions.GameObjectExtensions.FindChildByName (this GameObject gameObject, string childName) static
Finds a child GameObject by its name.
Parameters
gameObject The parent GameObject.
childName The name of the child GameObject to find.
Returns
The child GameObject, or null if not found.
            {
                Transform childTransform = gameObject.transform.Find(childName);
                return childTransform != null ? childTransform.gameObject : null;
            }
FindChildByTag()
GameObject IuvoUnity.Extensions.GameObjectExtensions.FindChildByTag (this GameObject gameObject, string tag) static
Finds a child GameObject by its tag.
Parameters
gameObject The parent GameObject.
tag The tag to search for.
Returns
The first child GameObject with the given tag, or null if not found.
            {
                foreach (Transform child in gameObject.transform)
                {
                    if (child.CompareTag(tag))
                    {
                        return child.gameObject;
                    }
                }
                return null;
            }
GetAllColliders()
Collider[] IuvoUnity.Extensions.GameObjectExtensions.GetAllColliders (this GameObject gameObject) static
Gets all colliders attached to a GameObject and its children as an array.
Parameters
gameObject The GameObject to search for colliders.
Returns
An array of Colliders.
            {
                return gameObject.GetComponentsInChildren<Collider>().ToArray();
            }
GetOrAdd< T >()
T IuvoUnity.Extensions.GameObjectExtensions.GetOrAdd< T > (this GameObject gameObject) static
Gets the component of type T if its exists otherwise adds it to the GameObject.
Template Parameters
T The type of the component to get or add.
Parameters
gameObject The GameObject to get or add the component to.
Returns
The component of type T
Type Constraints
T : Component
                                                                            : Component
            {
                T component = gameObject.GetComponent<T>();
                if (!component) component = gameObject.AddComponent<T>();
                return component;
            }
HasComponent< T >()
bool IuvoUnity.Extensions.GameObjectExtensions.HasComponent< T > (this GameObject gameObject) static
Checks if a GameObject has a component of type T.
Template Parameters
T The type of the component to check for.
Parameters
gameObject The GameObject to check.
Returns
True if the component is present, otherwise false.
Type Constraints
T : Component
                                                                                   : Component
            {
                return gameObject.GetComponent<T>() != null;
            }
HasRigidbody()
bool IuvoUnity.Extensions.GameObjectExtensions.HasRigidbody (this GameObject gameObject) static
Checks if the GameObject has a Rigidbody component.
Parameters
gameObject The GameObject to check.
Returns
True if the GameObject has a Rigidbody, otherwise false.
            {
                return gameObject.GetComponent<Rigidbody>() != null;
            }
IsCollidingWith()
bool IuvoUnity.Extensions.GameObjectExtensions.IsCollidingWith (this GameObject gameObject, GameObject other) static
Checks if the GameObject is colliding with another GameObject.
Parameters
gameObject The GameObject to check.
other The other GameObject to check for collision with.
Returns
True if the GameObject is colliding with the other GameObject, otherwise false.
            {
                Collider collider = gameObject.GetComponent<Collider>();
                Collider otherCollider = other.GetComponent<Collider>();
                return collider != null && otherCollider != null && collider.bounds.Intersects(otherCollider.bounds);
            }
LogComponents< T >()
void IuvoUnity.Extensions.GameObjectExtensions.LogComponents< T > (this GameObject gameObject) static
Logs all components of type T attached to the GameObject.
Template Parameters
T The type of component to log.
Parameters
gameObject The GameObject whose components to log.
Type Constraints
T : Component
                                                                                    : Component
            {
                T[] components = gameObject.GetComponents<T>();
                foreach (T component in components)
                {
                    IuvoDebug.DebugLog(component.name);
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog().
LogComponentsInChildren< T >()
void IuvoUnity.Extensions.GameObjectExtensions.LogComponentsInChildren< T > (this GameObject gameObject) static
Logs all components of type T attached to the GameObject and its children.
Template Parameters
T The type of component to log.
Parameters
gameObject The GameObject whose components to log.
Type Constraints
T : Component
                                                                                              : Component
            {
                T[] components = gameObject.GetComponentsInChildren<T>();
                foreach (T component in components)
                {
                    IuvoDebug.DebugLog(component.name);
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog().
OrNull< T >()
T IuvoUnity.Extensions.GameObjectExtensions.OrNull< T > (this T obj) static
Returns the object if it is not null, otherwise returns null.
Template Parameters
T The type of object.
Parameters
obj The object to check.
Returns
The object or null if it's null.
Type Constraints
T : UnityEngine.Object
: UnityEngine.Object => (bool)obj ? obj : null;
ScaleNonStaticChildrenWithMesh()
void IuvoUnity.Extensions.GameObjectExtensions.ScaleNonStaticChildrenWithMesh (this GameObject parent, Vector3 scale, bool includeParent = false) static
Scales all non-static children with MeshFilter components by the given scale.
Parameters
parent The parent GameObject.
scale The scale factor to apply.
includeParent Whether to include the parent in the scaling.
            {
                if (parent == null)
                {
                    IuvoDebug.DebugLogError("Parent GameObject is null.");
                    return;
                }
                // Scale the children that are non-static and have a MeshFilter.
                foreach (Transform child in parent.transform)
                {
                    if (!child.gameObject.isStatic && child.GetComponent<MeshFilter>() != null)
                    {
                        child.localScale = Vector3.Scale(child.localScale, scale);
                    }
                }
                // Optionally scale the parent if it's non-static and meets the criteria.
                if (includeParent && !parent.isStatic && parent.GetComponent<MeshFilter>() != null)
                {
                    parent.transform.localScale = Vector3.Scale(parent.transform.localScale, scale);
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError().
ScaleStaticChildrenWithMesh()
void IuvoUnity.Extensions.GameObjectExtensions.ScaleStaticChildrenWithMesh (this GameObject parent, Vector3 scale, bool includeParent = false) static
Scales all static children with MeshFilter components by the given scale.
Parameters
parent The parent GameObject.
scale The scale factor to apply.
includeParent Whether to include the parent in the scaling.
            {
                if (parent == null)
                {
                    IuvoDebug.DebugLogError("Parent GameObject is null.");
                    return;
                }
                // Scale the children.
                foreach (Transform child in parent.transform)
                {
                    if (child.gameObject.isStatic && child.GetComponent<MeshFilter>() != null)
                    {
                        child.localScale = Vector3.Scale(child.localScale, scale);
                    }
                }
                // Scale the parent if specified and it meets the criteria.
                if (includeParent && parent.isStatic && parent.GetComponent<MeshFilter>() != null)
                {
                    parent.transform.localScale = Vector3.Scale(parent.transform.localScale, scale);
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError().
SetLayerRecursively()
void IuvoUnity.Extensions.GameObjectExtensions.SetLayerRecursively (this GameObject obj, int layer) static
Recursively sets the layer of a GameObject and all of its children.
Parameters
obj The GameObject to change the layer of.
layer The Layer to set.
            {
                obj.layer = layer;
                foreach (Transform child in obj.transform)
                {
                    child.gameObject.SetLayerRecursively(layer);
                }
            }
SetMaterialColor()
void IuvoUnity.Extensions.GameObjectExtensions.SetMaterialColor (this GameObject gameObject, Color color) static
Sets the material color of the GameObject's Renderer.
Parameters
gameObject The GameObject to set the material color for.
color The color to set.
            {
                Renderer renderer = gameObject.GetComponent<Renderer>();
                if (renderer != null)
                {
                    renderer.material.color = color;
                }
            }
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Extensions/GameObjectExtensions.cs