Iuvo Unity: IuvoUnity.Constants.ConstTag Class Reference
IuvoUnity.Constants.ConstTag Class Reference
Public Member Functions
ConstTag (TagType tagType, ApplicationTag appTag=ApplicationTag.NONE, GameTag gameTag=GameTag.NONE, UITag uiTag=UITag.NONE)
void AddTagType (TagType tagType)
void RemoveTagType (TagType tagType)
void AddAppTag (ApplicationTag tag)
void RemoveAppTag (ApplicationTag tag)
void AddGameTag (GameTag tag)
void RemoveGameTag (GameTag tag)
void AddUITag (UITag tag)
void RemoveUITag (UITag tag)
bool HasTagType (TagType type)
bool HasAppTag (ApplicationTag tag)
bool HasGameTag (GameTag tag)
bool HasUITag (UITag tag)
IReadOnlyList< TagType > GetTagTypes ()
IReadOnlyList< ApplicationTag > GetAppTags ()
IReadOnlyList< GameTag > GetGameTags ()
IReadOnlyList< UITag > GetUITags ()
Private Member Functions
ConstTag ()
Private Attributes
List< TagType > tagTypes = new List<TagType>()
List< ApplicationTag > appTags = new List<ApplicationTag>()
List< GameTag > gameTags = new List<GameTag>()
List< UITag > uiTags = new List<UITag>()
Constructor & Destructor Documentation
ConstTag() [1/2]
IuvoUnity.Constants.ConstTag.ConstTag () private
            {
                tagTypes.Add(TagType.NONE);
                appTags.Add(ApplicationTag.NONE);
                gameTags.Add(GameTag.NONE);
                uiTags.Add(UITag.NONE);
            }
References appTags, gameTags, tagTypes, and uiTags.
ConstTag() [2/2]
IuvoUnity.Constants.ConstTag.ConstTag (TagType tagType, ApplicationTag appTag = ApplicationTag::NONE, GameTag gameTag = GameTag::NONE, UITag uiTag = UITag::NONE)
            {
                tagTypes.Add(tagType);
                appTags.Add(appTag);
                gameTags.Add(gameTag);
                uiTags.Add(uiTag);
            }
References appTags, gameTags, tagTypes, and uiTags.
Member Function Documentation
AddAppTag()
void IuvoUnity.Constants.ConstTag.AddAppTag (ApplicationTag tag)
            {
                if (!appTags.Contains(tag))
                    appTags.Add(tag);
            }
References appTags.
AddGameTag()
void IuvoUnity.Constants.ConstTag.AddGameTag (GameTag tag)
            {
                if (!gameTags.Contains(tag))
                    gameTags.Add(tag);
            }
References gameTags.
AddTagType()
void IuvoUnity.Constants.ConstTag.AddTagType (TagType tagType)
            {
                if (!tagTypes.Contains(tagType))
                    tagTypes.Add(tagType);
            }
References tagTypes.
AddUITag()
void IuvoUnity.Constants.ConstTag.AddUITag (UITag tag)
            {
                if (!uiTags.Contains(tag))
                    uiTags.Add(tag);
            }
References uiTags.
GetAppTags()
IReadOnlyList< ApplicationTag > IuvoUnity.Constants.ConstTag.GetAppTags ()
=> appTags.AsReadOnly();
References appTags.
GetGameTags()
IReadOnlyList< GameTag > IuvoUnity.Constants.ConstTag.GetGameTags ()
=> gameTags.AsReadOnly();
References gameTags.
GetTagTypes()
IReadOnlyList< TagType > IuvoUnity.Constants.ConstTag.GetTagTypes ()
=> tagTypes.AsReadOnly();
References tagTypes.
GetUITags()
IReadOnlyList< UITag > IuvoUnity.Constants.ConstTag.GetUITags ()
=> uiTags.AsReadOnly();
References uiTags.
HasAppTag()
bool IuvoUnity.Constants.ConstTag.HasAppTag (ApplicationTag tag)
=> appTags.Contains(tag);
References appTags.
HasGameTag()
bool IuvoUnity.Constants.ConstTag.HasGameTag (GameTag tag)
=> gameTags.Contains(tag);
References gameTags.
HasTagType()
bool IuvoUnity.Constants.ConstTag.HasTagType (TagType type)
=> tagTypes.Contains(type);
References tagTypes.
HasUITag()
bool IuvoUnity.Constants.ConstTag.HasUITag (UITag tag)
=> uiTags.Contains(tag);
References uiTags.
RemoveAppTag()
void IuvoUnity.Constants.ConstTag.RemoveAppTag (ApplicationTag tag)
            {
                appTags.Remove(tag);
            }
References appTags.
RemoveGameTag()
void IuvoUnity.Constants.ConstTag.RemoveGameTag (GameTag tag)
            {
                gameTags.Remove(tag);
            }
References gameTags.
RemoveTagType()
void IuvoUnity.Constants.ConstTag.RemoveTagType (TagType tagType)
            {
                tagTypes.Remove(tagType);
            }
References tagTypes.
RemoveUITag()
void IuvoUnity.Constants.ConstTag.RemoveUITag (UITag tag)
            {
                uiTags.Remove(tag);
            }
References uiTags.
Member Data Documentation
appTags
List<ApplicationTag> IuvoUnity.Constants.ConstTag.appTags = new List<ApplicationTag>() private
Referenced by AddAppTag(), ConstTag(), ConstTag(), GetAppTags(), HasAppTag(), and RemoveAppTag().
gameTags
List<GameTag> IuvoUnity.Constants.ConstTag.gameTags = new List<GameTag>() private
Referenced by AddGameTag(), ConstTag(), ConstTag(), GetGameTags(), HasGameTag(), and RemoveGameTag().
tagTypes
List<TagType> IuvoUnity.Constants.ConstTag.tagTypes = new List<TagType>() private
Referenced by AddTagType(), ConstTag(), ConstTag(), GetTagTypes(), HasTagType(), and RemoveTagType().
uiTags
List<UITag> IuvoUnity.Constants.ConstTag.uiTags = new List<UITag>() private
Referenced by AddUITag(), ConstTag(), ConstTag(), GetUITags(), HasUITag(), and RemoveUITag().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Constants/ConstantTags.cs