Iuvo Unity: IuvoUnity.StateMachines.HSM.StateMachineBuilder Class Reference
IuvoUnity.StateMachines.HSM.StateMachineBuilder Class Reference
Public Member Functions
StateMachineBuilder (State root)
StateMachine Build ()
Private Member Functions
void Wire (State s, StateMachine m, HashSet< State > visited)
Private Attributes
readonly State root
Constructor & Destructor Documentation
StateMachineBuilder()
IuvoUnity.StateMachines.HSM.StateMachineBuilder.StateMachineBuilder (State root)
                {
                    this.root = root;
                }
References root.
Member Function Documentation
Build()
StateMachine IuvoUnity.StateMachines.HSM.StateMachineBuilder.Build ()
                {
                    var m = new StateMachine(root);
                    Wire(root, m, new HashSet<State>());
                    return m;
                }
References root, and Wire().
Wire()
void IuvoUnity.StateMachines.HSM.StateMachineBuilder.Wire (State s, StateMachine m, HashSet< State > visited) private
                {
                    if (s == null) return;
                    if (!visited.Add(s)) return; // State is already wired
                    var flags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.FlattenHierarchy;
                    var machineField = typeof(State).GetField("Machine", flags);
                    if (machineField != null) machineField.SetValue(s, m);
                    foreach (var fld in s.GetType().GetFields(flags))
                    {
                        if (!typeof(State).IsAssignableFrom(fld.FieldType)) continue; // Not a State field
                        if (fld.Name == "Parent") continue; // Skip Parent field
                        var child = (State)(fld.GetValue(s));
                        if (child == null) continue; // Null field
                        if (!ReferenceEquals(child.Parent, s)) continue; // Not a child of 's'
                        Wire(child, m, visited);
                    }
                }
References Wire().
Referenced by Build(), and Wire().
Member Data Documentation
root
readonly State IuvoUnity.StateMachines.HSM.StateMachineBuilder.root private
Referenced by Build(), and StateMachineBuilder().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/StateMachine/HierarchicalStateMachine/StateMachineBuilder.cs