Iuvo Unity: IuvoUnity.Configurations.HealthConfiguration Class Reference
IuvoUnity.Configurations.HealthConfiguration Class Reference
Public Member Functions
AnimationCurve GetDefaultExperienceCurve ()
int GetMaxHealthAtLevel (int level)
void Serialize (HealthComponentData HealthComponent)
HealthComponentData? DeserializeHealthComponent ()
void SetLevelScalingCurve (AnimationCurve newHealthCurve)
Sets a new experience curve for level scaling.
Dictionary< int, int > GetFullHealthTable ()
Returns a dictionary mapping each level to the cumulative EXP required to reach that level.
virtual void OnEnable ()
virtual void OnDisable ()
override void PrintInfo ()
Public Member Functions inherited from IuvoUnity.Configurations.BaseConfig< T >
virtual void Configure (T configurable)
virtual void Reconfigure (T reconfigurable)
virtual string GetConfigSerializePath (string actingConfigClass, string objectToSerializeName, string parentConfigClass="BaseConfig")
Public Attributes
int BaseHealth = 100
Public Attributes inherited from IuvoUnity.Configurations.BaseConfig< T >
string configName
Protected Member Functions
virtual void ImplementDefaultScalingAlgorithm ()
Properties
int MaxLevel [get]
Private Attributes
AnimationCurve DefaultHealthGrowth
AnimationCurve healthCurve
HealthComponentData lastHealthComponentData = new HealthComponentData { MaxHealth = -100, CurrentLevel = -1, CurrentHealth = -1 }
Member Function Documentation
DeserializeHealthComponent()
HealthComponentData? IuvoUnity.Configurations.HealthConfiguration.DeserializeHealthComponent ()
            {
                // no valid data to load
                return null;
                // valid data to load
            }
GetDefaultExperienceCurve()
AnimationCurve IuvoUnity.Configurations.HealthConfiguration.GetDefaultExperienceCurve ()
            {
                return DefaultHealthGrowth;
            }
References DefaultHealthGrowth.
GetFullHealthTable()
Dictionary< int, int > IuvoUnity.Configurations.HealthConfiguration.GetFullHealthTable ()
Returns a dictionary mapping each level to the cumulative EXP required to reach that level.
Returns
            {
                Dictionary<int, int> healthTable = new Dictionary<int, int>();
                for (int level = 1; level <= MaxLevel; level++)
                {
                    healthTable[level] = GetMaxHealthAtLevel(level);
                }
                return healthTable;
            }
References GetMaxHealthAtLevel(), and MaxLevel.
GetMaxHealthAtLevel()
int IuvoUnity.Configurations.HealthConfiguration.GetMaxHealthAtLevel (int level)
            {
                if (level < 1 || level > MaxLevel)
                {
                    IuvoDebug.DebugLogError($"Level {level} is out of bounds. Valid levels are between 1 and {MaxLevel}.");
                    return -1;
                }
                return Mathf.FloorToInt(healthCurve.Evaluate(level));
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), healthCurve, and MaxLevel.
Referenced by GetFullHealthTable().
ImplementDefaultScalingAlgorithm()
virtual void IuvoUnity.Configurations.HealthConfiguration.ImplementDefaultScalingAlgorithm () protected virtual
            {
                IuvoDebug.DebugLog("Implementing default level scaling algorithm...");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog().
Referenced by SetLevelScalingCurve().
OnDisable()
virtual void IuvoUnity.Configurations.HealthConfiguration.OnDisable () virtual
            {
                IuvoDebug.DebugLog("HealthConfiguration disabled.");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog().
OnEnable()
virtual void IuvoUnity.Configurations.HealthConfiguration.OnEnable () virtual
            {
            }
PrintInfo()
override void IuvoUnity.Configurations.HealthConfiguration.PrintInfo () virtual
Reimplemented from IuvoUnity.Configurations.BaseConfig< T >.
            {
                base.PrintInfo();
                IuvoDebug.DebugLog($"Health Configuration: BaseHealth = {BaseHealth}");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog().
Serialize()
void IuvoUnity.Configurations.HealthConfiguration.Serialize (HealthComponentData HealthComponent)
            {
            }
SetLevelScalingCurve()
void IuvoUnity.Configurations.HealthConfiguration.SetLevelScalingCurve (AnimationCurve newHealthCurve)
Sets a new experience curve for level scaling.
Parameters
newExpCurve
            {
                if (newHealthCurve == null)
                {
                    IuvoDebug.DebugLogError("New Expereience curve cannot be null. Implementing default scaling");
                    ImplementDefaultScalingAlgorithm();
                    return;
                }
                IuvoDebug.DebugLog("Setting level scaling algorithm...");
                healthCurve = newHealthCurve;
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), IuvoUnity.Debug.IuvoDebug.DebugLogError(), healthCurve, and ImplementDefaultScalingAlgorithm().
Member Data Documentation
BaseHealth
int IuvoUnity.Configurations.HealthConfiguration.BaseHealth = 100
DefaultHealthGrowth
AnimationCurve IuvoUnity.Configurations.HealthConfiguration.DefaultHealthGrowth private
Initial value:
                                           = new AnimationCurve(
    new Keyframe(1, 100),
    new Keyframe(25, 25000),
    new Keyframe(50, 150000),
    new Keyframe(75, 2500000),
    new Keyframe(100, 50000000)
)
Referenced by GetDefaultExperienceCurve().
healthCurve
AnimationCurve IuvoUnity.Configurations.HealthConfiguration.healthCurve private
Referenced by GetMaxHealthAtLevel(), and SetLevelScalingCurve().
lastHealthComponentData
HealthComponentData IuvoUnity.Configurations.HealthConfiguration.lastHealthComponentData = new HealthComponentData { MaxHealth = -100, CurrentLevel = -1, CurrentHealth = -1 } private
{ MaxHealth = -100, CurrentLevel = -1, CurrentHealth = -1 };
Property Documentation
MaxLevel
int IuvoUnity.Configurations.HealthConfiguration.MaxLevel get
Referenced by GetFullHealthTable(), and GetMaxHealthAtLevel().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Configurations/HealthConfiguration.cs