Iuvo Unity: IuvoUnity.Colors.ComparableColor Class Reference
IuvoUnity.Colors.ComparableColor Class Reference
Public Types
enum ColorComparisonMode {
Brightness , Grayscale , Red , Green ,
Blue , Alpha
}
Public Member Functions
ComparableColor (Color color, ColorComparisonMode compMode=ColorComparisonMode.Brightness)
ComparableColor (Color32 color, ColorComparisonMode compMode=ColorComparisonMode.Brightness)
int CompareTo (ComparableColor other)
override bool Equals (object obj)
override int GetHashCode ()
Static Public Member Functions
static bool operator> (ComparableColor a, ComparableColor b)
static bool operator< (ComparableColor a, ComparableColor b)
static bool operator>= (ComparableColor a, ComparableColor b)
static bool operator<= (ComparableColor a, ComparableColor b)
static bool operator== (ComparableColor a, ComparableColor b)
static bool operator!= (ComparableColor a, ComparableColor b)
Public Attributes
Color color
ColorComparisonMode mode = ColorComparisonMode.Brightness
Private Member Functions
float GetComparableValue ()
Member Enumeration Documentation
ColorComparisonMode
enum IuvoUnity.Colors.ComparableColor.ColorComparisonMode
Enumerator
Brightness
Grayscale
Red
Green
Blue
Alpha
            {
                Brightness,
                Grayscale,
                Red,
                Green,
                Blue,
                Alpha
            }
Constructor & Destructor Documentation
ComparableColor() [1/2]
IuvoUnity.Colors.ComparableColor.ComparableColor (Color color, ColorComparisonMode compMode = ColorComparisonMode::Brightness)
            {
                this.color = color;
                this.mode = compMode;
            }
References color.
Referenced by CompareTo(), Equals(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
ComparableColor() [2/2]
IuvoUnity.Colors.ComparableColor.ComparableColor (Color32 color, ColorComparisonMode compMode = ColorComparisonMode::Brightness)
            {
                this.color = (Color)color;
                this.mode = compMode;
            }
References color.
Member Function Documentation
CompareTo()
int IuvoUnity.Colors.ComparableColor.CompareTo (ComparableColor other)
            {
                if (other == null) return 1;
                float aVal = this.GetComparableValue();
                float bVal = other.GetComparableValue();
                return aVal.CompareTo(bVal);
            }
References ComparableColor(), and GetComparableValue().
Equals()
override bool IuvoUnity.Colors.ComparableColor.Equals (object obj)
            {
                if (obj is ComparableColor other)
                    return this == other;
                return false;
            }
References ComparableColor().
GetComparableValue()
float IuvoUnity.Colors.ComparableColor.GetComparableValue () private
            {
                switch (mode)
                {
                    case ColorComparisonMode.Brightness:
                        return (color.r + color.g + color.b) / 3f;
                    case ColorComparisonMode.Grayscale:
                        return color.grayscale;
                    case ColorComparisonMode.Red:
                        return color.r;
                    case ColorComparisonMode.Green:
                        return color.g;
                    case ColorComparisonMode.Blue:
                        return color.b;
                    case ColorComparisonMode.Alpha:
                        return color.a;
                    default:
                        return 0f;
                }
            }
References color, and mode.
Referenced by CompareTo(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
GetHashCode()
override int IuvoUnity.Colors.ComparableColor.GetHashCode ()
            {
                return color.GetHashCode();
            }
References color.
operator!=()
bool IuvoUnity.Colors.ComparableColor.operator!= (ComparableColor a, ComparableColor b) static
            {
                return !(a == b);
            }
References ComparableColor().
operator<()
bool IuvoUnity.Colors.ComparableColor.operator< (ComparableColor a, ComparableColor b) static
            {
                return a.GetComparableValue() < b.GetComparableValue();
            }
References ComparableColor(), and GetComparableValue().
operator<=()
bool IuvoUnity.Colors.ComparableColor.operator<= (ComparableColor a, ComparableColor b) static
            {
                return a.GetComparableValue() <= b.GetComparableValue();
            }
References ComparableColor(), and GetComparableValue().
operator==()
bool IuvoUnity.Colors.ComparableColor.operator== (ComparableColor a, ComparableColor b) static
            {
                if (ReferenceEquals(a, b)) return true;
                if (a is null || b is null) return false;
                return Mathf.Approximately(a.GetComparableValue(), b.GetComparableValue());
            }
References ComparableColor(), and GetComparableValue().
operator>()
bool IuvoUnity.Colors.ComparableColor.operator> (ComparableColor a, ComparableColor b) static
            {
                return a.GetComparableValue() > b.GetComparableValue();
            }
References ComparableColor(), and GetComparableValue().
operator>=()
bool IuvoUnity.Colors.ComparableColor.operator>= (ComparableColor a, ComparableColor b) static
            {
                return a.GetComparableValue() >= b.GetComparableValue();
            }
References ComparableColor(), and GetComparableValue().
Member Data Documentation
color
Color IuvoUnity.Colors.ComparableColor.color
Referenced by ComparableColor(), ComparableColor(), GetComparableValue(), and GetHashCode().
mode
ColorComparisonMode IuvoUnity.Colors.ComparableColor.mode = ColorComparisonMode.Brightness
Referenced by GetComparableValue().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Colors/ComparableColor.cs