Iuvo Unity: IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager Class Reference
IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager Class Reference
Public Member Functions
void GenerateGridDungeon ()
void RemoveWalls ()
Public Attributes
bool generate = false
bool changedBoundaryColor = false
float wallPerctentage = 1f
bool isFinished = false
bool isFinishedMakingRooms = false
bool dungeonIsPathable = false
GameObject tester
GameObject roomFloorPrefab
int WorldWidth = 100
int WorldHeight = 5
int WorldLength = 100
int NumOfRooms = 0
int RoomWidth = 15
int RoomHeight = 15
int RoomLength = 15
float distanceFactor = 0.5f
List< Room > rooms = new List<Room>()
List< Wall > walls = new List<Wall>()
List< Wall > boundaryWalls = new List<Wall>()
Properties
static GridDungeonManager Instance [get, private set]
Private Member Functions
void Awake ()
void Update ()
void GenerateGridRoom (Vector3 position, int width, int height, int length)
void GenerateGridOfRooms ()
void SetWorldBoundaries ()
Private Attributes
Vector3 currentWorldSize = Vector3.zero
Member Function Documentation
Awake()
void IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.Awake () private
                {
                    if (Instance == null)
                    {
                        Instance = this;
                    }
                    else if (Instance != this)
                    {
                        Destroy(gameObject);
                    }
                    NumOfRooms = WorldWidth * WorldLength;
                }
References Instance, NumOfRooms, WorldLength, and WorldWidth.
GenerateGridDungeon()
void IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.GenerateGridDungeon ()
                {
                    GenerateGridOfRooms();
                }
References GenerateGridOfRooms().
Referenced by Update().
GenerateGridOfRooms()
void IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.GenerateGridOfRooms () private
                {
                    currentWorldSize = transform.position;
                    for (int h = 0; h < WorldHeight; h++)
                    {
                        for (int i = 0; i < WorldWidth; i++)
{
                            for (int j = 0; j < WorldLength; j++)
{
                                if (currentWorldSize.HasObjectWithLayerInBox(LayerMask.NameToLayer("PG_Room"), new Vector3(RoomLength / 2, RoomWidth / 2, RoomHeight / 2)))
{
                                    continue;
                                }
                                GenerateGridRoom(currentWorldSize, RoomWidth, RoomHeight, RoomLength);
                                currentWorldSize = currentWorldSize.Add(z: 1 * distanceFactor);
                            }
                            currentWorldSize = currentWorldSize.WithZ(transform.position.z);
                            currentWorldSize = currentWorldSize.Add(x: 1 * distanceFactor);
                        }
                        currentWorldSize = currentWorldSize.WithX(transform.position.x);
                        currentWorldSize = currentWorldSize.Add(y: 1 * distanceFactor);
                    }
                }
References currentWorldSize, distanceFactor, GenerateGridRoom(), RoomHeight, RoomLength, RoomWidth, WorldHeight, WorldLength, and WorldWidth.
Referenced by GenerateGridDungeon().
GenerateGridRoom()
void IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.GenerateGridRoom (Vector3 position, int width, int height, int length) private
                {
                    GameObject roomObject = Instantiate(roomFloorPrefab, position, Quaternion.identity);
                    Room room = roomObject.GetComponent<Room>();
                    if (room != null)
                    {
                        room.roomBounds.size = new Vector3(width, height, length);
                        rooms.Add(room);
                        walls.Add(room.northWall);
                        walls.Add(room.eastWall);
                        walls.Add(room.southWall);
                        walls.Add(room.westWall);
                    }
                }
References IuvoUnity.ProceduralGeneration.Room.eastWall, IuvoUnity.ProceduralGeneration.Room.northWall, roomFloorPrefab, rooms, IuvoUnity.ProceduralGeneration.Room.southWall, walls, and IuvoUnity.ProceduralGeneration.Room.westWall.
Referenced by GenerateGridOfRooms().
RemoveWalls()
void IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.RemoveWalls ()
                {
                    //for (int i = 0; i < rooms.Count; i++)
                    //{
                    //    rooms[i].CountBoundaryWalls();
                    //    rooms[i].RemoveSharedWalls(rooms);
                    //    if (i % RoomWidth == 0)
                    //    {
                    //        int side = Random.Range(1, 4);
                    //        switch (side)
                    //        {
                    //            case 1:
                    //                rooms[i].northWall.gameObject.SetActive(false);
                    //                break;
                    //            case 2:
                    //                rooms[i].eastWall.gameObject.SetActive(false);
                    //                break;
                    //            case 3:
                    //                rooms[i].southWall.gameObject.SetActive(false);
                    //                break;
                    //            case 4:
                    //                rooms[i].westWall.gameObject.SetActive(false);
                    //                break;
                    //            default:
                    //                break;
                    //        }
                    //    }
                    //}
                    //randomly deactivate walls
                    //int randomNum = UnityEngine.Random.Range(0, 15);
                    //int max = rooms.Count;
                    //for (int i = max; i < (max % (randomNum +1)); i--)
                    //{
                    //    int newRandomNum = UnityEngine.Random.Range(0, 15);
                    //    rooms[i].DisableWall(newRandomNum);
                    //}
                    for (int i = 0; i < walls.Count; i++)
                    {
                        for (int j = 0; j < boundaryWalls.Count; j++)
{
                            if (walls[i] == boundaryWalls[j])
{
                                walls.RemoveAt(i);
                            }
                        }
                    }
                    for (int i = 0; i < walls.Count; i++)
                    {
                        if (walls[i].myRoom.IsBoundaryRoom)
{
                            continue;
                        }
                        else
{
                            int randomNumForWallOperation = Random.Range(1, 16);
                            walls[i].myRoom.DisableWall(randomNumForWallOperation);
                        }
                    }
                }
References boundaryWalls, and walls.
Referenced by Update().
SetWorldBoundaries()
void IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.SetWorldBoundaries () private
                {
                    for (int i = 0; i < walls.Count; i++)
                    {
                        walls[i].IsBoundary();
                    }
                    for (int i = 0; i < walls.Count; i++)
                    {
                        if (walls[i].iAmBoundaryWall)
{
                            boundaryWalls.Add(walls[i]);
                            if (changedBoundaryColor)
{
                                MeshRenderer rend = walls[i].GetComponent<MeshRenderer>();
                                if (rend != null)
{
                                    walls[i].gameObject.SetMaterialColor(Color.white);
                                }
                            }
                        }
                    }
                }
References boundaryWalls, changedBoundaryColor, and walls.
Referenced by Update().
Update()
void IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.Update () private
                {
                    if (!isFinished)
                    {
                        if (rooms.Count >= NumOfRooms)
{
                            isFinishedMakingRooms = true;
                        }
                        else
{
                            GenerateGridDungeon();
                            SetWorldBoundaries();
                        }
                        if (isFinishedMakingRooms)
{
                            RemoveWalls();
                            RemoveWalls();
                            //RemoveWalls();
                        }
                    }
                }
References GenerateGridDungeon(), isFinished, isFinishedMakingRooms, NumOfRooms, RemoveWalls(), rooms, and SetWorldBoundaries().
Member Data Documentation
boundaryWalls
List<Wall> IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.boundaryWalls = new List<Wall>()
Referenced by RemoveWalls(), and SetWorldBoundaries().
changedBoundaryColor
bool IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.changedBoundaryColor = false
Referenced by SetWorldBoundaries().
currentWorldSize
Vector3 IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.currentWorldSize = Vector3.zero private
Referenced by GenerateGridOfRooms().
distanceFactor
float IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.distanceFactor = 0.5f
Referenced by GenerateGridOfRooms().
dungeonIsPathable
bool IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.dungeonIsPathable = false
generate
bool IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.generate = false
isFinished
bool IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.isFinished = false
Referenced by Update().
isFinishedMakingRooms
bool IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.isFinishedMakingRooms = false
Referenced by Update().
NumOfRooms
int IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.NumOfRooms = 0
Referenced by Awake(), and Update().
roomFloorPrefab
GameObject IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.roomFloorPrefab
Referenced by GenerateGridRoom().
RoomHeight
int IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.RoomHeight = 15
Referenced by GenerateGridOfRooms().
RoomLength
int IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.RoomLength = 15
Referenced by GenerateGridOfRooms().
rooms
List<Room> IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.rooms = new List<Room>()
Referenced by GenerateGridRoom(), and Update().
RoomWidth
int IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.RoomWidth = 15
Referenced by GenerateGridOfRooms().
tester
GameObject IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.tester
wallPerctentage
float IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.wallPerctentage = 1f
walls
List<Wall> IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.walls = new List<Wall>()
Referenced by IuvoUnity.ProceduralGeneration.Wall.Destroy(), GenerateGridRoom(), RemoveWalls(), and SetWorldBoundaries().
WorldHeight
int IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.WorldHeight = 5
Referenced by GenerateGridOfRooms().
WorldLength
int IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.WorldLength = 100
Referenced by Awake(), and GenerateGridOfRooms().
WorldWidth
int IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.WorldWidth = 100
Referenced by Awake(), and GenerateGridOfRooms().
Property Documentation
Instance
GridDungeonManager IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.Instance static get private set
{ get; private set; } // Singleton instance
Referenced by Awake(), and IuvoUnity.ProceduralGeneration.Wall.Destroy().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ProceduralGenerationBases/Dungeons/GridDungeonManager.cs