Iuvo Unity: IuvoUnity.ProceduralGeneration.ProceduralStripMesh Class Reference
IuvoUnity.ProceduralGeneration.ProceduralStripMesh Class Reference
Public Member Functions
void SetPairs (List< ProceduralStripLocationPair > pairs)
void GenerateBetweenStrips (List< ProceduralStripLocationPair > stripA, List< ProceduralStripLocationPair > stripB)
Public Member Functions inherited from IuvoUnity.ProceduralGeneration.ProceduralMesh
void Generate ()
Public Attributes
List< ProceduralStripLocationPair > pairedPoints = new List<ProceduralStripLocationPair>()
bool closedLoop = false
float thickness = 0f
bool stretchUV = false
float uvTileX = 1f
float uvTileY = 1f
bool useColors = false
Public Attributes inherited from IuvoUnity.ProceduralGeneration.ProceduralMesh
List< Vector3 > vertices = new List<Vector3>()
List< int > triangles = new List<int>()
List< Vector2 > uvs = new List<Vector2>()
List< Vector3 > normals = new List<Vector3>()
Mesh mesh
string meshName = "ProceduralMesh"
Material meshMaterial
Protected Member Functions
override void GenerateMesh ()
override void ApplyMesh ()
override void ClearMeshData ()
Protected Member Functions inherited from IuvoUnity.ProceduralGeneration.ProceduralMesh
virtual void Awake ()
void GenerateMesh ()
Protected Attributes
List< Color > colors = new List<Color>()
Member Function Documentation
ApplyMesh()
override void IuvoUnity.ProceduralGeneration.ProceduralStripMesh.ApplyMesh () protected virtual
Reimplemented from IuvoUnity.ProceduralGeneration.ProceduralMesh.
            {
                base.ApplyMesh();
                if (useColors && colors.Count == vertices.Count)
                    mesh.SetColors(colors);
            }
References colors, IuvoUnity.ProceduralGeneration.ProceduralMesh.mesh, useColors, and IuvoUnity.ProceduralGeneration.ProceduralMesh.vertices.
Referenced by GenerateBetweenStrips().
ClearMeshData()
override void IuvoUnity.ProceduralGeneration.ProceduralStripMesh.ClearMeshData () protected virtual
Reimplemented from IuvoUnity.ProceduralGeneration.ProceduralMesh.
            {
                base.ClearMeshData();
                colors.Clear();
            }
References colors.
Referenced by GenerateBetweenStrips().
GenerateBetweenStrips()
void IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateBetweenStrips (List< ProceduralStripLocationPair > stripA, List< ProceduralStripLocationPair > stripB)
            {
                if (stripA.Count != stripB.Count)
                {
                    IuvoDebug.DebugLogError("Strips must have the same number of pairs.");
                    return;
                }
                ClearMeshData();
                for (int i = 0; i < stripA.Count - 1; i++)
                {
                    ProceduralStripLocationPair a0 = stripA[i];
                    ProceduralStripLocationPair a1 = stripA[i + 1];
                    ProceduralStripLocationPair b0 = stripB[i];
                    ProceduralStripLocationPair b1 = stripB[i + 1];
                    int startIndex = vertices.Count;
                    // Vertices (quad: a0.A -> a1.A -> b1.A -> b0.A)
                    vertices.Add(a0.A);
                    vertices.Add(a1.A);
                    vertices.Add(b1.A);
                    vertices.Add(b0.A);
                    vertices.Add(a0.B);
                    vertices.Add(a1.B);
                    vertices.Add(b1.B);
                    vertices.Add(b0.B);
                    // Triangles for both quads
                    triangles.AddRange(new int[]
                    {
                            startIndex + 0, startIndex + 1, startIndex + 2,
                            startIndex + 2, startIndex + 3, startIndex + 0,
                            startIndex + 4, startIndex + 5, startIndex + 6,
                            startIndex + 6, startIndex + 7, startIndex + 4
                    });
                    // Normals (approximate cross product)
                    Vector3 forwardA = a1.A - a0.A;
                    Vector3 upA = b0.A - a0.A;
                    Vector3 normalA = Vector3.Cross(forwardA, upA).normalized;
                    Vector3 forwardB = a1.B - a0.B;
                    Vector3 upB = b0.B - a0.B;
                    Vector3 normalB = Vector3.Cross(forwardB, upB).normalized;
                    normals.AddRange(new[] { normalA, normalA, normalA, normalA });
                    normals.AddRange(new[] { normalB, normalB, normalB, normalB });
                    // UVs (simple mapping)
                    float v0 = (float)i / (stripA.Count - 1);
                    float v1 = (float)(i + 1) / (stripA.Count - 1);
                    uvs.AddRange(new[]
                    {
                            new Vector2(0, v0),
                            new Vector2(0, v1),
                            new Vector2(1, v1),
                            new Vector2(1, v0),
                            new Vector2(0, v0),
                            new Vector2(0, v1),
                            new Vector2(1, v1),
                            new Vector2(1, v0)
                        });
                    if (useColors)
                    {
                        colors.AddRange(new[] { a0.color, a1.color, b1.color, b0.color });
                        colors.AddRange(new[] { a0.color, a1.color, b1.color, b0.color });
                    }
                }
                ApplyMesh();
            }
References IuvoUnity.ProceduralStripLocationPair.A, ApplyMesh(), IuvoUnity.ProceduralStripLocationPair.B, ClearMeshData(), IuvoUnity.ProceduralStripLocationPair.color, colors, IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.ProceduralGeneration.ProceduralMesh.normals, IuvoUnity.ProceduralGeneration.ProceduralMesh.triangles, useColors, IuvoUnity.ProceduralGeneration.ProceduralMesh.uvs, and IuvoUnity.ProceduralGeneration.ProceduralMesh.vertices.
GenerateMesh()
override void IuvoUnity.ProceduralGeneration.ProceduralStripMesh.GenerateMesh () protected
            {
                if (pairedPoints.Count < 2)
                {
                    IuvoDebug.DebugLogWarning("Need at least two pairs to generate a strip.");
                    return;
                }
                int loopLimit = closedLoop ? pairedPoints.Count : pairedPoints.Count - 1;
                for (int i = 0; i < loopLimit; i++)
                {
                    ProceduralStripLocationPair p0 = pairedPoints[i];
                    ProceduralStripLocationPair p1 = pairedPoints[(i + 1) % pairedPoints.Count];
                    int startIndex = vertices.Count;
                    Vector3 dirA = (p1.A - p0.A).normalized;
                    Vector3 dirB = (p1.B - p0.B).normalized;
                    Vector3 normal = Vector3.Cross(dirB - dirA, p0.B - p0.A).normalized;
                    Vector3 tOffset = thickness * normal * 0.5f;
                    // Vertices for quad (with thickness)
                    vertices.Add(p0.A - tOffset);
                    vertices.Add(p1.A - tOffset);
                    vertices.Add(p1.B + tOffset);
                    vertices.Add(p0.B + tOffset);
                    // Triangles
                    triangles.Add(startIndex + 0);
                    triangles.Add(startIndex + 1);
                    triangles.Add(startIndex + 2);
                    triangles.Add(startIndex + 2);
                    triangles.Add(startIndex + 3);
                    triangles.Add(startIndex + 0);
                    // UVs
                    float t0 = stretchUV ? (float)i / loopLimit : i;
                    float t1 = stretchUV ? (float)(i + 1) / loopLimit : i + 1;
                    uvs.Add(new Vector2(0, t0 * uvTileY));
                    uvs.Add(new Vector2(0, t1 * uvTileY));
                    uvs.Add(new Vector2(1 * uvTileX, t1 * uvTileY));
                    uvs.Add(new Vector2(1 * uvTileX, t0 * uvTileY));
                    // Normals
                    for (int j = 0; j < 4; j++)
                        normals.Add(normal);
                    // Colors (optional)
                    if (useColors)
                    {
                        colors.Add(p0.color);
                        colors.Add(p1.color);
                        colors.Add(p1.color);
                        colors.Add(p0.color);
                    }
                }
            }
References IuvoUnity.ProceduralStripLocationPair.A, IuvoUnity.ProceduralStripLocationPair.B, closedLoop, IuvoUnity.ProceduralStripLocationPair.color, colors, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), IuvoUnity.ProceduralGeneration.ProceduralMesh.normals, pairedPoints, stretchUV, thickness, IuvoUnity.ProceduralGeneration.ProceduralMesh.triangles, useColors, IuvoUnity.ProceduralGeneration.ProceduralMesh.uvs, uvTileX, uvTileY, and IuvoUnity.ProceduralGeneration.ProceduralMesh.vertices.
SetPairs()
void IuvoUnity.ProceduralGeneration.ProceduralStripMesh.SetPairs (List< ProceduralStripLocationPair > pairs)
            {
                pairedPoints = new List<ProceduralStripLocationPair>(pairs);
                Generate();
            }
References IuvoUnity.ProceduralGeneration.ProceduralMesh.Generate(), and pairedPoints.
Member Data Documentation
closedLoop
bool IuvoUnity.ProceduralGeneration.ProceduralStripMesh.closedLoop = false
Referenced by GenerateMesh().
colors
List<Color> IuvoUnity.ProceduralGeneration.ProceduralStripMesh.colors = new List<Color>() protected
Referenced by ApplyMesh(), ClearMeshData(), GenerateBetweenStrips(), and GenerateMesh().
pairedPoints
List<ProceduralStripLocationPair> IuvoUnity.ProceduralGeneration.ProceduralStripMesh.pairedPoints = new List<ProceduralStripLocationPair>()
Referenced by GenerateMesh(), and SetPairs().
stretchUV
bool IuvoUnity.ProceduralGeneration.ProceduralStripMesh.stretchUV = false
Referenced by GenerateMesh().
thickness
float IuvoUnity.ProceduralGeneration.ProceduralStripMesh.thickness = 0f
Referenced by GenerateMesh().
useColors
bool IuvoUnity.ProceduralGeneration.ProceduralStripMesh.useColors = false
Referenced by ApplyMesh(), GenerateBetweenStrips(), and GenerateMesh().
uvTileX
float IuvoUnity.ProceduralGeneration.ProceduralStripMesh.uvTileX = 1f
Referenced by GenerateMesh().
uvTileY
float IuvoUnity.ProceduralGeneration.ProceduralStripMesh.uvTileY = 1f
Referenced by GenerateMesh().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ProceduralGenerationBases/ProceduralMesh/ProceduralStripMesh.cs