Iuvo Unity: IuvoUnity.Events.FlexibleEvent Class Reference
IuvoUnity.Events.FlexibleEvent Class Reference
Public Member Functions
void Invoke ()
void AddListener (Action listener)
void RemoveListener (Action listener)
void AddUnityListener (UnityAction listener)
void RemoveUnityListener (UnityAction listener)
void RemoveAllFlexibleEventListeners ()
Properties
UnityEvent UnityEvent [get]
Events
Action internalEvent
Private Attributes
UnityEvent unityEvent = new UnityEvent()
Member Function Documentation
AddListener()
void IuvoUnity.Events.FlexibleEvent.AddListener (Action listener)
            {
                internalEvent += listener;
                //internalActions.Add(listener);
            }
References internalEvent.
AddUnityListener()
void IuvoUnity.Events.FlexibleEvent.AddUnityListener (UnityAction listener)
            {
                unityEvent.AddListener(listener);
            }
References unityEvent.
Invoke()
void IuvoUnity.Events.FlexibleEvent.Invoke ()
            {
                unityEvent?.Invoke();
                internalEvent?.Invoke();
            }
References internalEvent, and unityEvent.
RemoveAllFlexibleEventListeners()
void IuvoUnity.Events.FlexibleEvent.RemoveAllFlexibleEventListeners ()
            {
                //foreach (var evt in internalActions)
                //{
                //    RemoveListener(evt);
                //}
                internalEvent = null; // Clear the C# event to prevent memory leaks
                unityEvent.RemoveAllListeners();
            }
References internalEvent, and unityEvent.
RemoveListener()
void IuvoUnity.Events.FlexibleEvent.RemoveListener (Action listener)
            {
                internalEvent -= listener;
                //internalActions.Remove(listener);
            }
References internalEvent.
RemoveUnityListener()
void IuvoUnity.Events.FlexibleEvent.RemoveUnityListener (UnityAction listener)
            {
                unityEvent.RemoveListener(listener);
            }
References unityEvent.
Member Data Documentation
unityEvent
UnityEvent IuvoUnity.Events.FlexibleEvent.unityEvent = new UnityEvent() private
Referenced by AddUnityListener(), Invoke(), RemoveAllFlexibleEventListeners(), and RemoveUnityListener().
Property Documentation
UnityEvent
UnityEvent IuvoUnity.Events.FlexibleEvent.UnityEvent get
Event Documentation
internalEvent
Action IuvoUnity.Events.FlexibleEvent.internalEvent private
Referenced by AddListener(), Invoke(), RemoveAllFlexibleEventListeners(), and RemoveListener().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Events/FlexibleEvent.cs