Iuvo Unity: IuvoUnity.BaseClasses.SemiBehaviorManager Class Reference
IuvoUnity.BaseClasses.SemiBehaviorManager Class Reference
Public Member Functions
void Register (SemiBehavior behavior)
void RefreshPriorities ()
void Unregister (SemiBehavior behavior)
void ClearAll ()
Static Public Member Functions
static T Create< T > (SemiBehaviorManager manager)
static void Destroy (SemiBehavior behavior)
Protected Attributes
readonly List< SemiBehavior > regularUpdateBehaviors = new()
readonly List< SemiBehavior > fixedUpdateBehaviors = new()
readonly List< SemiBehavior > lateUpdateBehaviors = new()
Private Member Functions
void Awake ()
void SortListByPriority (List< SemiBehavior > list)
void Update ()
void FixedUpdate ()
void LateUpdate ()
Member Function Documentation
Awake()
void IuvoUnity.BaseClasses.SemiBehaviorManager.Awake () private
            {
            }
ClearAll()
void IuvoUnity.BaseClasses.SemiBehaviorManager.ClearAll ()
            {
                foreach (var behavior in regularUpdateBehaviors) behavior.DeinitializeLifecycle();
                foreach (var behavior in fixedUpdateBehaviors) behavior.DeinitializeLifecycle();
                foreach (var behavior in lateUpdateBehaviors) behavior.DeinitializeLifecycle();
                regularUpdateBehaviors.Clear();
                fixedUpdateBehaviors.Clear();
                lateUpdateBehaviors.Clear();
            }
References fixedUpdateBehaviors, lateUpdateBehaviors, and regularUpdateBehaviors.
Create< T >()
T IuvoUnity.BaseClasses.SemiBehaviorManager.Create< T > (SemiBehaviorManager manager) static
Type Constraints
T : SemiBehavior
T : new()
                                                                           : SemiBehavior, new()
            {
                T instance = new T();
                manager.Register(instance);
                return instance;
            }
Destroy()
void IuvoUnity.BaseClasses.SemiBehaviorManager.Destroy (SemiBehavior behavior) static
            {
                if (behavior == null) return;
                behavior.DeinitializeLifecycle();
                behavior.parentManager.Unregister(behavior);
            }
References IuvoUnity.BaseClasses.SemiBehavior.DeinitializeLifecycle(), IuvoUnity.BaseClasses.SemiBehavior.parentManager, and Unregister().
FixedUpdate()
void IuvoUnity.BaseClasses.SemiBehaviorManager.FixedUpdate () private
            {
                foreach (var behavior in fixedUpdateBehaviors)
                {
                    if (behavior != null && behavior.isInitialized)
                        behavior.Tick();
                }
            }
References fixedUpdateBehaviors.
LateUpdate()
void IuvoUnity.BaseClasses.SemiBehaviorManager.LateUpdate () private
            {
                foreach (var behavior in lateUpdateBehaviors)
                {
                    if (behavior != null && behavior.isInitialized)
                        behavior.Tick();
                }
            }
References lateUpdateBehaviors.
RefreshPriorities()
void IuvoUnity.BaseClasses.SemiBehaviorManager.RefreshPriorities ()
            {
                SortListByPriority(regularUpdateBehaviors);
                SortListByPriority(fixedUpdateBehaviors);
                SortListByPriority(lateUpdateBehaviors);
            }
References fixedUpdateBehaviors, lateUpdateBehaviors, regularUpdateBehaviors, and SortListByPriority().
Register()
void IuvoUnity.BaseClasses.SemiBehaviorManager.Register (SemiBehavior behavior)
            {
                if (behavior == null) return;
                if (regularUpdateBehaviors.Contains(behavior) ||
                    fixedUpdateBehaviors.Contains(behavior) ||
                    lateUpdateBehaviors.Contains(behavior)) return;
                behavior.parentManager = this;
                behavior.TryInitializeLifecycle();
                switch (behavior.updateMode)
                {
                    case SemiBehavior.UpdateMode.Regular:
                        regularUpdateBehaviors.Add(behavior);
                        SortListByPriority(regularUpdateBehaviors);
                        break;
                    case SemiBehavior.UpdateMode.Fixed:
                        fixedUpdateBehaviors.Add(behavior);
                        SortListByPriority(fixedUpdateBehaviors);
                        break;
                    case SemiBehavior.UpdateMode.Late:
                        lateUpdateBehaviors.Add(behavior);
                        SortListByPriority(lateUpdateBehaviors);
                        break;
                }
            }
References fixedUpdateBehaviors, lateUpdateBehaviors, regularUpdateBehaviors, SortListByPriority(), IuvoUnity.BaseClasses.SemiBehavior.TryInitializeLifecycle(), and IuvoUnity.BaseClasses.SemiBehavior.updateMode.
SortListByPriority()
void IuvoUnity.BaseClasses.SemiBehaviorManager.SortListByPriority (List< SemiBehavior > list) private
            {
                list.Sort((a, b) =>
                {
                    int levelComparison = b.PriorityLevel.CompareTo(a.PriorityLevel); // descending
                    if (levelComparison != 0)
                        return levelComparison;
                    return b.priorityScale.Value.CompareTo(a.priorityScale.Value); // descending
                });
            }
Referenced by RefreshPriorities(), and Register().
Unregister()
void IuvoUnity.BaseClasses.SemiBehaviorManager.Unregister (SemiBehavior behavior)
            {
                if (behavior == null) return;
                behavior.DeinitializeLifecycle();
                regularUpdateBehaviors.Remove(behavior);
                fixedUpdateBehaviors.Remove(behavior);
                lateUpdateBehaviors.Remove(behavior);
            }
References IuvoUnity.BaseClasses.SemiBehavior.DeinitializeLifecycle(), fixedUpdateBehaviors, lateUpdateBehaviors, and regularUpdateBehaviors.
Referenced by Destroy().
Update()
void IuvoUnity.BaseClasses.SemiBehaviorManager.Update () private
            {
                foreach (var behavior in regularUpdateBehaviors)
                {
                    if (behavior != null && behavior.isInitialized)
                        behavior.Tick();
                }
            }
References regularUpdateBehaviors.
Member Data Documentation
fixedUpdateBehaviors
readonly List<SemiBehavior> IuvoUnity.BaseClasses.SemiBehaviorManager.fixedUpdateBehaviors = new() protected
Referenced by ClearAll(), FixedUpdate(), RefreshPriorities(), Register(), and Unregister().
lateUpdateBehaviors
readonly List<SemiBehavior> IuvoUnity.BaseClasses.SemiBehaviorManager.lateUpdateBehaviors = new() protected
Referenced by ClearAll(), LateUpdate(), RefreshPriorities(), Register(), and Unregister().
regularUpdateBehaviors
readonly List<SemiBehavior> IuvoUnity.BaseClasses.SemiBehaviorManager.regularUpdateBehaviors = new() protected
Referenced by ClearAll(), RefreshPriorities(), Register(), Unregister(), and Update().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/BaseClasses/SemiBehaviorManager.cs