Iuvo Unity: IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration Class Reference
IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration Class Reference
Public Attributes
int width = 5
int height = 5
int levels = 3
Material pathMaterial
Private Member Functions
void Start ()
void GenerateMaze ()
void GenerateMesh ()
void ApplyTextures ()
Private Attributes
List< Vector3 > mazeNodes = new List<Vector3>()
List< ProceduralStripLocationPair > corridors = new List<ProceduralStripLocationPair>()
Member Function Documentation
ApplyTextures()
void IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.ApplyTextures () private
            {
                MeshRenderer meshRenderer = GetComponent<MeshRenderer>();
                if (pathMaterial != null)
                {
                    meshRenderer.material = pathMaterial;
                }
            }
References pathMaterial.
GenerateMaze()
void IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.GenerateMaze () private
            {
                // Generate nodes (rooms)
                for (int z = 0; z < levels; z++)
                {
                    for (int x = 0; x < width; x++)
                    {
                        for (int y = 0; y < height; y++)
{
                            mazeNodes.Add(new Vector3(x * 2, y * 2, z * 2)); // Keep some space for thickness
                        }
                    }
                }
                // Connect rooms using random paths
                for (int i = 0; i < mazeNodes.Count; i++)
                {
                    Vector3 currentNode = mazeNodes[i];
                    // Connect vertically (up/down)
                    if (i + width < mazeNodes.Count)
                        corridors.Add(new ProceduralStripLocationPair(currentNode, mazeNodes[i + width], Random.ColorHSV()));
                    // Connect horizontally (left/right)
                    if (i + 1 < mazeNodes.Count && i % width != width - 1)
                        corridors.Add(new ProceduralStripLocationPair(currentNode, mazeNodes[i + 1], Random.ColorHSV()));
                }
                // Create the mesh from corridors
                GenerateMesh();
            }
References corridors, GenerateMesh(), height, levels, mazeNodes, and width.
Referenced by Start().
GenerateMesh()
void IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.GenerateMesh () private
            {
                MeshFilter meshFilter = GetComponent<MeshFilter>();
                Mesh mesh = new Mesh();
                List<Vector3> vertices = new List<Vector3>();
                List<int> triangles = new List<int>();
                List<Vector2> uvs = new List<Vector2>();
                // Generate vertices for each corridor
                foreach (var corridor in corridors)
                {
                    Vector3 A = corridor.A;
                    Vector3 B = corridor.B;
                    // Create vertices for corridor mesh (simple quad for now)
                    vertices.Add(A);
                    vertices.Add(B);
                    vertices.Add(A + Vector3.up * 1); // Vertical offset for thickness
                    vertices.Add(B + Vector3.up * 1);
                    // Triangles (forming a quad)
                    int vertCount = vertices.Count;
                    triangles.Add(vertCount - 4);
                    triangles.Add(vertCount - 3);
                    triangles.Add(vertCount - 2);
                    triangles.Add(vertCount - 2);
                    triangles.Add(vertCount - 3);
                    triangles.Add(vertCount - 1);
                    // UVs (simple mapping for now)
                    uvs.Add(new Vector2(0, 0));
                    uvs.Add(new Vector2(1, 0));
                    uvs.Add(new Vector2(0, 1));
                    uvs.Add(new Vector2(1, 1));
                }
                // Set mesh data
                mesh.SetVertices(vertices);
                mesh.SetTriangles(triangles, 0);
                mesh.SetUVs(0, uvs);
                mesh.RecalculateNormals();
                mesh.RecalculateBounds();
                meshFilter.mesh = mesh;
            }
References corridors.
Referenced by GenerateMaze().
Start()
void IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.Start () private
            {
                GenerateMaze();
            }
References GenerateMaze().
Member Data Documentation
corridors
List<ProceduralStripLocationPair> IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.corridors = new List<ProceduralStripLocationPair>() private
Referenced by GenerateMaze(), and GenerateMesh().
height
int IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.height = 5
Referenced by GenerateMaze().
levels
int IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.levels = 3
Referenced by GenerateMaze().
mazeNodes
List<Vector3> IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.mazeNodes = new List<Vector3>() private
Referenced by GenerateMaze().
pathMaterial
Material IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.pathMaterial
Referenced by ApplyTextures().
width
int IuvoUnity.ProceduralGeneration.ProceduralMazeGeneration.width = 5
Referenced by GenerateMaze().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ProceduralGenerationBases/Mazes/ProceduralMazeGeneration.cs