Iuvo Unity: IuvoUnity.DataStructs.MultiTimer Class Reference
IuvoUnity.DataStructs.MultiTimer Class Reference
Public Member Functions
MultiTimer ()
MultiTimer (float defaultDuration)
void Dispose ()
void Start (Timer_Activity_Mode mode)
void Pause (Timer_Activity_Mode mode)
void Resume (Timer_Activity_Mode mode)
void Reset (Timer_Activity_Mode mode)
void SetDuration (float newDuration, Timer_Activity_Mode activityMode)
float GetDuration (Timer_Activity_Mode activityMode)
float Elapsed (Timer_Activity_Mode activityMode)
float Remaining (Timer_Activity_Mode activityMode)
void Tick (Timer_Activity_Mode activityMode, float deltaTime)
bool IsRunning (Timer_Activity_Mode activityMode)
void Initialize (float defaultDuration=1.0f)
void ResetAll ()
override string ToString ()
Public Attributes
StopwatchTimer stopwatchTimer
DecrementTimer countdownTimer
IncrementTimer countUpTimer
Private Attributes
bool HasBeenInitialized
Constructor & Destructor Documentation
MultiTimer() [1/2]
IuvoUnity.DataStructs.MultiTimer.MultiTimer ()
            {
                HasBeenInitialized = false;
                stopwatchTimer = new StopwatchTimer();
                countdownTimer = new DecrementTimer();
                countUpTimer = new IncrementTimer();
                //loopingTimer = new LoopingTimer();
            }
References countdownTimer, countUpTimer, HasBeenInitialized, and stopwatchTimer.
MultiTimer() [2/2]
IuvoUnity.DataStructs.MultiTimer.MultiTimer (float defaultDuration)
            {
                HasBeenInitialized = false;
                stopwatchTimer = new StopwatchTimer();
                countdownTimer = new DecrementTimer(defaultDuration);
                countUpTimer = new IncrementTimer(defaultDuration);
                //loopingTimer = new LoopingTimer(defaultDuration, defaultDuration, true);
            }
References countdownTimer, countUpTimer, HasBeenInitialized, and stopwatchTimer.
Member Function Documentation
Dispose()
void IuvoUnity.DataStructs.MultiTimer.Dispose ()
            {
                stopwatchTimer.Dispose();
                countdownTimer.Dispose();
                countUpTimer.Dispose();
                //loopingTimer.Dispose();
            }
References countdownTimer, countUpTimer, and stopwatchTimer.
Elapsed()
float IuvoUnity.DataStructs.MultiTimer.Elapsed (Timer_Activity_Mode activityMode)
            {
                if (TimeKeeper.IsIncrement(activityMode))
                {
                    return countUpTimer.elapsed;
                }
                else if (TimeKeeper.IsDecrement(activityMode))
                {
                    return countdownTimer.duration - countdownTimer.remainingTime;
                }
                else if (TimeKeeper.IsStopwatch(activityMode))
                {
                    return stopwatchTimer.elapsed;
                }
                return 0f;
            }
References countdownTimer, countUpTimer, IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch(), and stopwatchTimer.
GetDuration()
float IuvoUnity.DataStructs.MultiTimer.GetDuration (Timer_Activity_Mode activityMode)
            {
                if (TimeKeeper.IsIncrement(activityMode))
                {
                    return countUpTimer.duration;
                }
                else if (TimeKeeper.IsDecrement(activityMode))
                {
                    return countdownTimer.duration;
                }
                else if (TimeKeeper.IsStopwatch(activityMode))
                {
                    IuvoDebug.DebugLogWarning("Stopwatch Timer has no set duration.");
                    return 0f; // Stopwatch has no set duration
                }
                else if (TimeKeeper.IsCustomTimer(activityMode))
                {
                    IuvoDebug.DebugLogWarning("Custom Timer has no set duration.");
                    return 0f; // Custom Timer has no set duration
                }
                return 0f;
            }
References countdownTimer, countUpTimer, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), IuvoUnity.IuvoTime.TimeKeeper.IsCustomTimer(), IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), and IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch().
Initialize()
void IuvoUnity.DataStructs.MultiTimer.Initialize (float defaultDuration = 1::0f)
            {
                if (HasBeenInitialized) return;
                HasBeenInitialized = true;
                stopwatchTimer = new StopwatchTimer { OnTick = new FlexibleEvent() };
                countdownTimer = new DecrementTimer { duration = defaultDuration, remainingTime = defaultDuration, OnFinished = new FlexibleEvent() };
                countUpTimer = new IncrementTimer { duration = defaultDuration, OnFinished = new FlexibleEvent() };
                ResetAll();
            }
References countdownTimer, countUpTimer, HasBeenInitialized, ResetAll(), and stopwatchTimer.
IsRunning()
bool IuvoUnity.DataStructs.MultiTimer.IsRunning (Timer_Activity_Mode activityMode)
            {
                if (TimeKeeper.IsIncrement(activityMode))
                {
                    return countUpTimer.IsRunning;
                }
                else if (TimeKeeper.IsDecrement(activityMode))
                {
                    return countdownTimer.IsRunning;
                }
                else if (TimeKeeper.IsStopwatch(activityMode))
                {
                    return stopwatchTimer.IsRunning;
                }
                return false;
            }
References countdownTimer, countUpTimer, IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch(), and stopwatchTimer.
Pause()
void IuvoUnity.DataStructs.MultiTimer.Pause (Timer_Activity_Mode mode)
            {
                if (TimeKeeper.IsIncrement(mode))
                {
                    countUpTimer.Pause();
                }
                else if (TimeKeeper.IsDecrement(mode))
                {
                    countdownTimer.Pause();
                }
                else if (TimeKeeper.IsStopwatch(mode))
                {
                    stopwatchTimer.Pause();
                }
                //else if (TimeKeeper.IsLoopingTimer(mode))
                //{
                //    if (loopingTimer.IsGoingUp) // Default to increment for looping timer
                //    {
                //        loopingTimer.incrementTimer.Pause();
                //    }
                //    else
                //    {
                //        loopingTimer.decrementTimer.Pause();
                //    }
                //}
            }
References countdownTimer, countUpTimer, IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch(), and stopwatchTimer.
Remaining()
float IuvoUnity.DataStructs.MultiTimer.Remaining (Timer_Activity_Mode activityMode)
            {
                if (TimeKeeper.IsIncrement(activityMode))
                {
                    return countUpTimer.duration - countUpTimer.elapsed;
                }
                else if (TimeKeeper.IsDecrement(activityMode))
                {
                    return countdownTimer.remainingTime;
                }
                else if (TimeKeeper.IsStopwatch(activityMode))
                {
                    IuvoDebug.DebugLogWarning("Stopwatch Timer has no remaining time.");
                    return 0f; // Stopwatch has no remaining time
                }
                return 0f;
            }
References countdownTimer, countUpTimer, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), and IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch().
Reset()
void IuvoUnity.DataStructs.MultiTimer.Reset (Timer_Activity_Mode mode)
            {
                if (TimeKeeper.IsIncrement(mode))
                {
                    countUpTimer.Reset();
                }
                else if (TimeKeeper.IsDecrement(mode))
                {
                    countdownTimer.Reset();
                }
                else if (TimeKeeper.IsStopwatch(mode))
                {
                    stopwatchTimer.Reset();
                }
                //else if (TimeKeeper.IsLoopingTimer(mode))
                //{
                //    loopingTimer.Reset(mode);
                //}
            }
References countdownTimer, countUpTimer, IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch(), and stopwatchTimer.
ResetAll()
void IuvoUnity.DataStructs.MultiTimer.ResetAll ()
            {
                stopwatchTimer.Reset();
                countdownTimer.Reset();
                countUpTimer.Reset();
            }
References countdownTimer, countUpTimer, and stopwatchTimer.
Referenced by Initialize().
Resume()
void IuvoUnity.DataStructs.MultiTimer.Resume (Timer_Activity_Mode mode)
            {
                if (TimeKeeper.IsIncrement(mode))
                {
                    countUpTimer.Resume();
                }
                else if (TimeKeeper.IsDecrement(mode))
                {
                    countdownTimer.Resume();
                }
                else if (TimeKeeper.IsStopwatch(mode))
                {
                    stopwatchTimer.Resume();
                }
                //else if (TimeKeeper.IsLoopingTimer(mode))
                //{
                //    if (loopingTimer.IsGoingUp) // Default to increment for looping timer
                //    {
                //        loopingTimer.incrementTimer.Resume();
                //    }
                //    else
                //    {
                //        loopingTimer.decrementTimer.Resume();
                //    }
                //}
            }
References countdownTimer, countUpTimer, IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch(), and stopwatchTimer.
SetDuration()
void IuvoUnity.DataStructs.MultiTimer.SetDuration (float newDuration, Timer_Activity_Mode activityMode)
            {
                if (TimeKeeper.IsIncrement(activityMode))
                {
                    if (newDuration <= 0)
                    {
                        IuvoDebug.DebugLogWarning("Count Up Timer duration must be greater than zero. Flipping value to positive");
                        newDuration = Mathf.Abs(newDuration);
                    }
                    countUpTimer.duration = newDuration;
                }
                else if (TimeKeeper.IsDecrement(activityMode))
                {
                    if (newDuration <= 0)
                    {
                        IuvoDebug.DebugLogWarning("Countdown Timer duration must be greater than zero. Flipping value to positive");
                        newDuration = Mathf.Abs(newDuration);
                    }
                    countdownTimer.duration = newDuration;
                    countdownTimer.remainingTime = newDuration;
                }
                else if (TimeKeeper.IsStopwatch(activityMode))
                {
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), and IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch().
Start()
void IuvoUnity.DataStructs.MultiTimer.Start (Timer_Activity_Mode mode)
            {
                if (TimeKeeper.IsIncrement(mode) && !countUpTimer.HasStarted)
                {
                    countUpTimer.Start();
                }
                else if (TimeKeeper.IsDecrement(mode) && !countdownTimer.HasStarted)
                {
                    countdownTimer.Start();
                }
                else if (TimeKeeper.IsStopwatch(mode) && !stopwatchTimer.HasStarted)
                {
                    stopwatchTimer.Start();
                }
                //else if (TimeKeeper.IsLoopingTimer(mode) && !loopingTimer.IsRunning)
                //{
                //    loopingTimer.Start(Timer_Activity_Mode.INCREMENT); // Default to increment for looping timer
                //}
            }
References countdownTimer, countUpTimer, IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch(), and stopwatchTimer.
Tick()
void IuvoUnity.DataStructs.MultiTimer.Tick (Timer_Activity_Mode activityMode, float deltaTime)
            {
                if (TimeKeeper.IsIncrement(activityMode) && countUpTimer.IsRunning)
                {
                    countUpTimer.Tick(deltaTime);
                }
                else if (TimeKeeper.IsDecrement(activityMode) && countdownTimer.IsRunning)
                {
                    countdownTimer.Tick(deltaTime);
                }
                else if (TimeKeeper.IsStopwatch(activityMode) && stopwatchTimer.IsRunning)
                {
                    stopwatchTimer.Tick(deltaTime);
                }
            }
References countdownTimer, countUpTimer, IuvoUnity.IuvoTime.TimeKeeper.IsDecrement(), IuvoUnity.IuvoTime.TimeKeeper.IsIncrement(), IuvoUnity.IuvoTime.TimeKeeper.IsStopwatch(), and stopwatchTimer.
ToString()
override string IuvoUnity.DataStructs.MultiTimer.ToString ()
            {
                return $"MultiTimer:\n {stopwatchTimer.ToString()}\n {countdownTimer.ToString()}\n {countUpTimer.ToString()}";
            }
Member Data Documentation
countdownTimer
DecrementTimer IuvoUnity.DataStructs.MultiTimer.countdownTimer
Referenced by Dispose(), Elapsed(), GetDuration(), Initialize(), IsRunning(), MultiTimer(), MultiTimer(), Pause(), Remaining(), Reset(), ResetAll(), Resume(), Start(), and Tick().
countUpTimer
IncrementTimer IuvoUnity.DataStructs.MultiTimer.countUpTimer
Referenced by Dispose(), Elapsed(), GetDuration(), Initialize(), IsRunning(), MultiTimer(), MultiTimer(), Pause(), Remaining(), Reset(), ResetAll(), Resume(), Start(), and Tick().
HasBeenInitialized
bool IuvoUnity.DataStructs.MultiTimer.HasBeenInitialized private
Referenced by Initialize(), MultiTimer(), and MultiTimer().
stopwatchTimer
StopwatchTimer IuvoUnity.DataStructs.MultiTimer.stopwatchTimer
Referenced by Dispose(), Elapsed(), Initialize(), IsRunning(), MultiTimer(), MultiTimer(), Pause(), Reset(), ResetAll(), Resume(), Start(), and Tick().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/MultiTimer.cs