Iuvo Unity: IuvoUnity.DataStructs.Timer Class Reference
IuvoUnity.DataStructs.Timer Class Reference
Public Member Functions
void SetDuration (float newDuration)
float Duration ()
float Elapsed ()
float Remaining ()
bool IsRunning (Timer_Activity_Mode activityMode)
void StartTimer ()
async Task AwaitFinish ()
void UpdateTimer ()
virtual void Update ()
virtual void FixedUpdate ()
virtual void LateUpdate ()
void PauseTimer ()
void ResumeTimer ()
void ResetTimer ()
void OnCreate ()
void OnDestroy ()
void Destroy ()
void ConfigureTimer (TimerData timerData)
virtual void OnConfigure ()
virtual void OnReconfigure ()
Public Attributes
Timer_Activity_Mode activityMode
Tick_Mode tickMode
MultiTimer timer
Properties
bool Configured [get, set]
bool Reconfigured [get, set]
Private Member Functions
void InitTimer ()
void Awake ()
Member Function Documentation
AwaitFinish()
async Task IuvoUnity.DataStructs.Timer.AwaitFinish ()
            {
                var tcs = new TaskCompletionSource<bool>();
                void Handler()
                {
                    tcs.TrySetResult(true);
                }
                if (activityMode == Timer_Activity_Mode.INCREMENT)
                {
                    timer.countUpTimer.OnFinished.AddListener(Handler);
                }
                else if (activityMode == Timer_Activity_Mode.DECREMENT)
                {
                    timer.countdownTimer.OnFinished.AddListener(Handler);
                }
                else
                {
                    throw new System.NotSupportedException("Stopwatch timer does not finish by itself.");
                }
                if (!timer.IsRunning(activityMode))
                {
                    StartTimer();
                }
                else if (timer.IsRunning(activityMode))
                {
                    IuvoDebug.DebugLogWarning("Timer is already running. AwaitFinish will return when the current timer finishes.");
                }
                await tcs.Task;
                // Cleanup listener
                if (activityMode == Timer_Activity_Mode.INCREMENT)
                {
                    timer.countUpTimer.OnFinished.RemoveListener(Handler);
                }
                else if (activityMode == Timer_Activity_Mode.DECREMENT)
                {
                    timer.countdownTimer.OnFinished.RemoveListener(Handler);
                }
            }
References activityMode, IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), StartTimer(), and timer.
Awake()
void IuvoUnity.DataStructs.Timer.Awake () private
=> InitTimer();
ConfigureTimer()
void IuvoUnity.DataStructs.Timer.ConfigureTimer (TimerData timerData)
            {
                activityMode = timerData.activityMode;
                tickMode = timerData.tickMethod;
                ResetTimer();
                SetDuration(timerData.duration);
            }
References IuvoUnity.Configurations.TimerData.activityMode, activityMode, IuvoUnity.Configurations.TimerData.duration, ResetTimer(), SetDuration(), IuvoUnity.Configurations.TimerData.tickMethod, and tickMode.
Referenced by IuvoUnity.Configurations.TimerConfiguration.Configure(), and IuvoUnity.Configurations.TimerConfiguration.Reconfigure().
Destroy()
void IuvoUnity.DataStructs.Timer.Destroy ()
            {
                Destroy(this);
            }
References Destroy().
Referenced by Destroy().
Duration()
float IuvoUnity.DataStructs.Timer.Duration ()
            {
                return timer.GetDuration(activityMode);
            }
References activityMode, and timer.
Referenced by IuvoUnity.IuvoTime.TimeKeeper.FormatTimerDuration().
Elapsed()
float IuvoUnity.DataStructs.Timer.Elapsed ()
            {
                return timer.Elapsed(activityMode);
            }
References activityMode, and timer.
Referenced by IuvoUnity.IuvoTime.TimeKeeper.FormatElapsedTime().
FixedUpdate()
virtual void IuvoUnity.DataStructs.Timer.FixedUpdate () virtual
            {
                if (tickMode == Tick_Mode.TICK_ON_FIXED_UPDATE)
                {
                    UpdateTimer();
                }
            }
References tickMode, and UpdateTimer().
InitTimer()
void IuvoUnity.DataStructs.Timer.InitTimer () private
            {
                timer = new MultiTimer();
                timer.Initialize();
            }
References timer.
IsRunning()
bool IuvoUnity.DataStructs.Timer.IsRunning (Timer_Activity_Mode activityMode)
            {
                return timer.IsRunning(activityMode);
            }
References activityMode, and timer.
LateUpdate()
virtual void IuvoUnity.DataStructs.Timer.LateUpdate () virtual
            {
                if (tickMode == Tick_Mode.TICK_ON_LATE_UPDATE)
                {
                    UpdateTimer();
                }
            }
References tickMode, and UpdateTimer().
OnConfigure()
virtual void IuvoUnity.DataStructs.Timer.OnConfigure () virtual
Implements IuvoUnity.Interfaces.IConfigurable.
            {
                Configured = true;
            }
References Configured.
Referenced by IuvoUnity.Configurations.TimerConfiguration.Configure(), and IuvoUnity.IuvoTime.TimerFactory.Create().
OnCreate()
void IuvoUnity.DataStructs.Timer.OnCreate ()
Implements IuvoUnity.Interfaces.ICreatable.
=> InitTimer();
Referenced by IuvoUnity.IuvoTime.TimerFactory.Create().
OnDestroy()
void IuvoUnity.DataStructs.Timer.OnDestroy ()
Implements IuvoUnity.Interfaces.IDestructible.
            {
                timer.Dispose();
            }
References timer.
OnReconfigure()
virtual void IuvoUnity.DataStructs.Timer.OnReconfigure () virtual
Implements IuvoUnity.Interfaces.IReconfigurable.
            {
                Reconfigured = true;
            }
References Reconfigured.
Referenced by IuvoUnity.Configurations.TimerConfiguration.Reconfigure().
PauseTimer()
void IuvoUnity.DataStructs.Timer.PauseTimer ()
            {
                timer.Pause(activityMode);
            }
References activityMode, and timer.
Remaining()
float IuvoUnity.DataStructs.Timer.Remaining ()
            {
                return timer.Remaining(activityMode);
            }
References activityMode, and timer.
Referenced by IuvoUnity.IuvoTime.TimeKeeper.FormatRemainingTime().
ResetTimer()
void IuvoUnity.DataStructs.Timer.ResetTimer ()
            {
                timer.Reset(activityMode);
            }
References activityMode, and timer.
Referenced by ConfigureTimer().
ResumeTimer()
void IuvoUnity.DataStructs.Timer.ResumeTimer ()
            {
                timer.Resume(activityMode);
            }
References activityMode, and timer.
SetDuration()
void IuvoUnity.DataStructs.Timer.SetDuration (float newDuration)
            {
                timer.SetDuration(newDuration, activityMode);
            }
References activityMode, and timer.
Referenced by ConfigureTimer().
StartTimer()
void IuvoUnity.DataStructs.Timer.StartTimer ()
            {
                timer.Start(activityMode);
            }
References activityMode, and timer.
Referenced by AwaitFinish().
Update()
virtual void IuvoUnity.DataStructs.Timer.Update () virtual
            {
                if (tickMode == Tick_Mode.TICK_ON_UPDATE)
                {
                    UpdateTimer();
                }
            }
References tickMode, and UpdateTimer().
UpdateTimer()
void IuvoUnity.DataStructs.Timer.UpdateTimer ()
            {
                timer.Tick(activityMode, Time.deltaTime);
            }
References activityMode, and timer.
Referenced by FixedUpdate(), LateUpdate(), and Update().
Member Data Documentation
activityMode
Timer_Activity_Mode IuvoUnity.DataStructs.Timer.activityMode
Referenced by AwaitFinish(), ConfigureTimer(), Duration(), Elapsed(), IsRunning(), PauseTimer(), Remaining(), ResetTimer(), ResumeTimer(), SetDuration(), StartTimer(), and UpdateTimer().
tickMode
Tick_Mode IuvoUnity.DataStructs.Timer.tickMode
Referenced by ConfigureTimer(), FixedUpdate(), LateUpdate(), and Update().
timer
MultiTimer IuvoUnity.DataStructs.Timer.timer
Referenced by AwaitFinish(), Duration(), Elapsed(), InitTimer(), IsRunning(), OnDestroy(), PauseTimer(), Remaining(), ResetTimer(), ResumeTimer(), SetDuration(), StartTimer(), and UpdateTimer().
Property Documentation
Configured
bool IuvoUnity.DataStructs.Timer.Configured get set
Implements IuvoUnity.Interfaces.IConfigurable.
{ get; set; }
Referenced by OnConfigure().
Reconfigured
bool IuvoUnity.DataStructs.Timer.Reconfigured get set
Implements IuvoUnity.Interfaces.IReconfigurable.
{ get; set; }
Referenced by OnReconfigure().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/TImer.cs