Iuvo Unity: IuvoUnity.Debug.TestDebugButton Class Reference
IuvoUnity.Debug.TestDebugButton Class Reference
Public Attributes
DebugButton myButton = new DebugButton { Label = "Do Something" }
Private Member Functions
void Awake ()
void TestFunction ()
Member Function Documentation
Awake()
void IuvoUnity.Debug.TestDebugButton.Awake () private
            {
                IuvoDebug.Initialize();
                myButton.OnClick.AddListener(TestFunction);
            }
References IuvoUnity.Debug.IuvoDebug.Initialize(), myButton, and TestFunction().
TestFunction()
void IuvoUnity.Debug.TestDebugButton.TestFunction () private
            {
                IuvoDebug.DebugLog("");
                IuvoDebug.DebugLog("This is a log message.");
                IuvoDebug.DebugLog("This is a log message with rich text.", true);
                IuvoDebug.DebugLogWarning("");
                IuvoDebug.DebugLogWarning("This is a warning message.");
                IuvoDebug.DebugLogWarning("This is a warning message with rich text.", true);
                IuvoDebug.DebugLogError("");
                IuvoDebug.DebugLogError("This is an error message.");
                IuvoDebug.DebugLogError("This is an error message with rich text.", true);
                IuvoDebug.DebugLogIuvoVersion();
                IuvoGame gameInstance = FindAnyObjectByType<IuvoGame>();
                if (gameInstance != null)
                {
                    IuvoDebug.DebugIuvoGame(gameInstance);
                }
                else
                {
                    IuvoDebug.DebugLogWarning("No IuvoGame instance found in the scene.");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugIuvoGame(), IuvoUnity.Debug.IuvoDebug.DebugLog(), IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.Debug.IuvoDebug.DebugLogIuvoVersion(), and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
Referenced by Awake().
Member Data Documentation
myButton
DebugButton IuvoUnity.Debug.TestDebugButton.myButton = new DebugButton { Label = "Do Something" }
{ Label = "Do Something" };
Referenced by Awake().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Debug/TestDebugButton.cs