Iuvo Unity: IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry Class Reference
IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry Class Reference
Static Public Member Functions
static IuvoEntity CreateEntity (bool debugOn=true)
static void DestroyEntity (int entityId)
static IuvoEntity CreateTimerEntity (bool debugOn=true, IuvoEntity parent=null)
static void InitializeDefaultComponents (IuvoEntity entity)
static void BreakdownRemovableComponents (IuvoEntity entity)
static bool FindIuvoEntityInRegister (IuvoEntity entity, out bool isTimer)
Static Public Attributes
static Dictionary< int, IuvoEntity > _myRegisteredEntities = new Dictionary<int, IuvoEntity>()
static Dictionary< int, IuvoEntity > _myRegisteredTimers = new Dictionary<int, IuvoEntity>()
Properties
static int _myRegistryID = 0 [get, set]
Static Private Attributes
static int _nextEntityID = 0
static int _nextTimerID = 0
Member Function Documentation
BreakdownRemovableComponents()
void IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry.BreakdownRemovableComponents (IuvoEntity entity) static
                {
                    List<IuvoComponentBase> comps = entity._ComponentManager.GetAllComponents();
                    for (int i = 0; i < comps.Count; i++)
                    {
                    }
                }
References IuvoUnity.BaseClasses.ECS.IuvoEntity._ComponentManager, and IuvoUnity.BaseClasses.ECS.ComponentManager.GetAllComponents().
Referenced by DestroyEntity().
CreateEntity()
IuvoEntity IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry.CreateEntity (bool debugOn = true) static
                {
                    var entity = IuvoEntity.CreateFromRegistry();
                    // always double check that the registry doesnt have that ID
                    while (_myRegisteredEntities.ContainsKey(_nextEntityID))
                    {
                        _nextEntityID++;
                    }
                    // assign the id if checks passed
                    entity._ID = _nextEntityID;
                    // always increment the id...
                    _nextEntityID++;
                    // Create the component manager and assign its entity reference
                    entity._ComponentManager = new ComponentManager(entity);
                    // Register in entity database
                    _myRegisteredEntities.Add(entity._ID, entity);
                    //IuvoDebug.Debugger debugger = new IuvoDebug.Debugger();         // default # 1
                    //entity.AddComponent<IuvoDebug.Debugger>(debugger);
                    // Maps this entity to the creating registry
                    IuvoRegistryID identification = new IuvoRegistryID();           // default # 2
                    identification._id = _myRegistryID;
                    entity.AddComponent(identification);
                    // do initialization of default components
                    InitializeDefaultComponents(entity);
                    // ...and finally return the new entity
                    return entity;
                }
References _myRegisteredEntities, _myRegistryID, _nextEntityID, and InitializeDefaultComponents().
Referenced by CreateTimerEntity().
CreateTimerEntity()
IuvoEntity IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry.CreateTimerEntity (bool debugOn = true, IuvoEntity parent = null) static
                {
                    var timer = CreateEntity(debugOn);
                    while (_myRegisteredTimers.ContainsKey(_nextTimerID))
                    {
                        _nextTimerID++;
                    }
                    // Maps this entity as a timer
                    IuvoWorldID worldID = new IuvoWorldID();
                    IuvoTimerID iuvoTimerID = new IuvoTimerID();                // default # 1
                    iuvoTimerID._id = _nextTimerID;
                    worldID._timerID = iuvoTimerID;
                    while (_myRegisteredEntities.ContainsKey(_nextEntityID))
                    {
                        _nextEntityID++;
                    }
                    if (parent == null)
                    {
                        worldID._entity = timer;
                    }
                    else
                    {
                        worldID._entity = parent;
                    }
                    timer._ComponentManager.TryGetComponent<IuvoRegistryID>(out var registryID);
                    worldID._registryID = registryID;
                    timer._ComponentManager.AddComponent<IuvoWorldID>(worldID);
                    // do initialization of default components
                    InitializeDefaultComponents(timer);
                    // ...and finally return the new entity
                    return timer;
                }
References _myRegisteredEntities, _myRegisteredTimers, _nextEntityID, _nextTimerID, CreateEntity(), and InitializeDefaultComponents().
Referenced by IuvoUnity.BaseClasses.ECS.IuvoTimer.IuvoTimer().
DestroyEntity()
void IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry.DestroyEntity (int entityId) static
                {
                    if (_myRegisteredEntities.TryGetValue(entityId, out var entity))
                    {
                        // cleanup default components
                        BreakdownRemovableComponents(entity);
                        // Finally destroy the held components and erase knowledge of the entity
                        entity._ComponentManager.ClearComponentManager(entity);
                        _myRegisteredEntities.Remove(entityId);
                    }
                }
References _myRegisteredEntities, and BreakdownRemovableComponents().
FindIuvoEntityInRegister()
bool IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry.FindIuvoEntityInRegister (IuvoEntity entity, out bool isTimer) static
                {
                    if (_myRegisteredEntities.ContainsKey(entity._ID))
                    {
                        return isTimer = false;
                    }
                    else if (_myRegisteredTimers.ContainsKey(entity._ID))
                    {
                        return isTimer = true;
                    }
                    else
                    {
                        return isTimer = false;
                    }
                }
References IuvoUnity.BaseClasses.ECS.IuvoEntity._ID, _myRegisteredEntities, and _myRegisteredTimers.
InitializeDefaultComponents()
void IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry.InitializeDefaultComponents (IuvoEntity entity) static
                {
                    List<IuvoComponentBase> comps = entity._ComponentManager.GetAllComponents();
                    for (int i = 0; i < comps.Count; i++)
                    {
                    }
                }
References IuvoUnity.BaseClasses.ECS.IuvoEntity._ComponentManager, and IuvoUnity.BaseClasses.ECS.ComponentManager.GetAllComponents().
Referenced by CreateEntity(), and CreateTimerEntity().
Member Data Documentation
_myRegisteredEntities
Dictionary<int, IuvoEntity> IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry._myRegisteredEntities = new Dictionary<int, IuvoEntity>() static
Referenced by CreateEntity(), CreateTimerEntity(), DestroyEntity(), and FindIuvoEntityInRegister().
_myRegisteredTimers
Dictionary<int, IuvoEntity> IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry._myRegisteredTimers = new Dictionary<int, IuvoEntity>() static
Referenced by CreateTimerEntity(), and FindIuvoEntityInRegister().
_nextEntityID
int IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry._nextEntityID = 0 static private
Referenced by CreateEntity(), and CreateTimerEntity().
_nextTimerID
int IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry._nextTimerID = 0 static private
Referenced by CreateTimerEntity().
Property Documentation
_myRegistryID
int IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry._myRegistryID = 0 static get set
{ get; set; } = 0;
Referenced by CreateEntity().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ECS/Entities/IuvoEntityRegistry.cs