Iuvo Unity: IuvoUnity.DataStructs.StopwatchTimer Class Reference
IuvoUnity.DataStructs.StopwatchTimer Class Reference
Public Member Functions
StopwatchTimer ()
void Dispose ()
void Start ()
void Restart ()
void Pause ()
void Resume ()
void Reset ()
void Tick (float deltaTime)
void AddLap ()
void AddSplitLap ()
void AddAbsoluteLap ()
override string ToString ()
Public Attributes
float elapsed
List< float > splitLaps = new List<float>()
List< float > absoluteLaps = new List<float>()
bool HasStarted
bool IsPaused
FlexibleEvent OnTick
Properties
bool IsRunning [get]
Constructor & Destructor Documentation
StopwatchTimer()
IuvoUnity.DataStructs.StopwatchTimer.StopwatchTimer ()
            {
                elapsed = 0.0f;
                HasStarted = false;
                IsPaused = false;
                OnTick = new FlexibleEvent();
            }
References elapsed, HasStarted, IsPaused, and OnTick.
Member Function Documentation
AddAbsoluteLap()
void IuvoUnity.DataStructs.StopwatchTimer.AddAbsoluteLap ()
            {
                absoluteLaps.Add(elapsed);
            }
References absoluteLaps, and elapsed.
Referenced by AddLap().
AddLap()
void IuvoUnity.DataStructs.StopwatchTimer.AddLap ()
            {
                AddSplitLap();
                AddAbsoluteLap();
            }
References AddAbsoluteLap(), and AddSplitLap().
AddSplitLap()
void IuvoUnity.DataStructs.StopwatchTimer.AddSplitLap ()
            {
                float val = elapsed;
                if (splitLaps.Count > 0)
                {
                    val -= splitLaps[splitLaps.Count - 1];
                }
                splitLaps.Add(val);
            }
References elapsed, and splitLaps.
Referenced by AddLap().
Dispose()
void IuvoUnity.DataStructs.StopwatchTimer.Dispose ()
            {
                OnTick.RemoveAllFlexibleEventListeners();
            }
References OnTick.
Pause()
void IuvoUnity.DataStructs.StopwatchTimer.Pause ()
=> IsPaused = true;
References IsPaused.
Reset()
void IuvoUnity.DataStructs.StopwatchTimer.Reset ()
            {
                elapsed = 0;
                HasStarted = false;
                IsPaused = false;
                splitLaps?.Clear();
                absoluteLaps?.Clear();
            }
References absoluteLaps, elapsed, HasStarted, IsPaused, and splitLaps.
Referenced by Restart().
Restart()
void IuvoUnity.DataStructs.StopwatchTimer.Restart ()
            {
                Reset();
                HasStarted = true;
                IsPaused = false;
            }
References HasStarted, IsPaused, and Reset().
Resume()
void IuvoUnity.DataStructs.StopwatchTimer.Resume ()
=> IsPaused = false;
References IsPaused.
Start()
void IuvoUnity.DataStructs.StopwatchTimer.Start ()
            {
                if (HasStarted) return;
                HasStarted = true;
                IsPaused = false;
            }
References HasStarted, and IsPaused.
Tick()
void IuvoUnity.DataStructs.StopwatchTimer.Tick (float deltaTime)
            {
                if (!IsRunning) return;
                elapsed += deltaTime;
                OnTick.Invoke();
            }
References elapsed, IsRunning, and OnTick.
ToString()
override string IuvoUnity.DataStructs.StopwatchTimer.ToString ()
            {
                return $"StopwatchTimer: Elapsed={elapsed}, HasStarted={HasStarted}, IsPaused={IsPaused}, IsRunning={IsRunning}, SplitLapsCount={(splitLaps != null ? splitLaps.Count : 0)}, AbsoluteLapsCount={(absoluteLaps != null ? absoluteLaps.Count : 0)}";
            }
Member Data Documentation
absoluteLaps
List<float> IuvoUnity.DataStructs.StopwatchTimer.absoluteLaps = new List<float>()
Referenced by AddAbsoluteLap(), and Reset().
elapsed
float IuvoUnity.DataStructs.StopwatchTimer.elapsed
Referenced by AddAbsoluteLap(), AddSplitLap(), Reset(), StopwatchTimer(), and Tick().
HasStarted
bool IuvoUnity.DataStructs.StopwatchTimer.HasStarted
Referenced by Reset(), Restart(), Start(), and StopwatchTimer().
IsPaused
bool IuvoUnity.DataStructs.StopwatchTimer.IsPaused
Referenced by Pause(), Reset(), Restart(), Resume(), Start(), and StopwatchTimer().
OnTick
FlexibleEvent IuvoUnity.DataStructs.StopwatchTimer.OnTick
Referenced by Dispose(), StopwatchTimer(), and Tick().
splitLaps
List<float> IuvoUnity.DataStructs.StopwatchTimer.splitLaps = new List<float>()
Referenced by AddSplitLap(), and Reset().
Property Documentation
IsRunning
bool IuvoUnity.DataStructs.StopwatchTimer.IsRunning get
Referenced by Tick().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/StopwatchTimer.cs