Iuvo Unity: IuvoUnity.Extensions.MaterialExtensions Class Reference
IuvoUnity.Extensions.MaterialExtensions Class Reference
Provides extension methods for working with Unity Materials.
Static Public Member Functions
static void WithMainColor (this Material material, Color color)
Sets the main color of the material, if the "_Color" property exists.
static void WithMainTexture (this Material material, Texture texture)
Sets the main texture of the material, if the "_MainTex" property exists.
static void WithMainTextureOffset (this Material material, Vector2 offset)
Sets the offset of the main texture, if the "_MainTex" property exists.
static void WithMainTextureScale (this Material material, Vector2 scale)
Sets the scale of the main texture, if the "_MainTex" property exists.
static void WithMainTextureTiling (this Material material, Vector2 tiling)
Sets the tiling (scale) of the main texture.
static void WithMetallic (this Material material, float metallic)
Sets the metallic value of the material, clamped between 0 and 1.
static void WithEmissionColor (this Material material, Color color)
Sets the emission color of the material, if the "_EmissionColor" property exists.
static void WithShader (this Material material, Shader shader)
Sets the shader of the material.
static void WithShader (this Material material, string shaderName)
static void WithShader (this Material material, string shaderName, string fallbackShaderName)
Sets the shader of the material by name, falling back to a secondary shader if the first is not found.
static void WithRenderingMode (this Material material, int mode)
Sets the rendering mode of the material using the "_Mode" property.
static void WithBuffer (this Material material, string propertyName, ComputeBuffer buffer)
Sets a compute buffer on the material.
static void WithColorArray (this Material material, string propertyName, Color[] colors)
Sets a color array on the material.
static void WithFloatArray (this Material material, string propertyName, float[] values)
Sets a float array on the material.
static void WithMatrixArray (this Material material, string propertyName, Matrix4x4[] matrices)
Sets a matrix array on the material.
static void WithTextureArray (this Material material, string propertyName, Texture2DArray textures)
Sets a texture array (Texture2DArray) on the material.
static void WithVectorArray (this Material material, string propertyName, Vector4[] vectors)
Sets a vector array on the material.
Detailed Description
Provides extension methods for working with Unity Materials.
Member Function Documentation
WithBuffer()
void IuvoUnity.Extensions.MaterialExtensions.WithBuffer (this Material material, string propertyName, ComputeBuffer buffer) static
Sets a compute buffer on the material.
Parameters
material The material to modify.
propertyName The shader property name.
buffer The compute buffer.
            {
                if (material.HasProperty(propertyName))
                    material.SetBuffer(propertyName, buffer);
                else
                    IuvoDebug.DebugLogWarning($"Material '{material.name}' does not have property '{propertyName}' for ComputeBuffer.");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
WithColorArray()
void IuvoUnity.Extensions.MaterialExtensions.WithColorArray (this Material material, string propertyName, Color[] colors) static
Sets a color array on the material.
Parameters
material The material to modify.
propertyName The shader property name.
colors The array of colors.
            {
                if (material.HasProperty(propertyName))
                    material.SetColorArray(propertyName, colors);
            }
WithEmissionColor()
void IuvoUnity.Extensions.MaterialExtensions.WithEmissionColor (this Material material, Color color) static
Sets the emission color of the material, if the "_EmissionColor" property exists.
Parameters
material The material to modify.
color The emission color.
            {
                if (material.HasProperty("_EmissionColor"))
                    material.SetColor("_EmissionColor", color);
            }
WithFloatArray()
void IuvoUnity.Extensions.MaterialExtensions.WithFloatArray (this Material material, string propertyName, float[] values) static
Sets a float array on the material.
Parameters
material The material to modify.
propertyName The shader property name.
values The array of float values.
            {
                if (material.HasProperty(propertyName))
                    material.SetFloatArray(propertyName, values);
            }
WithMainColor()
void IuvoUnity.Extensions.MaterialExtensions.WithMainColor (this Material material, Color color) static
Sets the main color of the material, if the "_Color" property exists.
Parameters
material The material to modify.
color The color to apply.
            {
                if (material.HasProperty("_Color"))
                    material.SetColor("_Color", color);
                else
                    IuvoDebug.DebugLogWarning($"Material '{material.name}' does not have a _Color property.");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
WithMainTexture()
void IuvoUnity.Extensions.MaterialExtensions.WithMainTexture (this Material material, Texture texture) static
Sets the main texture of the material, if the "_MainTex" property exists.
Parameters
material The material to modify.
texture The texture to assign.
            {
                if (material.HasProperty("_MainTex"))
                    material.SetTexture("_MainTex", texture);
                else
                    IuvoDebug.DebugLogWarning($"Material '{material.name}' does not have a _MainTex property.");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
WithMainTextureOffset()
void IuvoUnity.Extensions.MaterialExtensions.WithMainTextureOffset (this Material material, Vector2 offset) static
Sets the offset of the main texture, if the "_MainTex" property exists.
Parameters
material The material to modify.
offset The texture offset.
            {
                if (material.HasProperty("_MainTex"))
                    material.SetTextureOffset("_MainTex", offset);
            }
WithMainTextureScale()
void IuvoUnity.Extensions.MaterialExtensions.WithMainTextureScale (this Material material, Vector2 scale) static
Sets the scale of the main texture, if the "_MainTex" property exists.
Parameters
material The material to modify.
scale The texture scale.
            {
                if (material.HasProperty("_MainTex"))
                    material.SetTextureScale("_MainTex", scale);
            }
WithMainTextureTiling()
void IuvoUnity.Extensions.MaterialExtensions.WithMainTextureTiling (this Material material, Vector2 tiling) static
Sets the tiling (scale) of the main texture.
Parameters
material The material to modify.
tiling The tiling vector.
            {
                material.WithMainTextureScale(tiling);
            }
WithMatrixArray()
void IuvoUnity.Extensions.MaterialExtensions.WithMatrixArray (this Material material, string propertyName, Matrix4x4[] matrices) static
Sets a matrix array on the material.
Parameters
material The material to modify.
propertyName The shader property name.
matrices The array of matrices.
            {
                if (material.HasProperty(propertyName))
                    material.SetMatrixArray(propertyName, matrices);
            }
WithMetallic()
void IuvoUnity.Extensions.MaterialExtensions.WithMetallic (this Material material, float metallic) static
Sets the metallic value of the material, clamped between 0 and 1.
Parameters
material The material to modify.
metallic The metallic value.
            {
                if (material.HasProperty("_Metallic"))
                    material.SetFloat("_Metallic", Mathf.Clamp01(metallic));
            }
WithRenderingMode()
void IuvoUnity.Extensions.MaterialExtensions.WithRenderingMode (this Material material, int mode) static
Sets the rendering mode of the material using the "_Mode" property.
Parameters
material The material to modify.
mode The rendering mode (typically 0=Opaque, 1=Cutout, 2=Fade, 3=Transparent).
            {
                if (material.HasProperty("_Mode"))
                {
                    material.SetInt("_Mode", mode);
                }
                else
                {
                    IuvoDebug.DebugLogWarning($"Material '{material.name}' does not support '_Mode'. Use a compatible shader for transparency.");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
WithShader() [1/3]
void IuvoUnity.Extensions.MaterialExtensions.WithShader (this Material material, Shader shader) static
Sets the shader of the material.
Parameters
material The material to modify.
shader The shader to assign.
            {
                if (shader != null)
                {
                    material.shader = shader;
                }
                else
                {
                    IuvoDebug.DebugLogWarning($"Null shader passed to material '{material.name}'. Shader not changed.");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
WithShader() [2/3]
void IuvoUnity.Extensions.MaterialExtensions.WithShader (this Material material, string shaderName) static
<summary Sets the shader of the material by shader name.
Parameters
material The material to modify.
shaderName The name of the shader.
            {
                Shader shader = Shader.Find(shaderName);
                if (shader != null)
                {
                    material.shader = shader;
                }
                else
                {
                    IuvoDebug.DebugLogWarning($"Shader '{shaderName}' not found. Material '{material.name}' was not updated.");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
WithShader() [3/3]
void IuvoUnity.Extensions.MaterialExtensions.WithShader (this Material material, string shaderName, string fallbackShaderName) static
Sets the shader of the material by name, falling back to a secondary shader if the first is not found.
Parameters
material The material to modify.
shaderName The primary shader name.
fallbackShaderName The fallback shader name.
            {
                Shader shader = Shader.Find(shaderName);
                if (shader == null)
                {
                    IuvoDebug.DebugLogWarning($"Shader '{shaderName}' not found. Falling back to '{fallbackShaderName}'.");
                    shader = Shader.Find(fallbackShaderName);
                }
                if (shader != null)
                {
                    material.shader = shader;
                }
                else
                {
                    IuvoDebug.DebugLogError($"Both shader '{shaderName}' and fallback '{fallbackShaderName}' not found. Material '{material.name}' shader not changed.");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
WithTextureArray()
void IuvoUnity.Extensions.MaterialExtensions.WithTextureArray (this Material material, string propertyName, Texture2DArray textures) static
Sets a texture array (Texture2DArray) on the material.
Parameters
material The material to modify.
propertyName The shader property name.
textures The texture array to assign.
            {
                if (material.HasProperty(propertyName))
                    material.SetTexture(propertyName, textures);
                else
                    IuvoDebug.DebugLogWarning($"Material '{material.name}' does not support texture arrays at '{propertyName}'.");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
WithVectorArray()
void IuvoUnity.Extensions.MaterialExtensions.WithVectorArray (this Material material, string propertyName, Vector4[] vectors) static
Sets a vector array on the material.
Parameters
material The material to modify.
propertyName The shader property name.
vectors The array of vectors.
            {
                if (material.HasProperty(propertyName))
                    material.SetVectorArray(propertyName, vectors);
            }
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Extensions/MaterialExtensions.cs