Iuvo Unity: IuvoUnity.DataStructs.Link< T > Class Template Reference
IuvoUnity.DataStructs.Link< T > Class Template Reference
Public Member Functions
Link ()
Link (T data)
void SetData (T data)
T GetData ()
void SetNext (Link< T > next)
void SetPrevious (Link< T > prev)
Link< T > TryGetNext ()
Link< T > TryGetPrevious ()
bool IsNextNull ()
bool IsPreviousNull ()
IEnumerable< Link< T > > TraverseForward (int maxSteps=1000)
Link< T > Clone ()
Private Attributes
T _data
Link< T > _previous
Link< T > _next
Member Function Documentation
Clone()
Link< T > IuvoUnity.DataStructs.Link< T >.Clone ()
            {
                return new Link<T>(_data);
            }
References _data, and Link().
GetData()
T IuvoUnity.DataStructs.Link< T >.GetData ()
=> _data;
References _data.
IsNextNull()
bool IuvoUnity.DataStructs.Link< T >.IsNextNull ()
=> _next == null;
References _next.
IsPreviousNull()
bool IuvoUnity.DataStructs.Link< T >.IsPreviousNull ()
=> _previous == null;
References _previous.
Link() [1/2]
IuvoUnity.DataStructs.Link< T >.Link ()
            {
                SetData(default);
                _previous = null;
                _next = null;
            }
References _next, _previous, and SetData().
Referenced by Clone(), SetNext(), SetPrevious(), TryGetNext(), and TryGetPrevious().
Link() [2/2]
IuvoUnity.DataStructs.Link< T >.Link (T data)
            {
                SetData(data);
                _previous = null;
                _next = null;
            }
References _next, _previous, and SetData().
SetData()
void IuvoUnity.DataStructs.Link< T >.SetData (T data)
=> _data = data;
References _data.
Referenced by Link(), and Link().
SetNext()
void IuvoUnity.DataStructs.Link< T >.SetNext (Link< T > next)
            {
                _next = next;
                next._previous = this;
            }
References _next, and Link().
Referenced by IuvoUnity.DataStructs.Chain< T >.InsertAt(), IuvoUnity.DataStructs.Chain< T >.PushBack(), IuvoUnity.DataStructs.Chain< T >.PushFront(), and IuvoUnity.DataStructs.Chain< T >.Remove().
SetPrevious()
void IuvoUnity.DataStructs.Link< T >.SetPrevious (Link< T > prev)
            {
                _previous = prev;
                prev._next = this;
            }
References _previous, and Link().
Referenced by IuvoUnity.DataStructs.Chain< T >.InsertAt(), IuvoUnity.DataStructs.Chain< T >.PushBack(), IuvoUnity.DataStructs.Chain< T >.PushFront(), and IuvoUnity.DataStructs.Chain< T >.Remove().
TraverseForward()
IEnumerable< Link< T > > IuvoUnity.DataStructs.Link< T >.TraverseForward (int maxSteps = 1000)
            {
                var current = this;
                int count = 0;
                while (current != null && count++ < maxSteps)
                {
                    yield return current;
                    current = current.TryGetNext();
                }
            }
TryGetNext()
Link< T > IuvoUnity.DataStructs.Link< T >.TryGetNext ()
=> _next;
References _next, and Link().
Referenced by IuvoUnity.DataStructs.Chain< T >.Remove().
TryGetPrevious()
Link< T > IuvoUnity.DataStructs.Link< T >.TryGetPrevious ()
=> _previous;
References _previous, and Link().
Referenced by IuvoUnity.DataStructs.Chain< T >.Remove().
Member Data Documentation
_data
T IuvoUnity.DataStructs.Link< T >._data private
Referenced by Clone(), GetData(), and SetData().
_next
Link<T> IuvoUnity.DataStructs.Link< T >._next private
Referenced by IsNextNull(), Link(), Link(), SetNext(), and TryGetNext().
_previous
Link<T> IuvoUnity.DataStructs.Link< T >._previous private
Referenced by IsPreviousNull(), Link(), Link(), SetPrevious(), and TryGetPrevious().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/Link.cs