Iuvo Unity: IuvoUnity.RPG.Stat Class Reference
IuvoUnity.RPG.Stat Class Reference
Public Member Functions
string GetStatName ()
void SetStatName (string newName)
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
string statName = "New Stat"
Member Function Documentation
GetStatName()
string IuvoUnity.RPG.Stat.GetStatName ()
=> statName;
References statName.
OnDisable()
virtual void IuvoUnity.RPG.Stat.OnDisable () virtual
            {
                // This method can be overridden in derived classes for cleanup
                IuvoDebug.DebugLog($"Stat {statName} disabled.");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog().
OnEnable()
virtual void IuvoUnity.RPG.Stat.OnEnable () virtual
            {
                // This method can be overridden in derived classes for initialization
                IuvoDebug.DebugLog($"Stat {statName} enabled.");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog().
SetStatName()
void IuvoUnity.RPG.Stat.SetStatName (string newName)
            {
                if (!string.IsNullOrEmpty(newName))
                {
                    statName = newName;
                }
                else
                {
                    IuvoDebug.DebugLogWarning("Stat name cannot be empty.");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), and statName.
Member Data Documentation
statName
string IuvoUnity.RPG.Stat.statName = "New Stat" protected
Referenced by GetStatName(), and SetStatName().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/RPG/Progression/Stat.cs