Iuvo Unity: IuvoUnity.Events.FlexibleEvent< T > Class Template Reference
IuvoUnity.Events.FlexibleEvent< T > Class Template Reference
Public Member Functions
void Invoke (T arg)
void AddListener (Action< T > listener)
void RemoveListener (Action< T > listener)
void AddUnityListener (UnityAction< T > listener)
void RemoveUnityListener (UnityAction< T > listener)
void RemoveAllFlexibleEventListeners ()
Properties
UnityEvent< T > UnityEvent [get]
Events
Action< T > internalEvent
Private Attributes
UnityEvent< T > unityEvent = new UnityEvent<T>()
Member Function Documentation
AddListener()
void IuvoUnity.Events.FlexibleEvent< T >.AddListener (Action< T > listener)
            {
                internalEvent += listener;
                //internalActions.Add(listener);
            }
References internalEvent.
AddUnityListener()
void IuvoUnity.Events.FlexibleEvent< T >.AddUnityListener (UnityAction< T > listener)
            {
                unityEvent.AddListener(listener);
            }
References unityEvent.
Invoke()
void IuvoUnity.Events.FlexibleEvent< T >.Invoke (T arg)
            {
                unityEvent?.Invoke(arg);
                internalEvent?.Invoke(arg);
            }
References internalEvent, and unityEvent.
RemoveAllFlexibleEventListeners()
void IuvoUnity.Events.FlexibleEvent< T >.RemoveAllFlexibleEventListeners ()
            {
                //foreach (var evt in internalActions)
                //    RemoveListener(evt);
                internalEvent = null; // Clear the C# event to prevent memory leaks
                unityEvent.RemoveAllListeners();
            }
References internalEvent, and unityEvent.
RemoveListener()
void IuvoUnity.Events.FlexibleEvent< T >.RemoveListener (Action< T > listener)
            {
                internalEvent -= listener;
                //internalActions.Remove(listener);
            }
References internalEvent.
RemoveUnityListener()
void IuvoUnity.Events.FlexibleEvent< T >.RemoveUnityListener (UnityAction< T > listener)
            {
                unityEvent.RemoveListener(listener);
            }
References unityEvent.
Member Data Documentation
unityEvent
UnityEvent<T> IuvoUnity.Events.FlexibleEvent< T >.unityEvent = new UnityEvent<T>() private
Referenced by AddUnityListener(), Invoke(), RemoveAllFlexibleEventListeners(), and RemoveUnityListener().
Property Documentation
UnityEvent
UnityEvent<T> IuvoUnity.Events.FlexibleEvent< T >.UnityEvent get
Event Documentation
internalEvent
Action<T> IuvoUnity.Events.FlexibleEvent< T >.internalEvent private
Referenced by AddListener(), Invoke(), RemoveAllFlexibleEventListeners(), and RemoveListener().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Events/FlexibleEvent.cs