Iuvo Unity: IuvoUnity.Extensions.TransformExtensions Class Reference
IuvoUnity.Extensions.TransformExtensions Class Reference
Provides extension methods for Unity's Transform component, enabling simplified manipulation and queries of transforms in the scene.
Static Public Member Functions
static void SetParentWithoutAffectingTransform (this Transform transform, Transform newParent)
Sets the parent of this transform without modifying its world position, rotation, or scale.
static Transform FindChildByName (this Transform transform, string name)
Finds a direct child of the transform by name.
static Transform FindChildByNameRecursive (this Transform transform, string name)
Recursively searches for a child transform by name.
static void SetRotationToTargetDirection (this Transform transform, Vector3 direction)
Sets the transform's rotation to face the given direction.
static void RotateTowardsTarget (this Transform transform, Transform target, float speed, float deltaTime)
Smoothly rotates the transform to face a target transform.
static bool IsAbove (this Transform transform, Transform other)
Returns true if this transform is above the other transform.
static bool IsBelow (this Transform transform, Transform other)
Returns true if this transform is below the other transform.
static bool IsLeftOf (this Transform transform, Transform other)
Returns true if this transform is to the left of the other transform.
static bool IsRightOf (this Transform transform, Transform other)
Returns true if this transform is to the right of the other transform.
static bool IsInFrontOf (this Transform transform, Transform other)
Returns true if this transform is in front of the other transform.
static bool IsBehind (this Transform transform, Transform other)
Returns true if this transform is behind the other transform.
static void RotateToMatch (this Transform transform, Transform target)
Sets this transform's rotation to match the target's rotation.
static void MultiplyLocalScale (this Transform transform, Vector3 multiplier)
Multiplies the transform's local scale by the given vector.
static void ScaleToMatch (this Transform transform, Transform target)
Sets this transform's local scale to match the target's.
static void TranslateAlongAxis (this Transform transform, Vector3 axis, float distance)
Moves the transform along a given axis by a specified distance.
static void MoveTowardsPosition (this Transform transform, Vector3 targetPosition, float speed, float deltaTime)
Moves the transform towards a target position at a specified speed.
static Quaternion GetWorldRotation (this Transform transform)
Gets the world rotation of the transform.
static void SetWorldRotation (this Transform transform, Quaternion rotation)
Sets the world rotation of the transform.
static void RotateAroundWorldAxis (this Transform transform, Vector3 worldAxis, float angle)
Rotates the transform around a world axis by a specified angle.
static void RotateAroundLocalAxis (this Transform transform, Vector3 localAxis, float angle)
Rotates the transform around a local axis by a specified angle.
static void AlignWith (this Transform transform, Transform target)
Aligns this transform's position and rotation with the target.
static void AlignWith (this Transform transform, Transform target, Vector3 offset)
Aligns this transform with the target using a position offset.
static void AlignWith (this Transform transform, Transform target, Vector3 positionOffset, Vector3 rotationOffset)
Aligns this transform with the target using position and rotation offsets.
static void AlignWith (this Transform transform, Transform target, Vector3 positionOffset, Vector3 rotationOffset, Vector3 scale)
Aligns this transform with the target using position, rotation offsets, and absolute scale.
static void AlignWith (this Transform transform, Transform target, Vector3 positionOffset, Vector3 rotationOffset, float scale)
Aligns this transform with the target using position, rotation offsets, and uniform scale.
static void DetachAndDestroy (this Transform transform)
Detaches this transform from its parent and destroys the associated GameObject.
static void RotateAround (this Transform transform, Vector3 point, Vector3 axis, float angle)
Rotates the transform around a point along the given axis.
static void RotateAroundAxisWithDuration (this Transform transform, Vector3 axis, float angle, float duration, float deltaTime)
Smoothly rotates around a given axis over a set duration.
static void SwapPositionWith (this Transform transform, Transform target)
Swaps the position of this transform with another.
static void SwapRotationWith (this Transform transform, Transform target)
Swaps the rotation of this transform with another.
static void SwapScaleWith (this Transform transform, Transform target)
Swaps the local scale of this transform with another.
static void RotateSmoothlyTowards (this Transform transform, Vector3 targetPosition, float rotationSpeed, float deltaTime)
Smoothly rotates the transform to face a world position.
static void RotateSmoothlyTowards (this Transform transform, Transform target, float rotationSpeed, float deltaTime)
Smoothly rotates the transform to face another transform.
static IEnumerable< GameObject > GetAllChildren (this Transform transform)
Recursively gets all descendant GameObjects of the transform.
Detailed Description
Provides extension methods for Unity's Transform component, enabling simplified manipulation and queries of transforms in the scene.
Member Function Documentation
AlignWith() [1/5]
void IuvoUnity.Extensions.TransformExtensions.AlignWith (this Transform transform, Transform target) static
Aligns this transform's position and rotation with the target.
            {
                transform.position = target.position;
                transform.rotation = target.rotation;
            }
Referenced by AlignWith().
AlignWith() [2/5]
void IuvoUnity.Extensions.TransformExtensions.AlignWith (this Transform transform, Transform target, Vector3 offset) static
Aligns this transform with the target using a position offset.
            {
                transform.position = target.position + offset;
                transform.rotation = target.rotation;
            }
AlignWith() [3/5]
void IuvoUnity.Extensions.TransformExtensions.AlignWith (this Transform transform, Transform target, Vector3 positionOffset, Vector3 rotationOffset) static
Aligns this transform with the target using position and rotation offsets.
            {
                transform.position = target.position + positionOffset;
                transform.rotation = target.rotation * Quaternion.Euler(rotationOffset);
            }
AlignWith() [4/5]
void IuvoUnity.Extensions.TransformExtensions.AlignWith (this Transform transform, Transform target, Vector3 positionOffset, Vector3 rotationOffset, float scale) static
Aligns this transform with the target using position, rotation offsets, and uniform scale.
            {
                AlignWith(transform, target, positionOffset, rotationOffset, new Vector3(scale, scale, scale));
            }
References AlignWith().
AlignWith() [5/5]
void IuvoUnity.Extensions.TransformExtensions.AlignWith (this Transform transform, Transform target, Vector3 positionOffset, Vector3 rotationOffset, Vector3 scale) static
Aligns this transform with the target using position, rotation offsets, and absolute scale.
            {
                transform.position = target.position + positionOffset;
                transform.rotation = target.rotation * Quaternion.Euler(rotationOffset);
                transform.localScale = scale;
            }
DetachAndDestroy()
void IuvoUnity.Extensions.TransformExtensions.DetachAndDestroy (this Transform transform) static
Detaches this transform from its parent and destroys the associated GameObject.
            {
                transform.SetParent(null);
                Object.Destroy(transform.gameObject);
            }
FindChildByName()
Transform IuvoUnity.Extensions.TransformExtensions.FindChildByName (this Transform transform, string name) static
Finds a direct child of the transform by name.
            {
                foreach (Transform child in transform)
                {
                    if (child.name == name) return child;
                }
                return null;
            }
FindChildByNameRecursive()
Transform IuvoUnity.Extensions.TransformExtensions.FindChildByNameRecursive (this Transform transform, string name) static
Recursively searches for a child transform by name.
            {
                foreach (Transform child in transform)
                {
                    if (child.name == name) return child;
                    Transform found = child.FindChildByNameRecursive(name);
                    if (found != null) return found;
                }
                return null;
            }
GetAllChildren()
IEnumerable< GameObject > IuvoUnity.Extensions.TransformExtensions.GetAllChildren (this Transform transform) static
Recursively gets all descendant GameObjects of the transform.
            {
                foreach (Transform child in transform)
                {
                    yield return child.gameObject;
                    foreach (var descendant in child.GetAllChildren())
                    {
                        yield return descendant;
                    }
                }
            }
GetWorldRotation()
Quaternion IuvoUnity.Extensions.TransformExtensions.GetWorldRotation (this Transform transform) static
Gets the world rotation of the transform.
            {
                return transform.rotation;
            }
IsAbove()
bool IuvoUnity.Extensions.TransformExtensions.IsAbove (this Transform transform, Transform other) static
Returns true if this transform is above the other transform.
=> transform.position.y > other.position.y;
IsBehind()
bool IuvoUnity.Extensions.TransformExtensions.IsBehind (this Transform transform, Transform other) static
Returns true if this transform is behind the other transform.
=> transform.position.z < other.position.z;
IsBelow()
bool IuvoUnity.Extensions.TransformExtensions.IsBelow (this Transform transform, Transform other) static
Returns true if this transform is below the other transform.
=> transform.position.y < other.position.y;
IsInFrontOf()
bool IuvoUnity.Extensions.TransformExtensions.IsInFrontOf (this Transform transform, Transform other) static
Returns true if this transform is in front of the other transform.
=> transform.position.z > other.position.z;
IsLeftOf()
bool IuvoUnity.Extensions.TransformExtensions.IsLeftOf (this Transform transform, Transform other) static
Returns true if this transform is to the left of the other transform.
=> transform.position.x < other.position.x;
IsRightOf()
bool IuvoUnity.Extensions.TransformExtensions.IsRightOf (this Transform transform, Transform other) static
Returns true if this transform is to the right of the other transform.
=> transform.position.x > other.position.x;
MoveTowardsPosition()
void IuvoUnity.Extensions.TransformExtensions.MoveTowardsPosition (this Transform transform, Vector3 targetPosition, float speed, float deltaTime) static
Moves the transform towards a target position at a specified speed.
            {
                transform.position = Vector3.MoveTowards(transform.position, targetPosition, speed * deltaTime);
            }
MultiplyLocalScale()
void IuvoUnity.Extensions.TransformExtensions.MultiplyLocalScale (this Transform transform, Vector3 multiplier) static
Multiplies the transform's local scale by the given vector.
            {
                transform.localScale = Vector3.Scale(transform.localScale, multiplier);
            }
RotateAround()
void IuvoUnity.Extensions.TransformExtensions.RotateAround (this Transform transform, Vector3 point, Vector3 axis, float angle) static
Rotates the transform around a point along the given axis.
            {
                transform.RotateAround(point, axis, angle);
            }
RotateAroundAxisWithDuration()
void IuvoUnity.Extensions.TransformExtensions.RotateAroundAxisWithDuration (this Transform transform, Vector3 axis, float angle, float duration, float deltaTime) static
Smoothly rotates around a given axis over a set duration.
            {
                float angleStep = angle * (deltaTime / duration);
                transform.Rotate(axis, angleStep, Space.Self);
            }
RotateAroundLocalAxis()
void IuvoUnity.Extensions.TransformExtensions.RotateAroundLocalAxis (this Transform transform, Vector3 localAxis, float angle) static
Rotates the transform around a local axis by a specified angle.
            {
                transform.Rotate(localAxis, angle, Space.Self);
            }
RotateAroundWorldAxis()
void IuvoUnity.Extensions.TransformExtensions.RotateAroundWorldAxis (this Transform transform, Vector3 worldAxis, float angle) static
Rotates the transform around a world axis by a specified angle.
            {
                transform.Rotate(worldAxis, angle, Space.World);
            }
RotateSmoothlyTowards() [1/2]
void IuvoUnity.Extensions.TransformExtensions.RotateSmoothlyTowards (this Transform transform, Transform target, float rotationSpeed, float deltaTime) static
Smoothly rotates the transform to face another transform.
            {
                RotateSmoothlyTowards(transform, target.position, rotationSpeed, deltaTime);
            }
References RotateSmoothlyTowards().
RotateSmoothlyTowards() [2/2]
void IuvoUnity.Extensions.TransformExtensions.RotateSmoothlyTowards (this Transform transform, Vector3 targetPosition, float rotationSpeed, float deltaTime) static
Smoothly rotates the transform to face a world position.
            {
                Vector3 direction = targetPosition - transform.position;
                if (direction != Vector3.zero)
                {
                    Quaternion targetRotation = Quaternion.LookRotation(direction);
                    transform.rotation = Quaternion.RotateTowards(transform.rotation, targetRotation, rotationSpeed * deltaTime);
                }
            }
Referenced by RotateSmoothlyTowards().
RotateToMatch()
void IuvoUnity.Extensions.TransformExtensions.RotateToMatch (this Transform transform, Transform target) static
Sets this transform's rotation to match the target's rotation.
            {
                transform.rotation = target.rotation;
            }
RotateTowardsTarget()
void IuvoUnity.Extensions.TransformExtensions.RotateTowardsTarget (this Transform transform, Transform target, float speed, float deltaTime) static
Smoothly rotates the transform to face a target transform.
            {
                Quaternion targetRotation = Quaternion.LookRotation(target.position - transform.position);
                transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, speed * deltaTime);
            }
ScaleToMatch()
void IuvoUnity.Extensions.TransformExtensions.ScaleToMatch (this Transform transform, Transform target) static
Sets this transform's local scale to match the target's.
            {
                transform.localScale = target.localScale;
            }
SetParentWithoutAffectingTransform()
void IuvoUnity.Extensions.TransformExtensions.SetParentWithoutAffectingTransform (this Transform transform, Transform newParent) static
Sets the parent of this transform without modifying its world position, rotation, or scale.
            {
                Vector3 worldPosition = transform.position;
                Quaternion worldRotation = transform.rotation;
                Vector3 worldScale = transform.lossyScale;
                transform.SetParent(newParent, worldPositionStays: false);
                transform.position = worldPosition;
                transform.rotation = worldRotation;
                // Manually set scale because Unity doesn't preserve it when reparenting
                Vector3 parentScale = newParent != null ? newParent.lossyScale : Vector3.one;
                transform.localScale = new Vector3(
                    worldScale.x / parentScale.x,
                    worldScale.y / parentScale.y,
                    worldScale.z / parentScale.z
                );
            }
SetRotationToTargetDirection()
void IuvoUnity.Extensions.TransformExtensions.SetRotationToTargetDirection (this Transform transform, Vector3 direction) static
Sets the transform's rotation to face the given direction.
            {
                transform.rotation = Quaternion.LookRotation(direction);
            }
SetWorldRotation()
void IuvoUnity.Extensions.TransformExtensions.SetWorldRotation (this Transform transform, Quaternion rotation) static
Sets the world rotation of the transform.
            {
                transform.rotation = rotation;
            }
SwapPositionWith()
void IuvoUnity.Extensions.TransformExtensions.SwapPositionWith (this Transform transform, Transform target) static
Swaps the position of this transform with another.
            {
                Vector3 temp = transform.position;
                transform.position = target.position;
                target.position = temp;
            }
SwapRotationWith()
void IuvoUnity.Extensions.TransformExtensions.SwapRotationWith (this Transform transform, Transform target) static
Swaps the rotation of this transform with another.
            {
                Quaternion temp = transform.rotation;
                transform.rotation = target.rotation;
                target.rotation = temp;
            }
SwapScaleWith()
void IuvoUnity.Extensions.TransformExtensions.SwapScaleWith (this Transform transform, Transform target) static
Swaps the local scale of this transform with another.
            {
                Vector3 temp = transform.localScale;
                transform.localScale = target.localScale;
                target.localScale = temp;
            }
TranslateAlongAxis()
void IuvoUnity.Extensions.TransformExtensions.TranslateAlongAxis (this Transform transform, Vector3 axis, float distance) static
Moves the transform along a given axis by a specified distance.
            {
                transform.position += axis.normalized * distance;
            }
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Extensions/TransformExtensions.cs