Iuvo Unity: IuvoUnity.Inputs.HoldInputActionBase Class Reference
IuvoUnity.Inputs.HoldInputActionBase Class Reference abstract
Public Member Functions
override void HandleInput ()
bool IsPressed ()
Public Member Functions inherited from IuvoUnity.Inputs.BaseInputActionLegacy
void HandleInput ()
Public Attributes
float neededHoldTime = 0.5f
Public Attributes inherited from IuvoUnity.Inputs.BaseInputActionLegacy
UnityEvent OnPerformedUnity
Action OnPerformed
Protected Attributes
float timeHeld = 0f
Private Attributes
bool hasPerformed = false
Additional Inherited Members
Protected Member Functions inherited from IuvoUnity.Inputs.BaseInputActionLegacy
void Perform ()
virtual void Update ()
Member Function Documentation
HandleInput()
override void IuvoUnity.Inputs.HoldInputActionBase.HandleInput ()
            {
                if (IsPressed())
                {
                    timeHeld += Time.deltaTime;
                    if (timeHeld >= neededHoldTime && !hasPerformed)
                    {
                        Perform();
                        hasPerformed = true;
                    }
                }
                else
                {
                    timeHeld = 0f;
                    hasPerformed = false;
                }
            }
References hasPerformed, IsPressed(), neededHoldTime, IuvoUnity.Inputs.BaseInputActionLegacy.Perform(), and timeHeld.
IsPressed()
bool IuvoUnity.Inputs.HoldInputActionBase.IsPressed () abstract
Referenced by HandleInput().
Member Data Documentation
hasPerformed
bool IuvoUnity.Inputs.HoldInputActionBase.hasPerformed = false private
Referenced by HandleInput().
neededHoldTime
float IuvoUnity.Inputs.HoldInputActionBase.neededHoldTime = 0.5f
Referenced by HandleInput(), and IuvoUnity.Inputs.KeyHoldInputAction.HandleInput().
timeHeld
float IuvoUnity.Inputs.HoldInputActionBase.timeHeld = 0f protected
Referenced by HandleInput(), and IuvoUnity.Inputs.KeyHoldInputAction.HandleInput().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Input/InputBaseLegacy.cs