Iuvo Unity: IuvoUnity.Inputs.DirectionalInputAction Class Reference
IuvoUnity.Inputs.DirectionalInputAction Class Reference
Public Types
enum Direction {
None = 0 , Forward = 1 << 0 , Backward = 1 << 1 , Left = 1 << 2 ,
Right = 1 << 3 , Up = 1 << 4 , Down = 1 << 5
}
Public Member Functions
override void OnEnable ()
override void OnDisable ()
Vector3 GetCurrentDirectionVector ()
Public Member Functions inherited from IuvoUnity.Inputs.InputActionBase
void Enable ()
void Disable ()
void TriggerPerform ()
Public Attributes
UnityEvent< Vector3 > onMovementVectorGenerated
Public Attributes inherited from IuvoUnity.Inputs.InputActionBase
UnityEvent OnPerformedUnity
System.Action OnPerformed
System.Action OnStarted
System.Action OnCanceled
UnityEvent< InputAction.CallbackContext > onPerformedWithContext
UnityEvent< InputAction.CallbackContext > onStartedWithContext
UnityEvent< InputAction.CallbackContext > onCanceledWithContext
Protected Member Functions
override void OnInputPerformed (InputAction.CallbackContext context)
Protected Member Functions inherited from IuvoUnity.Inputs.InputActionBase
virtual void Awake ()
virtual void Update ()
virtual void FixedUpdate ()
virtual void OnInputStarted (InputAction.CallbackContext context)
virtual void OnInputCanceled (InputAction.CallbackContext context)
virtual void Perform ()
virtual void OnDestroy ()
Private Member Functions
void OnUpPerformed (InputAction.CallbackContext ctx)
void OnUpCanceled (InputAction.CallbackContext ctx)
void OnDownPerformed (InputAction.CallbackContext ctx)
void OnDownCanceled (InputAction.CallbackContext ctx)
void GenerateDirectionVector ()
Private Attributes
float axisThreshold = 0.1f
float yForce = 1f
InputActionReference inputUpY = new InputActionReference()
InputActionReference inputDownY = new InputActionReference()
Vector2 planarInput = Vector2.zero
bool isUpPressed = false
bool isDownPressed = false
Additional Inherited Members
Protected Attributes inherited from IuvoUnity.Inputs.InputActionBase
InputActionReference inputActionReference
Properties inherited from IuvoUnity.Inputs.InputActionBase
string ActionName [get]
InputAction inputAction [get]
bool IsEnabled = false [get, private set]
Member Enumeration Documentation
Direction
enum IuvoUnity.Inputs.DirectionalInputAction.Direction
Enumerator
None
Forward
Backward
Left
Right
Up
Down
            {
                None = 0,
                Forward = 1 << 0,
                Backward = 1 << 1,
                Left = 1 << 2,
                Right = 1 << 3,
                Up = 1 << 4,
                Down = 1 << 5
            }
Member Function Documentation
GenerateDirectionVector()
void IuvoUnity.Inputs.DirectionalInputAction.GenerateDirectionVector () private
            {
                Vector3 move = Vector3.zero;
                // X (Left / Right)
                if (planarInput.x > axisThreshold) move += Vector3.right;
                if (planarInput.x < -axisThreshold) move += Vector3.left;
                // Z (Forward / Backward)
                if (planarInput.y > axisThreshold) move += Vector3.forward;
                if (planarInput.y < -axisThreshold) move += Vector3.back;
                // Y (Up / Down)
                if (isUpPressed) move += Vector3.up * yForce;
                if (isDownPressed) move += Vector3.down * yForce * 2f;
                onMovementVectorGenerated?.Invoke(move);
            }
References axisThreshold, isDownPressed, isUpPressed, onMovementVectorGenerated, planarInput, and yForce.
Referenced by OnInputPerformed().
GetCurrentDirectionVector()
Vector3 IuvoUnity.Inputs.DirectionalInputAction.GetCurrentDirectionVector ()
            {
                Vector3 move = Vector3.zero;
                if (planarInput.x > axisThreshold) move += Vector3.right;
                if (planarInput.x < -axisThreshold) move += Vector3.left;
                if (planarInput.y > axisThreshold) move += Vector3.forward;
                if (planarInput.y < -axisThreshold) move += Vector3.back;
                if (isUpPressed) move += Vector3.up * yForce;
                if (isDownPressed) move += Vector3.down * yForce * 2f;
                return move;
            }
References axisThreshold, isDownPressed, isUpPressed, planarInput, and yForce.
OnDisable()
override void IuvoUnity.Inputs.DirectionalInputAction.OnDisable () virtual
Reimplemented from IuvoUnity.Inputs.InputActionBase.
            {
                base.OnDisable();
                if (inputUpY != null)
                {
                    inputUpY.action.performed -= OnUpPerformed;
                    inputUpY.action.canceled -= OnUpCanceled;
                    inputUpY.action.Disable();
                }
                if (inputDownY != null)
                {
                    inputDownY.action.performed -= OnDownPerformed;
                    inputDownY.action.canceled -= OnDownCanceled;
                    inputDownY.action.Disable();
                }
            }
References inputDownY, inputUpY, OnDownCanceled(), OnDownPerformed(), OnUpCanceled(), and OnUpPerformed().
OnDownCanceled()
void IuvoUnity.Inputs.DirectionalInputAction.OnDownCanceled (InputAction.CallbackContext ctx) private
=> isDownPressed = false;
References isDownPressed.
Referenced by OnDisable(), and OnEnable().
OnDownPerformed()
void IuvoUnity.Inputs.DirectionalInputAction.OnDownPerformed (InputAction.CallbackContext ctx) private
=> isDownPressed = true;
References isDownPressed.
Referenced by OnDisable(), and OnEnable().
OnEnable()
override void IuvoUnity.Inputs.DirectionalInputAction.OnEnable () virtual
Reimplemented from IuvoUnity.Inputs.InputActionBase.
            {
                base.OnEnable();
                if (inputUpY != null)
                {
                    inputUpY.action.performed += OnUpPerformed;
                    inputUpY.action.canceled += OnUpCanceled;
                    inputUpY.action.Enable();
                }
                if (inputDownY != null)
                {
                    inputDownY.action.performed += OnDownPerformed;
                    inputDownY.action.canceled += OnDownCanceled;
                    inputDownY.action.Enable();
                }
            }
References inputDownY, inputUpY, OnDownCanceled(), OnDownPerformed(), OnUpCanceled(), and OnUpPerformed().
OnInputPerformed()
override void IuvoUnity.Inputs.DirectionalInputAction.OnInputPerformed (InputAction.CallbackContext context) protected virtual
Reimplemented from IuvoUnity.Inputs.InputActionBase.
            {
                planarInput = context.ReadValue<Vector2>();
                GenerateDirectionVector();
                Perform();
            }
References GenerateDirectionVector(), IuvoUnity.Inputs.InputActionBase.Perform(), and planarInput.
OnUpCanceled()
void IuvoUnity.Inputs.DirectionalInputAction.OnUpCanceled (InputAction.CallbackContext ctx) private
=> isUpPressed = false;
References isUpPressed.
Referenced by OnDisable(), and OnEnable().
OnUpPerformed()
void IuvoUnity.Inputs.DirectionalInputAction.OnUpPerformed (InputAction.CallbackContext ctx) private
=> isUpPressed = true;
References isUpPressed.
Referenced by OnDisable(), and OnEnable().
Member Data Documentation
axisThreshold
float IuvoUnity.Inputs.DirectionalInputAction.axisThreshold = 0.1f private
Referenced by GenerateDirectionVector(), and GetCurrentDirectionVector().
inputDownY
InputActionReference IuvoUnity.Inputs.DirectionalInputAction.inputDownY = new InputActionReference() private
Referenced by OnDisable(), and OnEnable().
inputUpY
InputActionReference IuvoUnity.Inputs.DirectionalInputAction.inputUpY = new InputActionReference() private
Referenced by OnDisable(), and OnEnable().
isDownPressed
bool IuvoUnity.Inputs.DirectionalInputAction.isDownPressed = false private
Referenced by GenerateDirectionVector(), GetCurrentDirectionVector(), OnDownCanceled(), and OnDownPerformed().
isUpPressed
bool IuvoUnity.Inputs.DirectionalInputAction.isUpPressed = false private
Referenced by GenerateDirectionVector(), GetCurrentDirectionVector(), OnUpCanceled(), and OnUpPerformed().
onMovementVectorGenerated
UnityEvent<Vector3> IuvoUnity.Inputs.DirectionalInputAction.onMovementVectorGenerated
Referenced by GenerateDirectionVector().
planarInput
Vector2 IuvoUnity.Inputs.DirectionalInputAction.planarInput = Vector2.zero private
Referenced by GenerateDirectionVector(), GetCurrentDirectionVector(), and OnInputPerformed().
yForce
float IuvoUnity.Inputs.DirectionalInputAction.yForce = 1f private
Referenced by GenerateDirectionVector(), and GetCurrentDirectionVector().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Input/InputBase.cs