Iuvo Unity: IuvoUnity.Configurations.LevelConfiguration Class Reference
IuvoUnity.Configurations.LevelConfiguration Class Reference
Public Member Functions
AnimationCurve GetDefaultExperienceCurve ()
virtual void OnEnable ()
virtual void OnDisable ()
void Serialize (LevelComponentData levelComponent)
LevelComponentData? DeserializeLevelComponent ()
int GetExpAtLevel (int level)
int GetExperienceToNextLevel (int currLevel, int cumulativeExp)
Returns EXP still required to reach the next level from the current state. Uses cumulative EXP values stored in the exp curve.
void SetLevelScalingCurve (AnimationCurve newExpCurve)
Sets a new experience curve for level scaling.
Dictionary< int, int > GetFullLevelTable ()
Returns a dictionary mapping each level to the cumulative EXP required to reach that level.
override void PrintInfo ()
Prints detailed information about the level configuration, including the EXP curve and last known level component data.
Public Member Functions inherited from IuvoUnity.Configurations.BaseConfig< T >
virtual void Configure (T configurable)
virtual void Reconfigure (T reconfigurable)
virtual string GetConfigSerializePath (string actingConfigClass, string objectToSerializeName, string parentConfigClass="BaseConfig")
Public Attributes
string savedItemName = "LevelComponent"
Public Attributes inherited from IuvoUnity.Configurations.BaseConfig< T >
string configName
Protected Member Functions
virtual void ImplementDefaultScalingAlgorithm ()
Properties
int MaxLevel [get]
Private Attributes
AnimationCurve DefaultLevelingCurve
AnimationCurve expCurve
LevelComponentData lastLevelComponentData = new LevelComponentData { CurrentLevel = -1 }
Member Function Documentation
DeserializeLevelComponent()
LevelComponentData? IuvoUnity.Configurations.LevelConfiguration.DeserializeLevelComponent ()
            {
                string filePath = GetConfigSerializePath("LevelConfiguration", savedItemName, "BaseConfig");
                if (!System.IO.File.Exists(filePath))
                {
                    IuvoDebug.DebugLogWarning($"No save file found at {filePath}");
                    return null;
                }
                string json = System.IO.File.ReadAllText(filePath);
                LevelComponentData data = JsonUtility.FromJson<LevelComponentData>(json);
                lastLevelComponentData = data;
                return data;
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), IuvoUnity.Configurations.BaseConfig< T >.GetConfigSerializePath(), lastLevelComponentData, and savedItemName.
GetDefaultExperienceCurve()
AnimationCurve IuvoUnity.Configurations.LevelConfiguration.GetDefaultExperienceCurve ()
            {
                return DefaultLevelingCurve;
            }
References DefaultLevelingCurve.
Referenced by ImplementDefaultScalingAlgorithm().
GetExpAtLevel()
int IuvoUnity.Configurations.LevelConfiguration.GetExpAtLevel (int level)
            {
                if (level < 1 || level > MaxLevel)
                {
                    IuvoDebug.DebugLogWarning("Level out of range. Returning 0.");
                    return 0;
                }
                float exp = expCurve.Evaluate(level);
                return Mathf.RoundToInt(exp);
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogWarning(), expCurve, and MaxLevel.
Referenced by IuvoUnity.BaseClasses.LevelComponent.CheckLevelUp(), GetExperienceToNextLevel(), and GetFullLevelTable().
GetExperienceToNextLevel()
int IuvoUnity.Configurations.LevelConfiguration.GetExperienceToNextLevel (int currLevel, int cumulativeExp)
Returns EXP still required to reach the next level from the current state. Uses cumulative EXP values stored in the exp curve.
            {
                if (currLevel < 1 || currLevel >= MaxLevel)
                {
                    return 0;
                }
                int nextLevelExp = GetExpAtLevel(currLevel + 1);
                return Mathf.Max(0, nextLevelExp - cumulativeExp);
            }
References GetExpAtLevel(), and MaxLevel.
GetFullLevelTable()
Dictionary< int, int > IuvoUnity.Configurations.LevelConfiguration.GetFullLevelTable ()
Returns a dictionary mapping each level to the cumulative EXP required to reach that level.
Returns
            {
                Dictionary<int, int> levelTable = new Dictionary<int, int>();
                for (int level = 1; level <= MaxLevel; level++)
                {
                    levelTable[level] = GetExpAtLevel(level);
                }
                return levelTable;
            }
References GetExpAtLevel(), and MaxLevel.
Referenced by PrintInfo().
ImplementDefaultScalingAlgorithm()
virtual void IuvoUnity.Configurations.LevelConfiguration.ImplementDefaultScalingAlgorithm () protected virtual
            {
                IuvoDebug.DebugLog("Implementing default exp curve...");
                expCurve = new AnimationCurve(GetDefaultExperienceCurve().keys);
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), expCurve, and GetDefaultExperienceCurve().
Referenced by OnEnable(), and SetLevelScalingCurve().
OnDisable()
virtual void IuvoUnity.Configurations.LevelConfiguration.OnDisable () virtual
            {
                IuvoDebug.DebugLog("LevelConfiguration disabled.");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog().
OnEnable()
virtual void IuvoUnity.Configurations.LevelConfiguration.OnEnable () virtual
            {
                configName = typeof(LevelConfiguration).ToString();
                if (expCurve == null)
                {
                    ImplementDefaultScalingAlgorithm();
                }
            }
References IuvoUnity.Configurations.BaseConfig< T >.configName, expCurve, and ImplementDefaultScalingAlgorithm().
PrintInfo()
override void IuvoUnity.Configurations.LevelConfiguration.PrintInfo () virtual
Prints detailed information about the level configuration, including the EXP curve and last known level component data.
Reimplemented from IuvoUnity.Configurations.BaseConfig< T >.
            {
                base.PrintInfo();
                IuvoDebug.DebugLog("Level EXP Curve:");
                Dictionary<int, int> scaling = GetFullLevelTable();
                foreach (var kvp in scaling)
                {
                    IuvoDebug.DebugLog($"  Level {kvp.Key}: {kvp.Value} EXP");
                }
                if (lastLevelComponentData.IsValid())
                {
                    IuvoDebug.DebugLog("Last Level Component:");
                    IuvoDebug.DebugLog($"  Is Max Level: {lastLevelComponentData.CurrentLevel >= MaxLevel}");
                    IuvoDebug.DebugLog($"  Level: {lastLevelComponentData.CurrentLevel}");
                    IuvoDebug.DebugLog($"  Experience: {lastLevelComponentData.LevelProgressExperience}");
                    IuvoDebug.DebugLog($"  Lifetime Experience: {lastLevelComponentData.LifetimeExperience}");
                    IuvoDebug.DebugLog($"  Experience to Next Level: {lastLevelComponentData.ExperienceUntilNextLevel}");
                    IuvoDebug.DebugLog($"  Next Level EXP Requirement: {lastLevelComponentData.NextLevelExperienceMinimum}");
                    IuvoDebug.DebugLog($"  Current LevelUp Points: {lastLevelComponentData.CurrentLevelUpPoints}");
                    IuvoDebug.DebugLog($"  Max LevelUp Points: {lastLevelComponentData.MaxLevelUpPoints}");
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), GetFullLevelTable(), and lastLevelComponentData.
Serialize()
void IuvoUnity.Configurations.LevelConfiguration.Serialize (LevelComponentData levelComponent)
            {
                string json = JsonUtility.ToJson(levelComponent);
                string filePath = GetConfigSerializePath("LevelConfiguration", savedItemName, "BaseConfig");
                if (filePath == "")
                {
                    IuvoDebug.DebugLogError("Failed to get file path for serialization.");
                    return;
                }
                System.IO.File.WriteAllText(filePath, json);
                IuvoDebug.DebugLog($"Serialized LevelComponent to {filePath}");
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), IuvoUnity.Debug.IuvoDebug.DebugLogError(), IuvoUnity.Configurations.BaseConfig< T >.GetConfigSerializePath(), and savedItemName.
SetLevelScalingCurve()
void IuvoUnity.Configurations.LevelConfiguration.SetLevelScalingCurve (AnimationCurve newExpCurve)
Sets a new experience curve for level scaling.
Parameters
newExpCurve
            {
                if (newExpCurve == null)
                {
                    IuvoDebug.DebugLogError("New Expereience curve cannot be null. Implementing default scaling");
                    ImplementDefaultScalingAlgorithm();
                    return;
                }
                IuvoDebug.DebugLog("Setting level scaling algorithm...");
                expCurve = newExpCurve;
            }
References IuvoUnity.Debug.IuvoDebug.DebugLog(), IuvoUnity.Debug.IuvoDebug.DebugLogError(), expCurve, and ImplementDefaultScalingAlgorithm().
Member Data Documentation
DefaultLevelingCurve
AnimationCurve IuvoUnity.Configurations.LevelConfiguration.DefaultLevelingCurve private
Initial value:
                                            = new AnimationCurve(
    new Keyframe(1, 100),
    new Keyframe(25, 25000),
    new Keyframe(50, 150000),
    new Keyframe(75, 2500000),
    new Keyframe(100, 50000000)
)
Referenced by GetDefaultExperienceCurve().
expCurve
AnimationCurve IuvoUnity.Configurations.LevelConfiguration.expCurve private
Referenced by GetExpAtLevel(), ImplementDefaultScalingAlgorithm(), OnEnable(), and SetLevelScalingCurve().
lastLevelComponentData
LevelComponentData IuvoUnity.Configurations.LevelConfiguration.lastLevelComponentData = new LevelComponentData { CurrentLevel = -1 } private
{ CurrentLevel = -1 };
Referenced by DeserializeLevelComponent(), and PrintInfo().
savedItemName
string IuvoUnity.Configurations.LevelConfiguration.savedItemName = "LevelComponent"
Referenced by DeserializeLevelComponent(), and Serialize().
Property Documentation
MaxLevel
int IuvoUnity.Configurations.LevelConfiguration.MaxLevel get
Referenced by IuvoUnity.BaseClasses.LevelComponent.CheckLevelUp(), GetExpAtLevel(), GetExperienceToNextLevel(), and GetFullLevelTable().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Configurations/LevelConfiguration.cs