Iuvo Unity: IuvoUnity.BaseClasses.SemiBehavior Class Reference
IuvoUnity.BaseClasses.SemiBehavior Class Reference
"Custom lightweight lifecycle system for data-driven or decoupled non-MonoBehaviour systems (e.g. managers, AI behaviors, stat engines)."
Public Types
enum UpdateMode { None , Regular , Fixed , Late }
Defines the update phase this component responds to.
Public Member Functions
void Init (SemiBehaviorManager manager)
virtual void TryInitializeLifecycle ()
virtual void DeinitializeLifecycle ()
void RegisterUpdateLoop ()
virtual void Tick ()
virtual void OnAwake ()
Called via IAwake. Triggers the OnAwake hook for initialization logic.
void Awake ()
Called via IAwake. Triggers the Awake hook.
virtual void OnStart ()
Called via IStart. Triggers the OnStart hook.
void Start ()
Called via IStart. Executes OnStart and marks HasStarted as true.
virtual void OnUpdate ()
Override to define logic executed during the standard Update loop.
void Update ()
Called via IUpdate. Executes OnUpdate if UpdateMode is Regular.
virtual void OnFixedUpdate ()
Override to define logic executed during FixedUpdate loop.
void FixedUpdate ()
Called via IFixedUpdate. Executes OnFixedUpdate if UpdateMode is Fixed.
virtual void OnLateUpdate ()
Override to define logic executed during LateUpdate loop.
void LateUpdate ()
Called via ILateUpdate. Executes OnLateUpdate if UpdateMode is Late.
void Enable ()
Enables the component and calls the overridable OnEnable hook.
virtual void OnEnable ()
Override to define behavior when the component is enabled.
void Disable ()
Disables the component and calls the overridable OnDisable hook.
virtual void OnDisable ()
Override to define behavior when the component is disabled.
void Activate ()
Activates the component and calls the overridable OnActivate hook.
virtual void OnActivate ()
Override to define behavior when the component is activated.
void Deactivate ()
Deactivates the component and calls the overridable OnDeactivate hook.
virtual void OnDeactivate ()
Override to define behavior when the component is deactivated.
Public Attributes
bool isInitialized = false
SemiBehaviorManager parentManager
Protected Member Functions
virtual void OnPreUpdate ()
virtual void OnPostUpdate ()
Protected Attributes
FlexibleEvent UpdateLoop
Properties
PriorityLevel PriorityLevel = PriorityLevel.None [get, set]
ClampedData< float > priorityScale = new ClampedFloat(new RangeF(0, 1), 0.5f) [get, set]
bool hasStarted = false [get, private set]
Indicates whether the Start method has been called.
UpdateMode updateMode [get, set]
Determines which update loop (Update, FixedUpdate, LateUpdate) is used.
bool IsEnabled [get, set]
Indicates whether the component is enabled and can be toggled.
bool IsActive [get, set]
Indicates whether the component is actively doing work.
Private Member Functions
void IActivatable. OnActivate ()
Activates the component and invokes OnActivate.
void IDeactivatable. OnDeactivate ()
Deactivates the component and invokes OnDeactivate.
Private Attributes
bool autoStart = true
bool autoEnable = true
bool autoActivate = true
UpdateMode _updateMode = UpdateMode.Regular
Detailed Description
"Custom lightweight lifecycle system for data-driven or decoupled non-MonoBehaviour systems (e.g. managers, AI behaviors, stat engines)."
Member Enumeration Documentation
UpdateMode
enum IuvoUnity.BaseClasses.SemiBehavior.UpdateMode
Defines the update phase this component responds to.
Enumerator
None
Regular
Fixed
Late
            {
                None,
                Regular,
                Fixed,
                Late
            }
Member Function Documentation
Activate()
void IuvoUnity.BaseClasses.SemiBehavior.Activate ()
Activates the component and calls the overridable OnActivate hook.
            {
                if (IsActive) return;
                IsActive = true;
                OnActivate();
            }
References IsActive, and OnActivate().
Referenced by TryInitializeLifecycle().
Awake()
void IuvoUnity.BaseClasses.SemiBehavior.Awake ()
Called via IAwake. Triggers the Awake hook.
Internal Awake call. Executes OnAwake. Useful if you want to trigger awake manually.
            {
                OnAwake();
            }
References OnAwake().
Referenced by TryInitializeLifecycle().
Deactivate()
void IuvoUnity.BaseClasses.SemiBehavior.Deactivate ()
Deactivates the component and calls the overridable OnDeactivate hook.
            {
                if (!IsActive) return;
                IsActive = false;
                OnDeactivate();
            }
References IsActive, and OnDeactivate().
Referenced by DeinitializeLifecycle().
DeinitializeLifecycle()
virtual void IuvoUnity.BaseClasses.SemiBehavior.DeinitializeLifecycle () virtual
            {
                UpdateLoop?.RemoveAllFlexibleEventListeners();
                UpdateLoop = null;
                Deactivate();
                Disable();
                hasStarted = false;
                //isInitialized = false;
            }
References Deactivate(), Disable(), hasStarted, and UpdateLoop.
Referenced by IuvoUnity.BaseClasses.SemiBehaviorManager.Destroy(), and IuvoUnity.BaseClasses.SemiBehaviorManager.Unregister().
Disable()
void IuvoUnity.BaseClasses.SemiBehavior.Disable ()
Disables the component and calls the overridable OnDisable hook.
            {
                if (!IsEnabled) return;
                IsEnabled = false;
                OnDisable();
            }
References IsEnabled, and OnDisable().
Referenced by DeinitializeLifecycle().
Enable()
void IuvoUnity.BaseClasses.SemiBehavior.Enable ()
Enables the component and calls the overridable OnEnable hook.
            {
                if (IsEnabled) return;
                IsEnabled = true;
                OnEnable();
            }
References IsEnabled, and OnEnable().
Referenced by TryInitializeLifecycle().
FixedUpdate()
void IuvoUnity.BaseClasses.SemiBehavior.FixedUpdate ()
Called via IFixedUpdate. Executes OnFixedUpdate if UpdateMode is Fixed.
Implements IuvoUnity.Interfaces.IFixedUpdate.
            {
                if (updateMode == UpdateMode.Fixed)
                    OnFixedUpdate();
            }
References OnFixedUpdate(), and updateMode.
Referenced by RegisterUpdateLoop().
Init()
void IuvoUnity.BaseClasses.SemiBehavior.Init (SemiBehaviorManager manager)
            {
                //if (isInitialized) return;
                if (UpdateLoop != null) return;
                UpdateLoop = new FlexibleEvent();
                parentManager = manager;
                TryInitializeLifecycle();
            }
References parentManager, TryInitializeLifecycle(), and UpdateLoop.
LateUpdate()
void IuvoUnity.BaseClasses.SemiBehavior.LateUpdate ()
Called via ILateUpdate. Executes OnLateUpdate if UpdateMode is Late.
Implements IuvoUnity.Interfaces.ILateUpdate.
            {
                if (updateMode == UpdateMode.Late)
                    OnLateUpdate();
            }
References OnLateUpdate(), and updateMode.
Referenced by RegisterUpdateLoop().
OnActivate() [1/2]
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnActivate () virtual
Override to define behavior when the component is activated.
Implements IuvoUnity.Interfaces.IActivatable.
{ }
OnActivate() [2/2]
void IActivatable. IuvoUnity.BaseClasses.SemiBehavior.OnActivate () private
Activates the component and invokes OnActivate.
Implements IuvoUnity.Interfaces.IActivatable.
=> Activate();
Referenced by Activate().
OnAwake()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnAwake () virtual
Called via IAwake. Triggers the OnAwake hook for initialization logic.
Override to define custom logic to execute during the "Awake" phase.
{ }
Referenced by Awake().
OnDeactivate() [1/2]
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnDeactivate () virtual
Override to define behavior when the component is deactivated.
Implements IuvoUnity.Interfaces.IDeactivatable.
{ }
OnDeactivate() [2/2]
void IDeactivatable. IuvoUnity.BaseClasses.SemiBehavior.OnDeactivate () private
Deactivates the component and invokes OnDeactivate.
Implements IuvoUnity.Interfaces.IDeactivatable.
=> Deactivate();
Referenced by Deactivate().
OnDisable()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnDisable () virtual
Override to define behavior when the component is disabled.
{ }
Referenced by Disable().
OnEnable()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnEnable () virtual
Override to define behavior when the component is enabled.
Implements IuvoUnity.Interfaces.IEnableable.
{ }
Referenced by Enable().
OnFixedUpdate()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnFixedUpdate () virtual
Override to define logic executed during FixedUpdate loop.
{ }
Referenced by FixedUpdate().
OnLateUpdate()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnLateUpdate () virtual
Override to define logic executed during LateUpdate loop.
{ }
Referenced by LateUpdate().
OnPostUpdate()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnPostUpdate () protected virtual
{ }
Referenced by Tick().
OnPreUpdate()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnPreUpdate () protected virtual
{ }
Referenced by Tick().
OnStart()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnStart () virtual
Called via IStart. Triggers the OnStart hook.
Override to define custom logic to execute during the "Start" phase.
{ }
Referenced by Start().
OnUpdate()
virtual void IuvoUnity.BaseClasses.SemiBehavior.OnUpdate () virtual
Override to define logic executed during the standard Update loop.
{ }
Referenced by Update().
RegisterUpdateLoop()
void IuvoUnity.BaseClasses.SemiBehavior.RegisterUpdateLoop ()
            {
                switch (updateMode)
                {
                    case UpdateMode.Regular:
                        UpdateLoop.AddListener(Update);
                        break;
                    case UpdateMode.Fixed:
                        UpdateLoop.AddListener(FixedUpdate);
                        break;
                    case UpdateMode.Late:
                        UpdateLoop.AddListener(LateUpdate);
                        break;
                    case UpdateMode.None:
                        UnityEngine.Debug.LogWarning($"{GetType().Name}: UpdateMode is None  no update loop will be registered.");
                        break;
                    default:
                        UnityEngine.Debug.LogError("The given Update type did not match");
                        break;
                }
            }
References FixedUpdate(), LateUpdate(), Update(), UpdateLoop, and updateMode.
Referenced by TryInitializeLifecycle().
Start()
void IuvoUnity.BaseClasses.SemiBehavior.Start ()
Called via IStart. Executes OnStart and marks HasStarted as true.
Internal Start call. Triggers OnStart and flags the instance as started.
            {
                if (hasStarted) return;
                hasStarted = true;
                OnStart();
            }
References hasStarted, and OnStart().
Referenced by TryInitializeLifecycle().
Tick()
virtual void IuvoUnity.BaseClasses.SemiBehavior.Tick () virtual
            {
                if (!IsEnabled || !IsActive || UpdateLoop == null)
                {
                    UnityEngine.Debug.LogWarning($"{GetType().Name} tried to Tick but is not active, enabled, or update loop is missing.");
                    return;
                }
                OnPreUpdate();
                UpdateLoop?.Invoke();
                OnPostUpdate();
            }
References IsActive, IsEnabled, OnPostUpdate(), OnPreUpdate(), and UpdateLoop.
TryInitializeLifecycle()
virtual void IuvoUnity.BaseClasses.SemiBehavior.TryInitializeLifecycle () virtual
            {
                //if (isInitialized) return;
                //isInitialized = true;
                Awake();
                if (autoStart) Start();
                if (autoEnable) Enable();
                if (autoActivate) Activate();
                RegisterUpdateLoop();
            }
References Activate(), autoActivate, autoEnable, autoStart, Awake(), Enable(), RegisterUpdateLoop(), and Start().
Referenced by Init(), and IuvoUnity.BaseClasses.SemiBehaviorManager.Register().
Update()
void IuvoUnity.BaseClasses.SemiBehavior.Update ()
Called via IUpdate. Executes OnUpdate if UpdateMode is Regular.
Implements IuvoUnity.Interfaces.IUpdate.
            {
                if (updateMode == UpdateMode.Regular)
                    OnUpdate();
            }
References OnUpdate(), and updateMode.
Referenced by RegisterUpdateLoop().
Member Data Documentation
_updateMode
UpdateMode IuvoUnity.BaseClasses.SemiBehavior._updateMode = UpdateMode.Regular private
autoActivate
bool IuvoUnity.BaseClasses.SemiBehavior.autoActivate = true private
Referenced by TryInitializeLifecycle().
autoEnable
bool IuvoUnity.BaseClasses.SemiBehavior.autoEnable = true private
Referenced by TryInitializeLifecycle().
autoStart
bool IuvoUnity.BaseClasses.SemiBehavior.autoStart = true private
Referenced by TryInitializeLifecycle().
isInitialized
bool IuvoUnity.BaseClasses.SemiBehavior.isInitialized = false
parentManager
SemiBehaviorManager IuvoUnity.BaseClasses.SemiBehavior.parentManager
Referenced by IuvoUnity.BaseClasses.SemiBehaviorManager.Destroy(), and Init().
UpdateLoop
FlexibleEvent IuvoUnity.BaseClasses.SemiBehavior.UpdateLoop protected
Referenced by DeinitializeLifecycle(), Init(), RegisterUpdateLoop(), and Tick().
Property Documentation
hasStarted
bool IuvoUnity.BaseClasses.SemiBehavior.hasStarted = false get private set
Indicates whether the Start method has been called.
{ get; private set; } = false;
Referenced by DeinitializeLifecycle(), and Start().
IsActive
bool IuvoUnity.BaseClasses.SemiBehavior.IsActive get set
Indicates whether the component is actively doing work.
Implements IuvoUnity.Interfaces.ITogglable.
{ get; set; }
Referenced by Activate(), Deactivate(), and Tick().
IsEnabled
bool IuvoUnity.BaseClasses.SemiBehavior.IsEnabled get set
Indicates whether the component is enabled and can be toggled.
Implements IuvoUnity.Interfaces.ITogglable.
{ get; set; }
Referenced by Disable(), Enable(), and Tick().
PriorityLevel
PriorityLevel IuvoUnity.BaseClasses.SemiBehavior.PriorityLevel = PriorityLevel.None get set
Implements IuvoUnity.DataStructs.IPriority.
{ get; set; } = PriorityLevel.None;
priorityScale
ClampedData<float> IuvoUnity.BaseClasses.SemiBehavior.priorityScale = new ClampedFloat(new RangeF(0, 1), 0.5f) get set
Implements IuvoUnity.DataStructs.IPriority.
{ get; set; } = new ClampedFloat(new RangeF(0, 1), 0.5f);
updateMode
UpdateMode IuvoUnity.BaseClasses.SemiBehavior.updateMode get set
Determines which update loop (Update, FixedUpdate, LateUpdate) is used.
{ get => _updateMode; set => _updateMode = value; }
Referenced by FixedUpdate(), LateUpdate(), IuvoUnity.BaseClasses.SemiBehaviorManager.Register(), RegisterUpdateLoop(), and Update().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/BaseClasses/SemiBehavior.cs