Iuvo Unity: IuvoUnity.Extensions.CameraExtensions Class Reference
IuvoUnity.Extensions.CameraExtensions Class Reference
Static Public Member Functions
static void Initialize (MonoBehaviour runner)
Initializes the CameraExtensions with a coroutine runner.
static void ShakeScreen (this Camera camera, float magnitude, float duration)
Shakes the camera screen by applying random offsets to its position.
static void SetBackgroundColor (this Camera camera, Color color)
Sets the camera's background color.
static void FadeOut (this Camera camera, float duration)
Fades the camera's background to transparent over a given duration.
static void FadeIn (this Camera camera, float duration)
Fades the camera's background from transparent to opaque over a given duration.
static void MoveToPosition (this Camera camera, Vector3 targetPosition, float speed)
Moves the camera towards a target position at a specified speed.
static void RotateToRotation (this Camera camera, Quaternion targetRotation, float speed)
Rotates the camera towards a target rotation at a specified speed.
static void LookAt (this Camera camera, Transform target)
Makes the camera look at a specified target.
static void LookAt (this Camera camera, Vector3 target)
Makes the camera look at a specified target position.
static void LookAt (this Camera camera, GameObject target)
Makes the camera look at a specified target GameObject.
static void Follow (this Camera camera, Transform target, Vector3 offset)
Makes the camera follow a specified target with an offset.
static void ZoomIn (this Camera camera, float amount)
Zooms in the camera by reducing its field of view.
static void ZoomOut (this Camera camera, float amount)
Zooms out the camera by increasing its field of view.
static void SetPosition (this Camera camera, Vector3 position)
Sets the camera's position to a specific value.
static void SetRotation (this Camera camera, Quaternion rotation)
Sets the camera's rotation to a specific value.
static void LockRotationAxis (this Camera camera, Vector3 lockedAxis)
Locks the camera's rotation on specific axes.
static void SetRenderTarget (this Camera camera, RenderTexture renderTexture)
Sets the camera's render target to a specific RenderTexture.
static Ray GetCenterRay (this Camera camera)
Gets a ray from the center of the camera's viewport.
static ? RaycastHit RaycastFromCenter (this Camera camera, float maxDistance, LayerMask layerMask)
Performs a raycast from the center of the camera's viewport.
Static Private Member Functions
static IEnumerator ShakeScreenCoroutine (Camera camera, float magnitude, float duration)
static IEnumerator FadeOutCoroutine (Camera camera, float duration)
static IEnumerator FadeInCoroutine (Camera camera, float duration)
Static Private Attributes
static MonoBehaviour coroutineRunner
Member Function Documentation
FadeIn()
void IuvoUnity.Extensions.CameraExtensions.FadeIn (this Camera camera, float duration) static
Fades the camera's background from transparent to opaque over a given duration.
Parameters
camera The camera to fade.
duration The time, in seconds, for the fade effect.
            {
                coroutineRunner.StartCoroutine(FadeInCoroutine(camera, duration));
            }
References coroutineRunner, and FadeInCoroutine().
FadeInCoroutine()
IEnumerator IuvoUnity.Extensions.CameraExtensions.FadeInCoroutine (Camera camera, float duration) static private
            {
                float startAlpha = camera.backgroundColor.a;
                float timer = 0;
                while (timer < duration)
                {
                    Color newColor = camera.backgroundColor;
                    newColor.a = Mathf.Lerp(startAlpha, 1, timer / duration);
                    camera.backgroundColor = newColor;
                    timer += Time.deltaTime;
                    yield return null;
                }
            }
Referenced by FadeIn().
FadeOut()
void IuvoUnity.Extensions.CameraExtensions.FadeOut (this Camera camera, float duration) static
Fades the camera's background to transparent over a given duration.
Parameters
camera The camera to fade.
duration The time, in seconds, for the fade effect.
            {
                coroutineRunner.StartCoroutine(FadeOutCoroutine(camera, duration));
            }
References coroutineRunner, and FadeOutCoroutine().
FadeOutCoroutine()
IEnumerator IuvoUnity.Extensions.CameraExtensions.FadeOutCoroutine (Camera camera, float duration) static private
            {
                float startAlpha = camera.backgroundColor.a;
                float timer = 0;
                while (timer < duration)
                {
                    Color newColor = camera.backgroundColor;
                    newColor.a = Mathf.Lerp(startAlpha, 0, timer / duration);
                    camera.backgroundColor = newColor;
                    timer += Time.deltaTime;
                    yield return null;
                }
            }
Referenced by FadeOut().
Follow()
void IuvoUnity.Extensions.CameraExtensions.Follow (this Camera camera, Transform target, Vector3 offset) static
Makes the camera follow a specified target with an offset.
Parameters
camera The camera to follow the target.
target The target to follow.
offset The offset from the target.
            {
                camera.transform.position = target.position + offset;
            }
GetCenterRay()
Ray IuvoUnity.Extensions.CameraExtensions.GetCenterRay (this Camera camera) static
Gets a ray from the center of the camera's viewport.
Parameters
camera The camera from which the ray is cast.
Returns
A ray originating from the center of the camera's viewport.
            {
                return camera.ViewportPointToRay(new Vector3(0.5f, 0.5f, 0));
            }
Initialize()
void IuvoUnity.Extensions.CameraExtensions.Initialize (MonoBehaviour runner) static
Initializes the CameraExtensions with a coroutine runner.
Parameters
runner The MonoBehaviour instance used to run coroutines.
            {
                coroutineRunner = runner;
            }
References coroutineRunner.
LockRotationAxis()
void IuvoUnity.Extensions.CameraExtensions.LockRotationAxis (this Camera camera, Vector3 lockedAxis) static
Locks the camera's rotation on specific axes.
Parameters
camera The camera whose rotation axes are to be locked.
lockedAxis The axes to lock (x, y, z).
            {
                camera.transform.eulerAngles = new Vector3(camera.transform.eulerAngles.x * lockedAxis.x,
                                                            camera.transform.eulerAngles.y * lockedAxis.y,
                                                            camera.transform.eulerAngles.z * lockedAxis.z);
            }
LookAt() [1/3]
void IuvoUnity.Extensions.CameraExtensions.LookAt (this Camera camera, GameObject target) static
Makes the camera look at a specified target GameObject.
Parameters
camera The camera to look at the target.
target The target GameObject to look at.
            {
                camera.transform.LookAt(target.transform);
            }
LookAt() [2/3]
void IuvoUnity.Extensions.CameraExtensions.LookAt (this Camera camera, Transform target) static
Makes the camera look at a specified target.
Parameters
camera The camera to look at the target.
target The target to look at.
            {
                camera.transform.LookAt(target);
            }
LookAt() [3/3]
void IuvoUnity.Extensions.CameraExtensions.LookAt (this Camera camera, Vector3 target) static
Makes the camera look at a specified target position.
Parameters
camera The camera to look at the target.
target The target position to look at.
            {
                camera.transform.LookAt(target);
            }
MoveToPosition()
void IuvoUnity.Extensions.CameraExtensions.MoveToPosition (this Camera camera, Vector3 targetPosition, float speed) static
Moves the camera towards a target position at a specified speed.
Parameters
camera The camera to move.
targetPosition The target position to move towards.
speed The speed of the movement.
            {
                camera.transform.position = Vector3.Lerp(camera.transform.position, targetPosition, speed * Time.deltaTime);
            }
RaycastFromCenter()
? RaycastHit IuvoUnity.Extensions.CameraExtensions.RaycastFromCenter (this Camera camera, float maxDistance, LayerMask layerMask) static
Performs a raycast from the center of the camera's viewport.
Parameters
camera The camera to perform the raycast from.
maxDistance The maximum distance the ray should check for collisions.
layerMask The layers to include in the raycast.
Returns
A RaycastHit containing information about the hit, or null if no hit occurred.
            {
                Ray ray = camera.ViewportPointToRay(new Vector3(0.5f, 0.5f, 0));
                if (Physics.Raycast(ray, out RaycastHit hit, maxDistance, layerMask))
                    return hit;
                return null;
            }
RotateToRotation()
void IuvoUnity.Extensions.CameraExtensions.RotateToRotation (this Camera camera, Quaternion targetRotation, float speed) static
Rotates the camera towards a target rotation at a specified speed.
Parameters
camera The camera to rotate.
targetRotation The target rotation to rotate towards.
speed The speed of the rotation.
            {
                camera.transform.rotation = Quaternion.Lerp(camera.transform.rotation, targetRotation, speed * Time.deltaTime);
            }
SetBackgroundColor()
void IuvoUnity.Extensions.CameraExtensions.SetBackgroundColor (this Camera camera, Color color) static
Sets the camera's background color.
Parameters
camera The camera whose background color is to be set.
color The color to set as the background.
            {
                camera.backgroundColor = color;
            }
SetPosition()
void IuvoUnity.Extensions.CameraExtensions.SetPosition (this Camera camera, Vector3 position) static
Sets the camera's position to a specific value.
Parameters
camera The camera to set the position for.
position The position to set for the camera.
            {
                camera.transform.position = position;
            }
SetRenderTarget()
void IuvoUnity.Extensions.CameraExtensions.SetRenderTarget (this Camera camera, RenderTexture renderTexture) static
Sets the camera's render target to a specific RenderTexture.
Parameters
camera The camera to set the render target for.
renderTexture The RenderTexture to use as the render target.
            {
                camera.targetTexture = renderTexture;
            }
SetRotation()
void IuvoUnity.Extensions.CameraExtensions.SetRotation (this Camera camera, Quaternion rotation) static
Sets the camera's rotation to a specific value.
Parameters
camera The camera to set the rotation for.
rotation The rotation to set for the camera.
            {
                camera.transform.rotation = rotation;
            }
ShakeScreen()
void IuvoUnity.Extensions.CameraExtensions.ShakeScreen (this Camera camera, float magnitude, float duration) static
Shakes the camera screen by applying random offsets to its position.
Parameters
camera The camera to shake.
magnitude The magnitude of the shake (larger values produce a stronger shake).
duration How long the shake will last, in seconds.
            {
                coroutineRunner.StartCoroutine(ShakeScreenCoroutine(camera, magnitude, duration));
            }
References coroutineRunner, and ShakeScreenCoroutine().
ShakeScreenCoroutine()
IEnumerator IuvoUnity.Extensions.CameraExtensions.ShakeScreenCoroutine (Camera camera, float magnitude, float duration) static private
            {
                Vector3 originalPosition = camera.transform.position;
                float timeElapsed = 0f;
                while (timeElapsed < duration)
                {
                    camera.transform.position = originalPosition + UnityEngine.Random.insideUnitSphere * magnitude;
                    timeElapsed += Time.deltaTime;
                    yield return null;
                }
                camera.transform.position = originalPosition;
            }
Referenced by ShakeScreen().
ZoomIn()
void IuvoUnity.Extensions.CameraExtensions.ZoomIn (this Camera camera, float amount) static
Zooms in the camera by reducing its field of view.
Parameters
camera The camera to zoom in.
amount The amount to zoom in, reducing the field of view.
            {
                camera.fieldOfView -= amount;
            }
ZoomOut()
void IuvoUnity.Extensions.CameraExtensions.ZoomOut (this Camera camera, float amount) static
Zooms out the camera by increasing its field of view.
Parameters
camera The camera to zoom out.
amount The amount to zoom out, increasing the field of view.
            {
                camera.fieldOfView += amount;
            }
Member Data Documentation
coroutineRunner
MonoBehaviour IuvoUnity.Extensions.CameraExtensions.coroutineRunner static private
Referenced by FadeIn(), FadeOut(), Initialize(), and ShakeScreen().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Extensions/CameraExtensions.cs