Iuvo Unity: IuvoUnity.ProceduralGeneration.Room Class Reference
IuvoUnity.ProceduralGeneration.Room Class Reference
Public Member Functions
void Start ()
Room (Vector3 position, int width, int height, int length, GameObject roomPrefab)
void InitializeRoom (Vector3 size, bool isBoundaryRoom)
Sets up the room dimensions and other properties.
void DisableWall (int wallID)
void CountBoundaryWalls ()
void RemoveSharedWalls (List< Room > allRooms)
Wall GetWallFacingPosition (Vector3 position)
Static Public Member Functions
static Room CreateRoom (Vector3 position, Vector3 size, GameObject roomPrefab, bool isBoundaryRoom)
Factory method to create a Room instance.
Public Attributes
BoxCollider roomBounds
Vector3 center
GameObject roomFloor
Wall northWall
Wall eastWall
Wall southWall
Wall westWall
List< Wall > walls = new List<Wall>()
Transform Top_Middle
Transform Bottom_Middle
Transform Left_Middle
Transform Right_Middle
int boundaryWalls = 0
Properties
bool IsBoundaryRoom = false [get, private set]
bool IsNextToBoundaryRoom [get, private set]
Constructor & Destructor Documentation
Room()
IuvoUnity.ProceduralGeneration.Room.Room (Vector3 position, int width, int height, int length, GameObject roomPrefab)
            {
                GameObject roomObject = Object.Instantiate(roomPrefab, position, Quaternion.identity);
                Room room = roomObject.GetComponent<Room>();
                room.roomBounds.size = new Vector3(width, height, length);
            }
References Room().
Referenced by CreateRoom(), RemoveSharedWalls(), and Room().
Member Function Documentation
CountBoundaryWalls()
void IuvoUnity.ProceduralGeneration.Room.CountBoundaryWalls ()
            {
                int boundaryWalls = 0;
                if (northWall.iAmBoundaryWall)
                {
                    boundaryWalls++;
                }
                if (southWall.iAmBoundaryWall)
                {
                    boundaryWalls++;
                }
                if (westWall.iAmBoundaryWall)
                {
                    boundaryWalls++;
                }
                if (eastWall.iAmBoundaryWall)
                {
                    boundaryWalls++;
                }
                if (boundaryWalls != 0)
                {
                    IsBoundaryRoom = true;
                }
            }
References boundaryWalls, eastWall, IsBoundaryRoom, northWall, southWall, and westWall.
Referenced by Start().
CreateRoom()
Room IuvoUnity.ProceduralGeneration.Room.CreateRoom (Vector3 position, Vector3 size, GameObject roomPrefab, bool isBoundaryRoom) static
Factory method to create a Room instance.
Parameters
position The position of the room.
size The size of the room.
roomPrefab The room prefab.
isBoundaryRoom Indicates if this room is a boundary room.
Returns
A new Room instance.
            {
                if (roomPrefab == null)
                {
                    IuvoDebug.DebugLogError("Room prefab is null.");
                    return null;
                }
                GameObject roomObject = Instantiate(roomPrefab, position, Quaternion.identity);
                Room room = roomObject.GetComponent<Room>();
                if (room == null)
                {
                    IuvoDebug.DebugLogError("The provided prefab does not have a Room component.");
                    Destroy(roomObject);
                    return null;
                }
                room.InitializeRoom(size, isBoundaryRoom);
                return room;
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), InitializeRoom(), and Room().
DisableWall()
void IuvoUnity.ProceduralGeneration.Room.DisableWall (int wallID)
            {
                if (wallID == 16)
                {
                    if (northWall != null && !northWall.iAmBoundaryWall)
                    {
                        if (northWall.siblingWall != null)
{
                            Destroy(northWall.siblingWall);
                        }
                        northWall.Destroy();
                    }
                    if (eastWall != null && !eastWall.iAmBoundaryWall)
                    {
                        if (eastWall.siblingWall != null)
{
                            Destroy(eastWall.siblingWall);
                        }
                        eastWall.Destroy();
                    }
                    if (southWall != null && !southWall.iAmBoundaryWall)
                    {
                        if (southWall.siblingWall != null)
{
                            Destroy(southWall.siblingWall);
                        }
                        southWall.Destroy();
                    }
                    if (westWall != null && !westWall.iAmBoundaryWall)
                    {
                        if (westWall.siblingWall != null)
{
                            Destroy(westWall.siblingWall);
                        }
                        westWall.Destroy();
                    }
                }
                else if (wallID == 1)
                {
                    if (northWall != null && !northWall.iAmBoundaryWall)
                    {
                        if (northWall.siblingWall != null)
{
                            Destroy(northWall.siblingWall);
                        }
                        northWall.Destroy();
                    }
                }
                else if (wallID == 2)
                {
                    if (eastWall != null && !eastWall.iAmBoundaryWall)
                    {
                        if (eastWall.siblingWall != null)
{
                            Destroy(eastWall.siblingWall);
                        }
                        eastWall.Destroy();
                    }
                }
                else if (wallID == 3)
                {
                    if (southWall != null && !southWall.iAmBoundaryWall)
                    {
                        if (southWall.siblingWall != null)
{
                            Destroy(southWall.siblingWall);
                        }
                        southWall.Destroy();
                    }
                }
                else if (wallID == 4)
                {
                    if (westWall != null && !westWall.iAmBoundaryWall)
                    {
                        if (westWall.siblingWall != null)
{
                            Destroy(westWall.siblingWall);
                        }
                        westWall.Destroy();
                    }
                }
                else if (wallID == 5)
                {
                    if (northWall != null && !northWall.iAmBoundaryWall)
                    {
                        if (northWall.siblingWall != null)
{
                            Destroy(northWall.siblingWall);
                        }
                        northWall.Destroy();
                    }
                    if (westWall != null && !westWall.iAmBoundaryWall)
                    {
                        if (westWall.siblingWall != null)
{
                            Destroy(westWall.siblingWall);
                        }
                        westWall.Destroy();
                    }
                }
                else if (wallID == 6)
                {
                    if (eastWall != null && !eastWall.iAmBoundaryWall)
                    {
                        if (eastWall.siblingWall != null)
{
                            Destroy(eastWall.siblingWall);
                        }
                        eastWall.Destroy();
                    }
                    if (southWall != null && !southWall.iAmBoundaryWall)
                    {
                        if (southWall.siblingWall != null)
{
                            Destroy(southWall.siblingWall);
                        }
                        southWall.Destroy();
                    }
                }
                else if (wallID == 7)
                {
                    if (southWall != null && !southWall.iAmBoundaryWall)
                    {
                        if (southWall.siblingWall != null)
{
                            Destroy(southWall.siblingWall);
                        }
                        southWall.Destroy();
                    }
                    if (westWall != null && !westWall.iAmBoundaryWall)
                    {
                        if (westWall.siblingWall != null)
{
                            Destroy(westWall.siblingWall);
                        }
                        westWall.Destroy();
                    }
                }
                else if (wallID == 8)
                {
                    if (northWall != null && !northWall.iAmBoundaryWall)
                    {
                        if (northWall.siblingWall != null)
{
                            Destroy(northWall.siblingWall);
                        }
                        northWall.Destroy();
                    }
                    if (eastWall != null && !eastWall.iAmBoundaryWall)
                    {
                        if (eastWall.siblingWall != null)
{
                            Destroy(eastWall.siblingWall);
                        }
                        eastWall.Destroy();
                    }
                }
                else if (wallID == 9)
                {
                    if (eastWall != null && !eastWall.iAmBoundaryWall)
                    {
                        if (eastWall.siblingWall != null)
{
                            Destroy(eastWall.siblingWall);
                        }
                        eastWall.Destroy();
                    }
                    if (westWall != null && !westWall.iAmBoundaryWall)
                    {
                        if (westWall.siblingWall != null)
{
                            Destroy(westWall.siblingWall);
                        }
                        westWall.Destroy();
                    }
                }
                else if (wallID == 10)
                {
                    if (northWall != null && !northWall.iAmBoundaryWall)
                    {
                        if (northWall.siblingWall != null)
{
                            Destroy(northWall.siblingWall);
                        }
                        northWall.Destroy();
                    }
                    if (southWall != null && !southWall.iAmBoundaryWall)
                    {
                        if (southWall.siblingWall != null)
{
                            Destroy(southWall.siblingWall);
                        }
                        southWall.Destroy();
                    }
                }
                else if (wallID == 11)
                {
                    if (northWall != null && !northWall.iAmBoundaryWall)
                    {
                        if (northWall.siblingWall != null)
{
                            Destroy(northWall.siblingWall);
                        }
                        northWall.Destroy();
                    }
                    if (southWall != null && !southWall.iAmBoundaryWall)
                    {
                        if (southWall.siblingWall != null)
{
                            Destroy(southWall.siblingWall);
                        }
                        southWall.Destroy();
                    }
                    if (eastWall != null && !eastWall.iAmBoundaryWall)
                    {
                        if (eastWall.siblingWall != null)
{
                            Destroy(eastWall.siblingWall);
                        }
                        eastWall.Destroy();
                    }
                }
                else if (wallID == 12)
                {
                    if (northWall != null && !northWall.iAmBoundaryWall)
                    {
                        if (northWall.siblingWall != null)
{
                            Destroy(northWall.siblingWall);
                        }
                        northWall.Destroy();
                    }
                    if (southWall != null && !southWall.iAmBoundaryWall)
                    {
                        if (southWall.siblingWall != null)
{
                            Destroy(southWall.siblingWall);
                        }
                        southWall.Destroy();
                    }
                    if (westWall != null && !westWall.iAmBoundaryWall)
                    {
                        if (westWall.siblingWall != null)
{
                            Destroy(westWall.siblingWall);
                        }
                        westWall.Destroy();
                    }
                }
                else if (wallID == 13)
                {
                    if (southWall != null && !southWall.iAmBoundaryWall)
                    {
                        if (southWall.siblingWall != null)
{
                            Destroy(southWall.siblingWall);
                        }
                        southWall.Destroy();
                    }
                    if (eastWall != null && !eastWall.iAmBoundaryWall)
                    {
                        if (eastWall.siblingWall != null)
{
                            Destroy(eastWall.siblingWall);
                        }
                        eastWall.Destroy();
                    }
                    if (westWall != null && !westWall.iAmBoundaryWall)
                    {
                        if (westWall.siblingWall != null)
{
                            Destroy(westWall.siblingWall);
                        }
                        westWall.Destroy();
                    }
                }
                else if (wallID == 14)
                {
                    if (northWall != null && !northWall.iAmBoundaryWall)
                    {
                        if (northWall.siblingWall != null)
{
                            Destroy(northWall.siblingWall);
                        }
                        northWall.Destroy();
                    }
                    if (westWall != null && !westWall.iAmBoundaryWall)
                    {
                        if (westWall.siblingWall != null)
{
                            Destroy(westWall.siblingWall);
                        }
                        westWall.Destroy();
                    }
                    if (eastWall != null && !eastWall.iAmBoundaryWall)
                    {
                        if (eastWall.siblingWall != null)
{
                            Destroy(eastWall.siblingWall);
                        }
                        eastWall.Destroy();
                    }
                }
                else if (wallID == 15)
                {
                    if (roomFloor != null)
                    {
                        roomFloor.gameObject.gameObject.SetActive(false);
                    }
                }
                else { return; }
            }
References eastWall, northWall, roomFloor, southWall, and westWall.
GetWallFacingPosition()
Wall IuvoUnity.ProceduralGeneration.Room.GetWallFacingPosition (Vector3 position)
            {
                foreach (Wall wall in walls)
                {
                    // Check if the wall faces the given position
                    if (Vector3.Dot(wall.transform.forward, position - wall.transform.position) > 0)
                    {
                        return wall;
                    }
                }
                return null;
            }
References walls.
Referenced by RemoveSharedWalls().
InitializeRoom()
void IuvoUnity.ProceduralGeneration.Room.InitializeRoom (Vector3 size, bool isBoundaryRoom)
Sets up the room dimensions and other properties.
Parameters
size The size of the room.
            {
                if (roomBounds == null)
                {
                    IuvoDebug.DebugLogError("BoxCollider is missing on the Room GameObject.");
                    return;
                }
                roomBounds.size = size;
                center = roomBounds.center;
                IsBoundaryRoom = isBoundaryRoom;
            }
References center, IuvoUnity.Debug.IuvoDebug.DebugLogError(), IsBoundaryRoom, and roomBounds.
Referenced by CreateRoom().
RemoveSharedWalls()
void IuvoUnity.ProceduralGeneration.Room.RemoveSharedWalls (List< Room > allRooms)
            {
                foreach (Wall wall in walls)
                {
                    Collider wallCollider = wall.GetComponent<Collider>();
                    if (wallCollider == null)
                    {
                        IuvoDebug.DebugLogError($"Wall {wall.name} has no collider. Skipping.");
                        continue;
                    }
                    // Calculate raycast length based on wall dimensions
                    float rayLength = wallCollider.bounds.size.z / 2f + 0.1f; // Add a small buffer to ensure overlap detection
                    RaycastHit hit;
                    if (Physics.Raycast(wall.transform.position, -wall.transform.forward, out hit, rayLength))
                    {
                        // Check if the ray hit another room
                        Room neighboringRoom = hit.transform.GetComponentInParent<Room>();
                        if (neighboringRoom != null && neighboringRoom != this)
{
                            // Remove the wall in both rooms
                            wall.gameObject.SetActive(false);
                            Wall correspondingWall = neighboringRoom.GetWallFacingPosition(wall.transform.position);
                            if (correspondingWall != null)
{
                                correspondingWall.gameObject.SetActive(false);
                            }
                        }
                    }
                }
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), GetWallFacingPosition(), Room(), and walls.
Start()
void IuvoUnity.ProceduralGeneration.Room.Start ()
            {
                if (roomFloor == null)
                {
                    IuvoDebug.DebugLogError("Room floor prefab is null. Cannot create room.");
                    return;
                }
                roomBounds = GetComponent<BoxCollider>();
                if (roomBounds == null)
                {
                    IuvoDebug.DebugLogError("BoxCollider is missing on the Room GameObject.");
                    return;
                }
                center = roomBounds.center;
                //CheckBoundaryWalls();
                northWall.myNumber = 1;
                eastWall.myNumber = 2;
                southWall.myNumber = 3;
                westWall.myNumber = 4;
                // Assigning this room to each of the present room's walls
                // North Wall
                if (northWall != null)
                {
                    northWall.myRoom = this;
                    walls.Add(northWall);
                }
                else
                {
                    IuvoDebug.DebugLogError("Room is missing North Wall.");
                }
                //South Wall
                if (southWall != null)
                {
                    southWall.myRoom = this;
                    walls.Add(southWall);
                }
                else
                {
                    IuvoDebug.DebugLogError("Room is missing South Wall.");
                }
                //East Wall
                if (eastWall != null)
                {
                    eastWall.myRoom = this;
                    walls.Add(eastWall);
                }
                else
                {
                    IuvoDebug.DebugLogError("Room is missing East Wall.");
                }
                //West Wall
                if (westWall != null)
                {
                    westWall.myRoom = this;
                    walls.Add(westWall);
                }
                else
                {
                    IuvoDebug.DebugLogError("Room is missing West Wall.");
                }
                // Counts the number of walls that identify as boundaries
                // if that number is greater than zero the room is
                // marked as a boundary room as well
                CountBoundaryWalls();
                for (int i = 0; i < walls.Count; i++)
                {
                    if (walls[i].iAmBoundaryWall)
                    {
                        for (int j = 0; j < walls[i].myContacts.Count; j++)
{
                            if (walls[i].myContacts[j].transform == walls[i].transform)
{
                                var wall = walls[i].myContacts[j].GetComponent<Wall>();
                                if (wall != null)
                                { wall.Destroy(); }
                            }
                        }
                        walls.RemoveAt(i);
                    }
                }
            }
References center, CountBoundaryWalls(), IuvoUnity.Debug.IuvoDebug.DebugLogError(), eastWall, northWall, roomBounds, roomFloor, southWall, walls, and westWall.
Member Data Documentation
Bottom_Middle
Transform IuvoUnity.ProceduralGeneration.Room.Bottom_Middle
boundaryWalls
int IuvoUnity.ProceduralGeneration.Room.boundaryWalls = 0
Referenced by CountBoundaryWalls().
center
Vector3 IuvoUnity.ProceduralGeneration.Room.center
Referenced by InitializeRoom(), and Start().
eastWall
Wall IuvoUnity.ProceduralGeneration.Room.eastWall
Referenced by CountBoundaryWalls(), DisableWall(), IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.GenerateGridRoom(), and Start().
Left_Middle
Transform IuvoUnity.ProceduralGeneration.Room.Left_Middle
northWall
Wall IuvoUnity.ProceduralGeneration.Room.northWall
Referenced by CountBoundaryWalls(), DisableWall(), IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.GenerateGridRoom(), and Start().
Right_Middle
Transform IuvoUnity.ProceduralGeneration.Room.Right_Middle
roomBounds
BoxCollider IuvoUnity.ProceduralGeneration.Room.roomBounds
Referenced by InitializeRoom(), and Start().
roomFloor
GameObject IuvoUnity.ProceduralGeneration.Room.roomFloor
Referenced by DisableWall(), IuvoUnity.ProceduralGeneration.Dungeons.DungeonManager.GenerateGridOfRooms(), and Start().
southWall
Wall IuvoUnity.ProceduralGeneration.Room.southWall
Referenced by CountBoundaryWalls(), DisableWall(), IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.GenerateGridRoom(), and Start().
Top_Middle
Transform IuvoUnity.ProceduralGeneration.Room.Top_Middle
walls
List<Wall> IuvoUnity.ProceduralGeneration.Room.walls = new List<Wall>()
Referenced by GetWallFacingPosition(), RemoveSharedWalls(), and Start().
westWall
Wall IuvoUnity.ProceduralGeneration.Room.westWall
Referenced by CountBoundaryWalls(), DisableWall(), IuvoUnity.ProceduralGeneration.Dungeons.GridDungeonManager.GenerateGridRoom(), and Start().
Property Documentation
IsBoundaryRoom
bool IuvoUnity.ProceduralGeneration.Room.IsBoundaryRoom = false get private set
{ get; private set; } = false;
Referenced by CountBoundaryWalls(), and InitializeRoom().
IsNextToBoundaryRoom
bool IuvoUnity.ProceduralGeneration.Room.IsNextToBoundaryRoom get private set
{ get; private set; }
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ProceduralGenerationBases/Dungeons/Room.cs