Iuvo Unity: IuvoUnity.Configurations.BaseConfig< T > Class Template Reference
IuvoUnity.Configurations.BaseConfig< T > Class Template Reference abstract
Public Member Functions
virtual void Configure (T configurable)
virtual void Reconfigure (T reconfigurable)
virtual string GetConfigSerializePath (string actingConfigClass, string objectToSerializeName, string parentConfigClass="BaseConfig")
virtual void PrintInfo ()
Public Attributes
string configName
Member Function Documentation
Configure()
virtual void IuvoUnity.Configurations.BaseConfig< T >.Configure (T configurable) virtual
Implements IuvoUnity.Interfaces.IConfigure< T >.
            {
                configurable.OnConfigure();
            }
GetConfigSerializePath()
virtual string IuvoUnity.Configurations.BaseConfig< T >.GetConfigSerializePath (string actingConfigClass, string objectToSerializeName, string parentConfigClass = "BaseConfig") virtual
            {
                if (string.IsNullOrWhiteSpace(actingConfigClass))
                {
                    IuvoDebug.DebugLogError("Acting config class name cannot be null or empty.");
                    return null;
                }
                if (string.IsNullOrWhiteSpace(objectToSerializeName))
                {
                    IuvoDebug.DebugLogError("Object to serialize name cannot be null or empty.");
                    return null;
                }
                if (string.Compare(parentConfigClass, "BaseConfig", true) == 0)
                {
                    IuvoDebug.DebugLogWarning("Parent config class is set to BaseConfig. Consider using a more specific parent class.");
                }
                string filePath =  Path.Combine(Application.persistentDataPath, "Configurations" ,parentConfigClass, actingConfigClass, objectToSerializeName + ".json");
                Directory.CreateDirectory(Path.GetDirectoryName(filePath));
                return filePath;
            }
References IuvoUnity.Debug.IuvoDebug.DebugLogError(), and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
Referenced by IuvoUnity.Configurations.LevelConfiguration.DeserializeLevelComponent(), and IuvoUnity.Configurations.LevelConfiguration.Serialize().
PrintInfo()
virtual void IuvoUnity.Configurations.BaseConfig< T >.PrintInfo () virtual
Reimplemented in IuvoUnity.Configurations.HealthConfiguration, IuvoUnity.Configurations.ItemConfiguration, IuvoUnity.Configurations.LevelConfiguration, and IuvoUnity.Configurations.TimerConfiguration.
            {
                IuvoDebug.DebugLog(string.Concat("Config: ", configName));
            }
References configName, and IuvoUnity.Debug.IuvoDebug.DebugLog().
Reconfigure()
virtual void IuvoUnity.Configurations.BaseConfig< T >.Reconfigure (T reconfigurable) virtual
Implements IuvoUnity.Interfaces.IReconfigure< T >.
            {
                reconfigurable.OnReconfigure();
            }
Member Data Documentation
configName
string IuvoUnity.Configurations.BaseConfig< T >.configName
Referenced by IuvoUnity.Configurations.ItemConfiguration.OnEnable(), IuvoUnity.Configurations.LevelConfiguration.OnEnable(), IuvoUnity.Configurations.TimerConfiguration.OnEnable(), and PrintInfo().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Configurations/BaseConfig.cs