Iuvo Unity: IuvoUnity.DataStructs.History< T > Class Template Reference
IuvoUnity.DataStructs.History< T > Class Template Reference
Public Member Functions
void Push (T state)
T Undo ()
void Redo (T state)
Private Attributes
Stack< T > _past = new Stack<T>()
Stack< T > _future = new Stack<T>()
Member Function Documentation
Push()
void IuvoUnity.DataStructs.History< T >.Push (T state)
            {
                _past.Push(state);
                _future.Clear();
            }
References _future, and _past.
Redo()
void IuvoUnity.DataStructs.History< T >.Redo (T state)
=> _future.Push(state);
References _future.
Undo()
T IuvoUnity.DataStructs.History< T >.Undo ()
=> _past.Count > 0 ? _past.Pop() : default;
References _past.
Member Data Documentation
_future
Stack<T> IuvoUnity.DataStructs.History< T >._future = new Stack<T>() private
Referenced by Push(), and Redo().
_past
Stack<T> IuvoUnity.DataStructs.History< T >._past = new Stack<T>() private
Referenced by Push(), and Undo().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/History.cs