Iuvo Unity: IuvoUnity.DataStructs.TransformContext Class Reference
IuvoUnity.DataStructs.TransformContext Class Reference
Public Member Functions
TransformContext ()
void Dispose ()
void SetTransform (Transform transform)
Transform GetTransform ()
bool TryGetTransform (out Transform transform)
void SetPosition (Vector3 position)
Vector3 GetPosition ()
bool TryGetPosition (out Vector3 position)
void SetDestination (Vector3 destination)
Vector3 GetDestination ()
bool TryGetDestination (out Vector3 destination)
void SetVelocity (Vector3 velocity)
Vector3 GetVelocity ()
bool TryGetVelocity (out Vector3 velocity)
void SetDirection (Vector3 direction)
Vector3 GetDirection ()
bool TryGetDirection (out Vector3 direction)
void SetLookTarget (Vector3 lookTarget)
Vector3 GetLookTarget ()
bool TryGetLookTarget (out Vector3 lookTarget)
void SetLastDirection (Vector3 lastDirection)
Vector3 GetLastDirection ()
bool TryGetLastDirection (out Vector3 lastDirection)
void SetInputDirection (Vector3 inputDirection)
Vector3 GetInputDirection ()
bool TryGetInputDirection (out Vector3 inputDirection)
void SetMoveSpeed (float moveSpeed)
float GetMoveSpeed ()
bool TryGetMoveSpeed (out float moveSpeed)
Private Member Functions
void Set< T > (ContextKey_TRANSFORM key, T value)
T Get< T > (ContextKey_TRANSFORM key)
bool TryGet< T > (ContextKey_TRANSFORM key, out T value)
Private Attributes
readonly Dictionary< ContextKey_TRANSFORM, object > _data = new()
Constructor & Destructor Documentation
TransformContext()
IuvoUnity.DataStructs.TransformContext.TransformContext ()
            {
                // Initialize all keys with default values
                foreach (ContextKey_TRANSFORM key in System.Enum.GetValues(typeof(ContextKey_TRANSFORM)))
                {
                    _data[key] = default;
                }
            }
References _data.
Member Function Documentation
Dispose()
void IuvoUnity.DataStructs.TransformContext.Dispose ()
Implements IuvoUnity.Interfaces.IContext.
            {
                _data.Clear();
            }
References _data.
Get< T >()
T IuvoUnity.DataStructs.TransformContext.Get< T > (ContextKey_TRANSFORM key) private
            {
                if (_data.TryGetValue(key, out var value) && value is T cast)
                    return cast;
                return default;
            }
References _data.
GetDestination()
Vector3 IuvoUnity.DataStructs.TransformContext.GetDestination ()
=> Get<Vector3>(ContextKey_TRANSFORM.Destination);
GetDirection()
Vector3 IuvoUnity.DataStructs.TransformContext.GetDirection ()
=> Get<Vector3>(ContextKey_TRANSFORM.Direction);
GetInputDirection()
Vector3 IuvoUnity.DataStructs.TransformContext.GetInputDirection ()
=> Get<Vector3>(ContextKey_TRANSFORM.InputDirection);
GetLastDirection()
Vector3 IuvoUnity.DataStructs.TransformContext.GetLastDirection ()
=> Get<Vector3>(ContextKey_TRANSFORM.LastDirection);
GetLookTarget()
Vector3 IuvoUnity.DataStructs.TransformContext.GetLookTarget ()
=> Get<Vector3>(ContextKey_TRANSFORM.LookTarget);
GetMoveSpeed()
float IuvoUnity.DataStructs.TransformContext.GetMoveSpeed ()
=> Get<float>(ContextKey_TRANSFORM.MoveSpeed);
GetPosition()
Vector3 IuvoUnity.DataStructs.TransformContext.GetPosition ()
=> Get<Vector3>(ContextKey_TRANSFORM.Position);
GetTransform()
Transform IuvoUnity.DataStructs.TransformContext.GetTransform ()
=> Get<Transform>(ContextKey_TRANSFORM.Transform);
GetVelocity()
Vector3 IuvoUnity.DataStructs.TransformContext.GetVelocity ()
=> Get<Vector3>(ContextKey_TRANSFORM.Velocity);
Set< T >()
void IuvoUnity.DataStructs.TransformContext.Set< T > (ContextKey_TRANSFORM key, T value) private
            {
                _data[key] = value;
            }
References _data.
SetDestination()
void IuvoUnity.DataStructs.TransformContext.SetDestination (Vector3 destination)
=> Set(ContextKey_TRANSFORM.Destination, destination);
SetDirection()
void IuvoUnity.DataStructs.TransformContext.SetDirection (Vector3 direction)
=> Set(ContextKey_TRANSFORM.Direction, direction);
SetInputDirection()
void IuvoUnity.DataStructs.TransformContext.SetInputDirection (Vector3 inputDirection)
=> Set(ContextKey_TRANSFORM.InputDirection, inputDirection);
SetLastDirection()
void IuvoUnity.DataStructs.TransformContext.SetLastDirection (Vector3 lastDirection)
=> Set(ContextKey_TRANSFORM.LastDirection, lastDirection);
SetLookTarget()
void IuvoUnity.DataStructs.TransformContext.SetLookTarget (Vector3 lookTarget)
=> Set(ContextKey_TRANSFORM.LookTarget, lookTarget);
SetMoveSpeed()
void IuvoUnity.DataStructs.TransformContext.SetMoveSpeed (float moveSpeed)
=> Set(ContextKey_TRANSFORM.MoveSpeed, moveSpeed);
SetPosition()
void IuvoUnity.DataStructs.TransformContext.SetPosition (Vector3 position)
=> Set(ContextKey_TRANSFORM.Position, position);
SetTransform()
void IuvoUnity.DataStructs.TransformContext.SetTransform (Transform transform)
=> Set(ContextKey_TRANSFORM.Transform, transform);
SetVelocity()
void IuvoUnity.DataStructs.TransformContext.SetVelocity (Vector3 velocity)
=> Set(ContextKey_TRANSFORM.Velocity, velocity);
TryGet< T >()
bool IuvoUnity.DataStructs.TransformContext.TryGet< T > (ContextKey_TRANSFORM key, out T value) private
            {
                if (_data.TryGetValue(key, out var obj) && obj is T castValue)
                {
                    value = castValue;
                    return true;
                }
                value = default;
                return false;
            }
References _data.
TryGetDestination()
bool IuvoUnity.DataStructs.TransformContext.TryGetDestination (out Vector3 destination)
=> TryGet(ContextKey_TRANSFORM.Destination, out destination);
TryGetDirection()
bool IuvoUnity.DataStructs.TransformContext.TryGetDirection (out Vector3 direction)
=> TryGet(ContextKey_TRANSFORM.Direction, out direction);
TryGetInputDirection()
bool IuvoUnity.DataStructs.TransformContext.TryGetInputDirection (out Vector3 inputDirection)
=> TryGet(ContextKey_TRANSFORM.InputDirection, out inputDirection);
TryGetLastDirection()
bool IuvoUnity.DataStructs.TransformContext.TryGetLastDirection (out Vector3 lastDirection)
=> TryGet(ContextKey_TRANSFORM.LastDirection, out lastDirection);
TryGetLookTarget()
bool IuvoUnity.DataStructs.TransformContext.TryGetLookTarget (out Vector3 lookTarget)
=> TryGet(ContextKey_TRANSFORM.LookTarget, out lookTarget);
TryGetMoveSpeed()
bool IuvoUnity.DataStructs.TransformContext.TryGetMoveSpeed (out float moveSpeed)
=> TryGet(ContextKey_TRANSFORM.MoveSpeed, out moveSpeed);
TryGetPosition()
bool IuvoUnity.DataStructs.TransformContext.TryGetPosition (out Vector3 position)
=> TryGet(ContextKey_TRANSFORM.Position, out position);
TryGetTransform()
bool IuvoUnity.DataStructs.TransformContext.TryGetTransform (out Transform transform)
=> TryGet(ContextKey_TRANSFORM.Transform, out transform);
TryGetVelocity()
bool IuvoUnity.DataStructs.TransformContext.TryGetVelocity (out Vector3 velocity)
=> TryGet(ContextKey_TRANSFORM.Velocity, out velocity);
Member Data Documentation
_data
readonly Dictionary<ContextKey_TRANSFORM, object> IuvoUnity.DataStructs.TransformContext._data = new() private
Referenced by Dispose(), Get< T >(), Set< T >(), TransformContext(), and TryGet< T >().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/TransformContext.cs