Iuvo Unity: IuvoUnity.BaseClasses.ECS.ComponentManager Class Reference
IuvoUnity.BaseClasses.ECS.ComponentManager Class Reference
Public Member Functions
ComponentManager (IuvoEntity myIuvoEntity)
void AddComponent< T > (T component)
T? GetComponent< T > ()
bool TryGetComponent< T > (out T component)
bool HasComponent< T > ()
void RemoveComponent< T > ()
bool TryToRemoveComponent< T > ()
List< IuvoComponentBase > GetAllComponents ()
void ClearComponentManager (IuvoEntity entity)
Properties
IuvoEntity _myIuvoEntity [get, private set]
Private Attributes
Dictionary< Type, IuvoComponentBase > _components = new Dictionary<Type, IuvoComponentBase>()
Constructor & Destructor Documentation
ComponentManager()
IuvoUnity.BaseClasses.ECS.ComponentManager.ComponentManager (IuvoEntity myIuvoEntity)
                {
                    _myIuvoEntity = myIuvoEntity;
                }
References _myIuvoEntity.
Member Function Documentation
AddComponent< T >()
void IuvoUnity.BaseClasses.ECS.ComponentManager.AddComponent< T > (T component)
Type Constraints
T : IuvoComponentBase
                                                                 : IuvoComponentBase
                {
                    _components[typeof(T)] = component;
                    //component.OnAdd(_myIuvoEntity);
                }
References _components.
ClearComponentManager()
void IuvoUnity.BaseClasses.ECS.ComponentManager.ClearComponentManager (IuvoEntity entity)
                {
                    foreach (var component in _components.Values)
                    {
                        //component.OnRemove(entity);
                    }
                    _components.Clear();
                }
References _components.
GetAllComponents()
List< IuvoComponentBase > IuvoUnity.BaseClasses.ECS.ComponentManager.GetAllComponents ()
                {
                    List<IuvoComponentBase> components = new List<IuvoComponentBase>();
                    foreach (var component in _components.Values)
                    {
                        components.Add(component);
                    }
                    return components;
                }
References _components.
Referenced by IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry.BreakdownRemovableComponents(), IuvoUnity.BaseClasses.ECS.ComponentFilter.GetAllComponentsArray(), IuvoUnity.BaseClasses.ECS.ComponentFilter.GetAllComponentsEnumerable(), and IuvoUnity.BaseClasses.ECS.IuvoEntityRegistry.InitializeDefaultComponents().
GetComponent< T >()
T? IuvoUnity.BaseClasses.ECS.ComponentManager.GetComponent< T > ()
Type Constraints
T : IuvoComponentBase
                                                    : IuvoComponentBase
                {
                    if (_components.TryGetValue(typeof(T), out var comp))
                        return comp as T;
                    return null;
                }
References _components.
HasComponent< T >()
bool IuvoUnity.BaseClasses.ECS.ComponentManager.HasComponent< T > ()
Type Constraints
T : IuvoComponentBase
                                                      : IuvoComponentBase
                {
                    return _components.ContainsKey(typeof(T));
                }
References _components.
Referenced by TryToRemoveComponent< T >().
RemoveComponent< T >()
void IuvoUnity.BaseClasses.ECS.ComponentManager.RemoveComponent< T > ()
Type Constraints
T : IuvoComponentBase
                                                         : IuvoComponentBase
                {
                    if (_components.TryGetValue(typeof(T), out var component))
                    {
                        //component.OnRemove(_myIuvoEntity);
                        _components.Remove(typeof(T));
                    }
                }
References _components.
TryGetComponent< T >()
bool IuvoUnity.BaseClasses.ECS.ComponentManager.TryGetComponent< T > (out T component)
Type Constraints
T : IuvoComponentBase
                                                                        : IuvoComponentBase
                {
                    if (_components.TryGetValue(typeof(T), out var comp))
                    {
                        component = comp as T;
                        return true;
                    }
                    component = null;
                    return false;
                }
References _components.
TryToRemoveComponent< T >()
bool IuvoUnity.BaseClasses.ECS.ComponentManager.TryToRemoveComponent< T > ()
Type Constraints
T : IuvoComponentBase
                                                              : IuvoComponentBase
                {
                    if (!HasComponent<T>()) return false;
                    return _components.Remove(typeof(T));
                }
References _components, and HasComponent< T >().
Member Data Documentation
_components
Dictionary<Type, IuvoComponentBase> IuvoUnity.BaseClasses.ECS.ComponentManager._components = new Dictionary<Type, IuvoComponentBase>() private
Referenced by AddComponent< T >(), ClearComponentManager(), GetAllComponents(), GetComponent< T >(), HasComponent< T >(), RemoveComponent< T >(), TryGetComponent< T >(), and TryToRemoveComponent< T >().
Property Documentation
_myIuvoEntity
IuvoEntity IuvoUnity.BaseClasses.ECS.ComponentManager._myIuvoEntity get private set
{ get; private set; }
Referenced by ComponentManager().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/ECS/Components/ComponentManager.cs