Iuvo Unity: IuvoUnity.DataStructs.ConditionContext Class Reference
IuvoUnity.DataStructs.ConditionContext Class Reference
Public Member Functions
ConditionContext ()
void Dispose ()
bool GetIsUnderAttack ()
bool GetIsVisible ()
bool GetIsMoving ()
bool GetIsGrounded ()
bool GetIsAiming ()
bool GetIsDead ()
bool GetIsPaused ()
bool GetIsSprinting ()
Dictionary< ContextKey_STATE, bool > GetAllConditions ()
void SetIsUnderAttack (bool value)
void SetIsVisible (bool value)
void SetIsMoving (bool value)
void SetIsGrounded (bool value)
void SetIsAiming (bool value)
void SetIsDead (bool value)
void SetIsPaused (bool value)
void SetIsSprinting (bool value)
Private Member Functions
bool GetCondition (ContextKey_STATE key)
void SetCondition (ContextKey_STATE key, bool value)
Private Attributes
ConcurrentDictionary< ContextKey_STATE, bool > Conditions = new ConcurrentDictionary<ContextKey_STATE, bool>()
Constructor & Destructor Documentation
ConditionContext()
IuvoUnity.DataStructs.ConditionContext.ConditionContext ()
            {
                foreach (ContextKey_STATE key in System.Enum.GetValues(typeof(ContextKey_STATE)))
                {
                    Conditions[key] = false;
                }
            }
References Conditions.
Member Function Documentation
Dispose()
void IuvoUnity.DataStructs.ConditionContext.Dispose ()
Implements IuvoUnity.Interfaces.IContext.
            {
                Conditions.Clear();
            }
References Conditions.
GetAllConditions()
Dictionary< ContextKey_STATE, bool > IuvoUnity.DataStructs.ConditionContext.GetAllConditions ()
            {
                return new Dictionary<ContextKey_STATE, bool>(Conditions);
            }
References Conditions.
GetCondition()
bool IuvoUnity.DataStructs.ConditionContext.GetCondition (ContextKey_STATE key) private
            {
                return Conditions.TryGetValue(key, out bool value) && value;
            }
References Conditions.
GetIsAiming()
bool IuvoUnity.DataStructs.ConditionContext.GetIsAiming ()
=> GetCondition(ContextKey_STATE.IsAiming);
GetIsDead()
bool IuvoUnity.DataStructs.ConditionContext.GetIsDead ()
=> GetCondition(ContextKey_STATE.IsDead);
GetIsGrounded()
bool IuvoUnity.DataStructs.ConditionContext.GetIsGrounded ()
=> GetCondition(ContextKey_STATE.IsGrounded);
GetIsMoving()
bool IuvoUnity.DataStructs.ConditionContext.GetIsMoving ()
=> GetCondition(ContextKey_STATE.IsMoving);
GetIsPaused()
bool IuvoUnity.DataStructs.ConditionContext.GetIsPaused ()
=> GetCondition(ContextKey_STATE.IsPaused);
GetIsSprinting()
bool IuvoUnity.DataStructs.ConditionContext.GetIsSprinting ()
=> GetCondition(ContextKey_STATE.IsSprinting);
GetIsUnderAttack()
bool IuvoUnity.DataStructs.ConditionContext.GetIsUnderAttack ()
=> GetCondition(ContextKey_STATE.IsUnderAttack);
GetIsVisible()
bool IuvoUnity.DataStructs.ConditionContext.GetIsVisible ()
=> GetCondition(ContextKey_STATE.IsVisible);
SetCondition()
void IuvoUnity.DataStructs.ConditionContext.SetCondition (ContextKey_STATE key, bool value) private
            {
                Conditions[key] = value;
            }
References Conditions.
SetIsAiming()
void IuvoUnity.DataStructs.ConditionContext.SetIsAiming (bool value)
=> SetCondition(ContextKey_STATE.IsAiming, value);
SetIsDead()
void IuvoUnity.DataStructs.ConditionContext.SetIsDead (bool value)
=> SetCondition(ContextKey_STATE.IsDead, value);
SetIsGrounded()
void IuvoUnity.DataStructs.ConditionContext.SetIsGrounded (bool value)
=> SetCondition(ContextKey_STATE.IsGrounded, value);
SetIsMoving()
void IuvoUnity.DataStructs.ConditionContext.SetIsMoving (bool value)
=> SetCondition(ContextKey_STATE.IsMoving, value);
SetIsPaused()
void IuvoUnity.DataStructs.ConditionContext.SetIsPaused (bool value)
=> SetCondition(ContextKey_STATE.IsPaused, value);
SetIsSprinting()
void IuvoUnity.DataStructs.ConditionContext.SetIsSprinting (bool value)
=> SetCondition(ContextKey_STATE.IsSprinting, value);
SetIsUnderAttack()
void IuvoUnity.DataStructs.ConditionContext.SetIsUnderAttack (bool value)
=> SetCondition(ContextKey_STATE.IsUnderAttack, value);
SetIsVisible()
void IuvoUnity.DataStructs.ConditionContext.SetIsVisible (bool value)
=> SetCondition(ContextKey_STATE.IsVisible, value);
Member Data Documentation
Conditions
ConcurrentDictionary<ContextKey_STATE, bool> IuvoUnity.DataStructs.ConditionContext.Conditions = new ConcurrentDictionary<ContextKey_STATE, bool>() private
Referenced by ConditionContext(), Dispose(), GetAllConditions(), GetCondition(), and SetCondition().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/ConditionContext.cs