Iuvo Unity: IuvoUnity.DataStructs.ContextKeyGroups Class Reference
IuvoUnity.DataStructs.ContextKeyGroups Class Reference
Static Public Member Functions
static bool IsValidKey (Enum key)
static void CheckForDuplicateEnumNames ()
Static Public Attributes
static readonly Type[] AllowedKeys
Static Private Member Functions
static void ValidateContextKeys ()
Member Function Documentation
CheckForDuplicateEnumNames()
void IuvoUnity.DataStructs.ContextKeyGroups.CheckForDuplicateEnumNames () static
            {
                // Dictionary to track which enum names appear in which enum types.
                // Key = enum field name (string), Value = list of enum types where this name is found.
                Dictionary<string, List<Type>> nameToEnumTypes = new Dictionary<string, List<Type>>();
                // Iterate through all allowed enum types defined in ContextKeyGroups.
                foreach (Type enumType in AllowedKeys)
                {
                    // Safety check to ensure the type is actually an enum.
                    if (!enumType.IsEnum)
                    {
                        IuvoDebug.DebugLogWarning($"[ContextKeyGroups] Type {enumType.Name} in AllowedKeys is not an enum.");
                        continue;
                    }
                    // Loop through all enum field names (as strings) in the current enum type.
                    foreach (string fieldName in Enum.GetNames(enumType))
                    {
                        // Add the field name to the map, associating it with the current enum type.
                        if (!nameToEnumTypes.ContainsKey(fieldName))
{
                            nameToEnumTypes[fieldName] = new List<Type>();
                        }
                        nameToEnumTypes[fieldName].Add(enumType);
                    }
                }
                // Check for enum field names that appear in more than one enum type.
                foreach (var kvp in nameToEnumTypes)
                {
                    string fieldName = kvp.Key;
                    List<Type> typesWithField = kvp.Value;
                    // If the field name is present in multiple enum types, issue a warning.
                    if (typesWithField.Count > 1)
                    {
                        string typeList = string.Join(", ", typesWithField.Select(t => t.Name));
                        IuvoDebug.DebugLogWarning($"[ContextKeyGroups] Duplicate enum field name \"{fieldName}\" found in multiple enums: {typeList}");
                    }
                }
            }
References AllowedKeys, and IuvoUnity.Debug.IuvoDebug.DebugLogWarning().
Referenced by ValidateContextKeys().
IsValidKey()
bool IuvoUnity.DataStructs.ContextKeyGroups.IsValidKey (Enum key) static
            {
                return Array.Exists(AllowedKeys, t => t == key.GetType());
            }
References AllowedKeys.
Referenced by IuvoUnity.DataStructs.Context.Get< T >(), IuvoUnity.DataStructs.Context.RegisterEvent(), IuvoUnity.DataStructs.Context.RegisterEvent< T >(), and IuvoUnity.DataStructs.Context.TryGet< T >().
ValidateContextKeys()
void IuvoUnity.DataStructs.ContextKeyGroups.ValidateContextKeys () static private
            {
#if UNITY_EDITOR
                ContextKeyGroups.CheckForDuplicateEnumNames();
#endif
            }
References CheckForDuplicateEnumNames().
Member Data Documentation
AllowedKeys
readonly Type [] IuvoUnity.DataStructs.ContextKeyGroups.AllowedKeys static
Initial value:
                                        = new[]
{
    typeof(ContextKey_ACTOR),
    typeof(ContextKey_PLAYER_HANDLERS),
    typeof(ContextKey_STATE),
    typeof(ContextKey_STATS),
    typeof(ContextKey_TRANSFORM),
    typeof(ContextKey_EVENT)
}
            {
                typeof(ContextKey_ACTOR),
                typeof(ContextKey_PLAYER_HANDLERS),
                typeof(ContextKey_STATE),
                typeof(ContextKey_STATS),
                typeof(ContextKey_TRANSFORM),
                typeof(ContextKey_EVENT)
            };
Referenced by CheckForDuplicateEnumNames(), IsValidKey(), and IuvoUnity.DataStructs.Context.Set< T >().
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/DataStructs/Context.cs