Iuvo Unity: IuvoUnity.StateMachines.CSM.ConditionalState Class Reference
IuvoUnity.StateMachines.CSM.ConditionalState Class Reference
Public Member Functions
bool CanInterrupt (ConditionalStateMachine stateMachine)
bool CanExit (ConditionalStateMachine stateMachine)
bool CanEnter (ConditionalStateMachine stateMachine)
bool CanContinue (ConditionalStateMachine stateMachine)
virtual bool InterruptConditionsMet (ConditionalStateMachine stateMachine)
Default implementations of the condition checks, override in derived classes.
virtual bool ExitConditionsMet (ConditionalStateMachine stateMachine)
virtual bool EnterConditionsMet (ConditionalStateMachine stateMachine)
virtual bool ContinueConditionsMet (ConditionalStateMachine stateMachine)
Public Attributes
string stateName
FlexibleEvent< ConditionalStateMachine > OnInterrupt = new FlexibleEvent<ConditionalStateMachine>()
FlexibleEvent< ConditionalStateMachine > OnExit = new FlexibleEvent<ConditionalStateMachine>()
FlexibleEvent< ConditionalStateMachine > OnEnter = new FlexibleEvent<ConditionalStateMachine>()
FlexibleEvent< ConditionalStateMachine > OnContinue = new FlexibleEvent<ConditionalStateMachine>()
List< IStateACondition > stateInterruptConditions = new List<IStateACondition>()
List< IStateACondition > stateExitConditions = new List<IStateACondition>()
List< IStateACondition > stateEnterConditions = new List<IStateACondition>()
List< IStateACondition > stateContinueConditions = new List<IStateACondition>()
ConditionalStateMachineUpdateMode updateMode = ConditionalStateMachineUpdateMode.None
Protected Member Functions
bool AreConditionsMet (List< IStateACondition > conditions)
Member Function Documentation
AreConditionsMet()
bool IuvoUnity.StateMachines.CSM.ConditionalState.AreConditionsMet (List< IStateACondition > conditions) protected
                {
                    if (conditions.Count == 0) return true;
                    foreach (var c in conditions)
                    {
                        if (c == null) continue;
                        if (!c.IsConditionMet()) return false;
                    }
                    return true;
                }
Referenced by ContinueConditionsMet(), EnterConditionsMet(), ExitConditionsMet(), and InterruptConditionsMet().
CanContinue()
bool IuvoUnity.StateMachines.CSM.ConditionalState.CanContinue (ConditionalStateMachine stateMachine)
                {
                    return ContinueConditionsMet(stateMachine);
                }
References ContinueConditionsMet().
CanEnter()
bool IuvoUnity.StateMachines.CSM.ConditionalState.CanEnter (ConditionalStateMachine stateMachine)
                {
                    return EnterConditionsMet(stateMachine);
                }
References EnterConditionsMet().
Referenced by IuvoUnity.StateMachines.CSM.ConditionalStateMachine.TryChangeState().
CanExit()
bool IuvoUnity.StateMachines.CSM.ConditionalState.CanExit (ConditionalStateMachine stateMachine)
                {
                    return ExitConditionsMet(stateMachine);
                }
References ExitConditionsMet().
CanInterrupt()
bool IuvoUnity.StateMachines.CSM.ConditionalState.CanInterrupt (ConditionalStateMachine stateMachine)
                {
                    return InterruptConditionsMet(stateMachine);
                }
References InterruptConditionsMet().
ContinueConditionsMet()
virtual bool IuvoUnity.StateMachines.CSM.ConditionalState.ContinueConditionsMet (ConditionalStateMachine stateMachine) virtual
Implements IuvoUnity.Interfaces.IStateMachineCondition.
                {
                    return AreConditionsMet(stateContinueConditions);
                }
References AreConditionsMet(), and stateContinueConditions.
Referenced by CanContinue().
EnterConditionsMet()
virtual bool IuvoUnity.StateMachines.CSM.ConditionalState.EnterConditionsMet (ConditionalStateMachine stateMachine) virtual
Implements IuvoUnity.Interfaces.IStateMachineCondition.
                {
                    return AreConditionsMet(stateEnterConditions);
                }
References AreConditionsMet(), and stateEnterConditions.
Referenced by CanEnter().
ExitConditionsMet()
virtual bool IuvoUnity.StateMachines.CSM.ConditionalState.ExitConditionsMet (ConditionalStateMachine stateMachine) virtual
Implements IuvoUnity.Interfaces.IStateMachineCondition.
                {
                    return AreConditionsMet(stateExitConditions);
                }
References AreConditionsMet(), and stateExitConditions.
Referenced by CanExit().
InterruptConditionsMet()
virtual bool IuvoUnity.StateMachines.CSM.ConditionalState.InterruptConditionsMet (ConditionalStateMachine stateMachine) virtual
Default implementations of the condition checks, override in derived classes.
Parameters
stateMachine
Returns
Implements IuvoUnity.Interfaces.IStateMachineCondition.
                {
                    return AreConditionsMet(stateInterruptConditions);
                }
References AreConditionsMet(), and stateInterruptConditions.
Referenced by CanInterrupt().
Member Data Documentation
OnContinue
FlexibleEvent<ConditionalStateMachine> IuvoUnity.StateMachines.CSM.ConditionalState.OnContinue = new FlexibleEvent<ConditionalStateMachine>()
OnEnter
FlexibleEvent<ConditionalStateMachine> IuvoUnity.StateMachines.CSM.ConditionalState.OnEnter = new FlexibleEvent<ConditionalStateMachine>()
OnExit
FlexibleEvent<ConditionalStateMachine> IuvoUnity.StateMachines.CSM.ConditionalState.OnExit = new FlexibleEvent<ConditionalStateMachine>()
OnInterrupt
FlexibleEvent<ConditionalStateMachine> IuvoUnity.StateMachines.CSM.ConditionalState.OnInterrupt = new FlexibleEvent<ConditionalStateMachine>()
stateContinueConditions
List<IStateACondition> IuvoUnity.StateMachines.CSM.ConditionalState.stateContinueConditions = new List<IStateACondition>()
Referenced by ContinueConditionsMet().
stateEnterConditions
List<IStateACondition> IuvoUnity.StateMachines.CSM.ConditionalState.stateEnterConditions = new List<IStateACondition>()
Referenced by EnterConditionsMet().
stateExitConditions
List<IStateACondition> IuvoUnity.StateMachines.CSM.ConditionalState.stateExitConditions = new List<IStateACondition>()
Referenced by ExitConditionsMet().
stateInterruptConditions
List<IStateACondition> IuvoUnity.StateMachines.CSM.ConditionalState.stateInterruptConditions = new List<IStateACondition>()
Referenced by InterruptConditionsMet().
stateName
string IuvoUnity.StateMachines.CSM.ConditionalState.stateName
updateMode
ConditionalStateMachineUpdateMode IuvoUnity.StateMachines.CSM.ConditionalState.updateMode = ConditionalStateMachineUpdateMode.None
The documentation for this class was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/StateMachine/ConditionalStateMachine/States/ConditionalState.cs