Iuvo Unity: IuvoUnity.Interfaces.IUpdatable Interface Reference
IuvoUnity.Interfaces.IUpdatable Interface Reference
Public Member Functions
bool HasUpdateMode ()
virtual void OnUpdate ()
void HandleUpdate (StateMachines.CSM.ConditionalStateMachineUpdateMode updateMode)
Public Member Functions inherited from IuvoUnity.Interfaces.IUpdate
void Update ()
Public Member Functions inherited from IuvoUnity.Interfaces.IFixedUpdate
void FixedUpdate ()
Public Member Functions inherited from IuvoUnity.Interfaces.ILateUpdate
void LateUpdate ()
Properties
StateMachines.CSM.ConditionalStateMachineUpdateMode updateMode [get, set]
Member Function Documentation
HandleUpdate()
void IuvoUnity.Interfaces.IUpdatable.HandleUpdate (StateMachines.CSM.ConditionalStateMachineUpdateMode updateMode)
            {
                if ((this.updateMode & updateMode) != 0)
                {
                    switch (updateMode)
                    {
                        case StateMachines.CSM.ConditionalStateMachineUpdateMode.Update:
                            Update();
                            break;
                        case StateMachines.CSM.ConditionalStateMachineUpdateMode.FixedUpdate:
                            FixedUpdate();
                            break;
                        case StateMachines.CSM.ConditionalStateMachineUpdateMode.LateUpdate:
                            LateUpdate();
                            break;
                    }
                }
                OnUpdate();
            }
References IuvoUnity.Interfaces.IFixedUpdate.FixedUpdate(), IuvoUnity.Interfaces.ILateUpdate.LateUpdate(), OnUpdate(), IuvoUnity.Interfaces.IUpdate.Update(), and updateMode.
HasUpdateMode()
bool IuvoUnity.Interfaces.IUpdatable.HasUpdateMode ()
=> updateMode != StateMachines.CSM.ConditionalStateMachineUpdateMode.None;
References updateMode.
OnUpdate()
virtual void IuvoUnity.Interfaces.IUpdatable.OnUpdate () virtual
{ }
Referenced by HandleUpdate().
Property Documentation
updateMode
StateMachines.CSM.ConditionalStateMachineUpdateMode IuvoUnity.Interfaces.IUpdatable.updateMode get set
{ get; set; }
Referenced by HandleUpdate(), and HasUpdateMode().
The documentation for this interface was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Interfaces/IUpdatable.cs