Iuvo Unity: IuvoUnity.Interfaces.IPausable Interface Reference
IuvoUnity.Interfaces.IPausable Interface Reference
Public Member Functions
void OnPause ()
void OnResume ()
void PauseFor (float seconds)
IEnumerator ResumeAfterDelay (float seconds)
Public Member Functions inherited from IuvoUnity.Interfaces.IEnableable
void OnEnable ()
Public Member Functions inherited from IuvoUnity.Interfaces.IActivatable
void OnActivate ()
Properties
bool IsPaused [get, set]
Properties inherited from IuvoUnity.Interfaces.ITogglable
bool IsEnabled [get, set]
bool IsActive [get, set]
Member Function Documentation
OnPause()
void IuvoUnity.Interfaces.IPausable.OnPause () abstract
Referenced by PauseFor().
OnResume()
void IuvoUnity.Interfaces.IPausable.OnResume () abstract
Referenced by ResumeAfterDelay().
PauseFor()
void IuvoUnity.Interfaces.IPausable.PauseFor (float seconds)
            {
                if (!IsPaused)
                {
                    IsPaused = true;
                    OnPause();
                    CoroutineManager.RunCoroutine(ResumeAfterDelay(seconds));
                }
            }
References IsPaused, OnPause(), ResumeAfterDelay(), and IuvoUnity.Singletons.CoroutineManager.RunCoroutine().
ResumeAfterDelay()
IEnumerator IuvoUnity.Interfaces.IPausable.ResumeAfterDelay (float seconds)
            {
                yield return CoroutineManager.GetWaitForSeconds(seconds);
                IsPaused = false;
                OnResume();
            }
References IuvoUnity.Singletons.CoroutineManager.GetWaitForSeconds(), IsPaused, and OnResume().
Referenced by PauseFor().
Property Documentation
IsPaused
bool IuvoUnity.Interfaces.IPausable.IsPaused get set
{ get; set; }
Referenced by PauseFor(), and ResumeAfterDelay().
The documentation for this interface was generated from the following file:
D:/Unity/IuvoUnityCore/Assets/IuvoUnity/Runtime/Interfaces/ITogglable.cs